### ISSUE TITLE
Improve and document the debug method for Genesis during hardware discovery 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1024]
- A way to trace the discovery process to see what is going on (standard messages that come back to the xCAT management node showing progress...)
- How do we know discovery is complete? 
- xCAT prints this message in `doxcat`  which is confusing, because it does not tell the user whether something went wrong.  This is normal behavior, so we should indicate that Genesis is waiting for new instructions, but is normal.  

```
echo -en "Received request to retry in a bit, will call xCAT back in $delay seconds  \r"
```
- Can we get rid of `xCAT-nbroot2` from the code tree? Why is it left around? 
- Document a end to end flow for hardware discovery: 
  - with bmcsetup executed
  - without bmcsetup

**Comment by daniceexi** [comment]
@xuweibj is working on an item to add more debug information in genesis to indicate the progress of discovery.
Yes, remove nbroot dir is OK.

**Comment by pdlun92** [comment]
Some related suggestions / comments...

looking at `/var/log/messages` from MN running discovery

```
May  6 15:24:32 fs1 xcat[135132]: xcatd: Processing discovery request from 192.168.5.153
May  6 15:24:32 fs1 xcat[135132]: Discovery Error: Could not find any node.
May  6 15:24:32 fs1 xcat[135132]: Discovery Error: Could not find any node.
```
Perhaps this "error" message should be more detailed.  One suggestion would be to include the name of the plugin or sub routine that is sending the message.  Additionally, I'm not sure if this is truly an indication of an error or just a part of the discovery process. Maybe "Discovery Error" is not appropriate.

```
May  6 15:24:03 fs1 xcat[135132]: xcatd: Processing discovery request from 192.168.5.153
...
May  6 15:24:11 fs1 xcat[135132]: xcatd: Processing discovery request from 192.168.5.153
```

Looking at timestamps, I believe this message is repeated so quickly due to a sleep(5) in the dodiscover code.  This may be sent too often and therefore not work well to scale

I may update this comment with additionally debug observations / suggestions as we run in to them

**Comment by immarvin** [comment]
hi @xuweibj , has this been fixed?

**Comment by xuweibj** [comment]
I think this had been fixed. I have added some log in doxcat. Hi @whowutwut , could we close this or I should add some more?

**Comment by immarvin** [comment]
hi @whowutwut , would you please take a look at this? is it ok to close it?

**Comment by whowutwut** [comment]
I will close this for now, will look at some of the code removal and documentation in the next release
