### ISSUE TITLE
[DEV]is it ok to modify "xcat-genesis-base-amd64" to "xcat-genesis-base-x86_64" in the dependency of "xCAT-genesis-scripts/debian/control" ?

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#1074]
Currently,  xCAT-genesis-scripts  depends on the "xcat-genesis-base-amd64", the deb package "xcat-genesis-base-amd64" is a "noarch" package and intended to be installed on MN. The "amd64" in the package name just indicate that the package includes some executable binaries that will be run on x86_64 compute nodes.

Since  "xcat-genesis-base-amd64" deb package is converted from "xcat-genesis-base-x86_64" rpm package with "alien", the name of the original converted deb package is "xcat-genesis-base-x86_64" , which is the same as source rpm package, we need 4 steps to produce a   "xcat-genesis-base-amd64" deb package:
1. generate <xcat-genesis-base-x86_64.deb> with "alien --scripts -k  <xcat-genesis-base-x86_64.rpm>"
2. extract the  "xcat-genesis-base-x86_64" deb package,
3. then modify the package name in the debian/control to be "xcat-genesis-base-amd64",
4. then repackage it. 

We might need to see whether is it ok to modify "xcat-genesis-base-amd64" to "xcat-genesis-base-x86_64" in the dependency of "xCAT-genesis-scripts/debian/control", so that we only need step#1.

**Comment by whowutwut** [comment]
Thanks for looking into this issue...  I do agree that we should reduce the number of steps, or we need to have a script that will automatically create the whole genesis-base files...  maybe using a docker container and having a script run that will do all the conversion for us

Are all the debian packages using the `amd64` as the architecture? 
What happens if we rename the rpm from `x86_64` to `amd64` before running the alien command? Or is it because `x86_64` is built into the rpm package and it's not just a rename

**Comment by immarvin** [comment]
hi @whowutwut , the "package name" and “arch” are packaged into the debian packages(specified in DEBIAN/control file, ), and the "apt-get" use the info inside packages.  Renaming the package file name does not change anything except file name.

The ubuntu deb packages use "amd64" instead of "x86_64" in the "arch"  of the package, but for the "genesis-base" package, the package arch is "noarch", the "amd64" or "x86_64" in the package name just indicates that the binaries in the package will be run on the compute nodes with "x86_64" architecture.

**Comment by daniceexi** [comment]
Since the 'x86_64' just a word in the package name instead of real arch, so may change the genesis-script to require ``xcat-genesis-base-x86_64`` instead of ``xcat-genesis-base-amd64``. Then we don't need to repackage the genesis-base for ubuntu to change the package name.

~~~~
./xCAT-genesis-scripts/debian/control:Depends: xcat-genesis-base-amd64[any-amd64],xcat-genesis-base-ppc64[any-ppc64el]
~~~~

**Comment by immarvin** [comment]
hi @zet809  , since you are working on the repackaging of "xcat-genesis-base", can you take this issue into consideration?
thanks

**Comment by neo954** [comment]
Hello Everyone,

I suggest we change the package name back to ``xcat-genesis-base-amd64`` before we release xCAT 2.12.2. I have a bunch of reasons. I listed them below.

  * For RPM package, we choose the package name ``xCAT-genesis-base-x86_64``. But the underscore character, ``_`` is not a valid character in the DEB package name, which cause the DEB package name changed to ``xcat-genesis-base-x86-64``. Beside the uppercase-vs-lowercase-letters difference, we get one extra obscure difference (underscore, ``_`` vs dash, ``-``) between the package name of RPM and DEB.
  * We did not get the benefit @immarvin mentioned in the original issue description.  Since we still need to tweak the ``control`` file. That is due to we still need to handle the uppercase-vs-lowercase-letters difference between RPM and DEB package. We have to handle the package dependency properly.
  * After we change the package name to ``xcat-genesis-base-x86-64``. All existing users of xCAT 2.10, 2.11, 2.12, 2.12.1 cannot use the latest ``xcat-dep`` tarball any more, due to the name changing of the package. Soon after we release 2.12.2, we have to face this problem and put extra effort to handle it properly.

Conclusion, leave the package name as its original shape ``xcat-genesis-base-amd64`` can make our lives easier.

**Comment by whowutwut** [comment]
Seems like reasonable reasons to change the name back to amd64. We should try and follow Debian naming conventions ...

**Comment by zet809** [comment]
I agree with @neo954 that we shall not modify the package name from amd64 to x86-64. We got no benefit from it but suffering a lot.

**Comment by daniceexi** [comment]
Good, then we made the agreement that revert all the changes we have made for the genesis name changing. 

To achieve our original idea to simplify the procedure to make genesis-base, we might work out a script to reduce the complicacy of the procedure.
