### ISSUE TITLE
xcatdebugmode should allow setting per individual node

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#1082]
Currently xcatdebugmode is set in the site table.
As a result, it affects all the nodes managed by the MN.
Perhaps it is better to have an ability to set xcatdebugmode for individual nodes.

**Comment by whowutwut** [comment]
To add to this issue, one Use Case to back this requirement is that having `xcatdebugmode` turned on, causes problems in provisioning normal Ubuntu compute nodes. We might be debugging a single node installation, and having `xcatdebugmode=2` would prevent the system admin from re-provisioning any other node because it would stop the install to go into debug mode.

**Comment by daniceexi** [comment]
Yes, we can add an attribute to control that. 

Then the problem turns to which table should be used.  Several weeks ago, @xuweibj add an attribute ``syslog`` in the ``noderes`` table to indicate whether running the syslog for a specific compute node. But I don't think the ``noderes`` is the best place. We might need to add a new table to control the switches for a compute node.

**Comment by penguhyang** [comment]
This feature will move to 2.12.4

**Comment by whowutwut** [comment]
@penguhyang  has any investigation been done to estimate the size of this work?

**Comment by penguhyang** [comment]
@whowutwut No, I will try this on next release.

**Comment by robin2008** [comment]
It is better to support pass an environment variable for an on-demand debuging requresting, for example,  `XCAT_DEBUGMODE=1 nodeset xxx`

**Comment by gurevichmark** [comment]
Yes, that would work also.
