### ISSUE TITLE
[DEV] for diskless installation, the log can't forward to MN when xcatdebugmode=2

### ISSUE THREAD

**Issue by penguhyang** [xcat2/xcat-core#1083]
For redhat, sles, ubuntu.
The diskless installation log can't be forwarded to MN.

**Comment by daniceexi** [comment]
@penguhyang Please open a bug for this issue.
Since this is not a critical issue and the change is big, I recommend to check in this fix for 2.12.1.

**Comment by whowutwut** [comment]
@penguhyang @daniceexi  Before we get too far here...  

I'd like to discuss whether we should change xcatdebugmode to only support off and on..    

After using this for some time, I don't see the use case for having debugmode=1.  If you can tell me, I would appreciate it.  I'm trying to understand when a user would want to use mode=1 over mode=2.  If I think about this myself, i would always use 2 because I want to have the ability to ssh into the installer if possible.  I don't want to try to use mode=1 and then realize I need to ssh into the installer, and then I need to re-provision again.  

Just supporting 1 mode would also simplify a lot of these checks in the code.. .which I dislike the tests for.

**Comment by daniceexi** [comment]
@whowutwut In the original design, we just supported the mode=1. But we found the enabling of the ``ssh`` in the installer causes the pause on ``sles and Ubuntu`` and the install process only can continue after user's interaction. I think this is not convenient for common user. Then designed changed to:

* for all the no-pause debug features will be enabled by mode=1
* the mode=2 will enable the debug features which are enabled by mode=1 plus the debug feature which will cause pause (sshd only now)

**Comment by whowutwut** [comment]
So mode=1 allows you to debug during the time that the installer is running but will continue to run and complete the install... ?

So then i guess my 2nd question....  if nothing bad happens during the install, why does the admin ever need to query anything with the installer.  I noticed that on our shared development cluster, when I set `xcatdebugmode=2` that others trying to provision Ubuntu OS would fail.  Is that a reason to set `xcatdebugmode=1` ,so we can debug certain machines while at the same time keep OS provisioning going on the rest of the cluster? 

I am also wondering if we can poll the direct team to see who has used xcatdebugmode=1 and the use case.  I just think having this mode is adding complexity to the code that is not required.  If no one ever uses it, then it's a feature that provides no value while adding complexity to the code.

**Comment by daniceexi** [comment]
@whowutwut Yes, your understanding is correct.

My thought is a little different than yours. I don't think there are too much people know how to debug/what to debug in the installer (e.g. anaconda). So my suggestion is that if a user encountered an OS deployment issue, enable the xcatdebugmode=1 and do deployment again. Then try to diagnostic from the logs. If they could fine something which related to the installer, he/she could enable the xcatdebugmode=2 and try to log in the installer and debug more. Otherwise, send the logs to xCAT team for help.
