### ISSUE TITLE
[FVT] stop=yes label and wait for installed sentence are missed in automation test environment

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1179]
Description:
case: Diskless_installation_flat_p8_le, there is a label stop:yes, and after rnetboot, there is a sentence in line34 to wait for CN is booted, but these 2 are missed in /opt/xcat/share/xcat/tools/autotest/testcase/installation/Diskless_installation_flat_p8_le.

ENV: PPC64le, sles12.1

This reproduced several times, and will track the reason continuely

**Comment by hu-weihua** [comment]
@caomengmeng , after checking, I found this isn't problem of ``xcattest`` or other regular things. just because ``xCATreg`` has been changed by someone for unknown reason in autotest control node.

The code running now is

     709 sub do_test {
      .......
     716         my $regconf=$mn.".conf";
     717         my $res = system("scp $configfiledir/$regconf root\@$confkeys{$mn}:/opt/xcat/share/xcat/tools/autotest/default.conf  >/dev/null");
     718         my $res1 = system("scp /Diskless_installation_flat_p8_le root\@$confkeys{$mn}:/opt/xcat/share/xcat/tools/autotest/testcase/installation  >/dev/null");

So, no matter what ``Diskless_installation_flat_p8_le`` is in our daily build, it will be replaced by one file named ``Diskless_installation_flat_p8_le`` in control node. so in fact, the file run in auto test is the file which come from control node.

**Comment by caomengmeng** [comment]
@junxiawang Did this change before, and she will submit a pull request to handle all the other changes by her to Git.
After code merged, I will use the latest code directly from Git. 
Thanks @hu-weihua

**Comment by caomengmeng** [comment]
xCATreg.pl is changed back in local by @junxiawang, so close this issue
