### ISSUE TITLE
Configuring xCAT to use an existing intermediate CA 

### ISSUE THREAD

**Issue by samveen** [xcat2/xcat-core#1266]
As part of our infrastructure, we use our own in-house Certificate authority. We were wondering if we could somehow configure `xCAT` to use a existing set of certificates for it's inbuilt Certifying Authority instead of it building it's own during installation.

The reason is that we want to be able to verify all certificates against our in-house CA.  As the inhouse CA's cert is added into the certificate bundles of all our hosts, thus if the xCAT CA was an intermediate CA of our in-house CA, then every certificate generated by it would be verifiable without any extra effort on our part.

If so,
- Could I get instructions to do this?
- Could this step be added be added to the `xCAT` package install?

**Comment by daniceexi** [comment]
xCAT calls ``xcatconfig`` to create certificates. ``xcatconfig`` calls ``/opt/xcat/share/xcat/scripts/setup-xcat-ca.sh`` to create CA. Could you make a CA and sign it by your root CA, then pass it to ``xcatconfig``, so that xcatconfig will use it instead of creating a new one.

Steps you can try:
1. create your CA and copy it ``/etc/xcat/ca/``
2. run ``/opt/xcat/share/xcat/scripts/setup-local-client.sh``
3. run ``/opt/xcat/share/xcat/scripts/setup-server-cert.sh``
4. restart xcatd
5. check whether ``lsdef`` command works well

BTW, it's not easy to inject CA during the xCAT install.

**Comment by whowutwut** [comment]
@daniceexi  Just some thought, maybe we can have some environment variables in the pre/post install scripts of the RPM that could take these types of configuration and install xCAT using those files?

**Comment by daniceexi** [comment]
@whowutwut it's doable, but is a little complicated to use and debug. Make user to rerun the 'xcatconfig' after the xCAT installation might be simpler.

**Comment by gurevichmark** [comment]
This issue has been open for a long time. I do not think we have resources to do this.
