### ISSUE TITLE
[fvt]xcatd restart failed using latest build during loading  docker.pm

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#132]
1.down load the latest build
[root@c910f02c01p13 /]# xcatd -f
Error loading module /opt/xcat/lib/perl/xCAT_plugin/docker.pm  ...skipping
2.xcatd -f 
[root@c910f02c01p13 /]# xcatd -f
Error loading module /opt/xcat/lib/perl/xCAT_plugin/docker.pm  ...skipping
3.[root@c910f02c01p13 /]# xcatd -f
Error loading module /opt/xcat/lib/perl/xCAT_plugin/docker.pm  ...skipping

**Comment by daniceexi** [comment]
@bybai Could you take a look why the docker.pm affacts the start of xcatd?

**Comment by bybai** [comment]
Fixed；

Before fix：
at-core]# perl -c ./xCAT-server/lib/xcat/plugins/docker.pm
Bareword "SSL_VERIFY_PEER" not allowed while "strict subs" in use at ./xCAT-server/lib/xcat/plugins/docker.pm line 312.
./xCAT-server/lib/xcat/plugins/docker.pm had compilation errors.

After fix：
re]# perl -c ./xCAT-server/lib/xcat/plugins/docker.pm
./xCAT-server/lib/xcat/plugins/docker.pm syntax OK

c910f03c05k06:/opt/xcat/lib/perl/xCAT_plugin # service xcatd status
xcatd.service - LSB: xCATd
   Loaded: loaded (/etc/init.d/xcatd)
   Active: active (running) since Mon 2015-08-31 09:24:13 EDT; 6s ago
  Process: 16135 ExecStop=/etc/init.d/xcatd stop (code=exited, status=0/SUCCESS)
  Process: 16152 ExecStart=/etc/init.d/xcatd start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/xcatd.service
           `-16191 /usr/sbin/in.tftpd -v -l -s /tftpboot -m /etc/tftpmapfile4xcat.conf

Aug 31 09:24:14 c910f03c05k06 xcat[16194]: xcatd: possible BUG encountered by xCAT UDP service: Undefin
