### ISSUE TITLE
rmkit -f essl failed to remove the essl kit. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1326]
My osimage is : 
lsdef -t osimage rh72diskfull1621
Object name: rh72diskfull1621
    exlist=/install/osimages/rh72diskfull1621/kits/KIT_COMPONENTS.exlist
    imagetype=linux
    kitcomponents=essl-license-5.5.0-0-rhels-7.2-ppc64le,xlf.license-compute-15.1.3-0-rhels-7.2-ppc64le,essl-computenode-5.5.0-0-rhels-7.2-ppc64le,xlc.compiler-compute-13.1.3-0-rhels-7.2-ppc64le,xlf.rte-compute-15.1.3-0-rhels-7.2-ppc64le,xlc.license-compute-13.1.3-0-rhels-7.2-ppc64le,xlf.compiler-compute-15.1.3-0-rhels-7.2-ppc64le,xlc.rte-compute-13.1.3-0-rhels-7.2-ppc64le,essl-loginnode-5.5.0-0-rhels-7.2-ppc64le,pessl-loginnode-5.2.0-0-rhels-7.2-ppc64le,pessl-license-5.2.0-0-rhels-7.2-ppc64le,pessl-computenode-5.2.0-0-rhels-7.2-ppc64le
    osarch=ppc64le
...
------------------------------------------------------------------------------------------------------------------------
[root@c712ems4 test_nogpu]# rmkit -f essl
Removing kit essl-5.5.0-0-ppc64le
Error: Command failed: rmkitcomp. Error message: kitcomponent pperte-compute basename does not existRemoving kitcomponent essl-computenode-5.5.0-0-rhels-7.2-ppc64le from osimage rh72diskfull1621kitcomponents essl-computenode-5.5.0-0-rhels-7.2-ppc64le were removed from osimage rh72diskfull1621 successfully.

Error: Failed to remove kit component essl-computenode-5.5.0-0-rhels-7.2-ppc64le from rh72diskfull1621

**Comment by bybai** [comment]
Hi @wwzhubj , For test kit, rmkit can works, so I need your environment to reproduce this issue:
[root@c910f05c01bc06 testkit]# addkit testkit-1.0-1.tar.bz2
Adding Kit testkit-1.0-1
Kit testkit-1.0-1 was successfully added.
[root@c910f05c01bc06 testkit]# addkitcomp -i rhels7.1-x86_64-netboot-compute "testkit_compute-1.0-1-rhels-7.1-x86_64"
Assigning kit component testkit_compute-1.0-1-rhels-7.1-x86_64 to osimage rhels7.1-x86_64-netboot-compute
Kit components testkit_compute-1.0-1-rhels-7.1-x86_64 were added to osimage rhels7.1-x86_64-netboot-compute successfully
[root@c910f05c01bc06 testkit]# rmkit "testkit-1.0-1"
Removing kit testkit-1.0-1
Error: Failed to remove kit component testkit_compute-1.0-1-rhels-7.1-x86_64 because:testkit_compute-1.0-1-rhels-7.1-x86_64 is being used by osimage rhels7.1-x86_64-netboot-compute
[root@c910f05c01bc06 testkit]# rmkit "testkit-1.0-1" -f
Removing kit testkit-1.0-1
Kit testkit-1.0-1 was successfully removed.

**Comment by wwzhubj** [comment]
how to recreate: 
<1. addkit pessl-5.2.0-0-ppc64le.tar.bz2
2. create a image and add the pessl license, loginnode kitcomponent  with "-f", (since it has dependency on ppe_rte). 
[root@c712ems4 PESSL]#  addkitcomp -i test pessl-license-5.2.0-0-rhels-7.2-ppc64le,pessl-loginnode-5.2.0-0-rhels-7.2-ppc64le -f
Assigning kit component pessl-loginnode-5.2.0-0-rhels-7.2-ppc64le to osimage test
Assigning kit component pessl-license-5.2.0-0-rhels-7.2-ppc64le to osimage test
Kit components pessl-loginnode-5.2.0-0-rhels-7.2-ppc64le,pessl-license-5.2.0-0-rhels-7.2-ppc64le were added to osimage test successfully
3. [root@c712ems4 PESSL]# rmkit pessl
Removing kit pessl-5.2.0-0-ppc64le
Error: Failed to remove kit component pessl-loginnode-5.2.0-0-rhels-7.2-ppc64le because:pessl-loginnode-5.2.0-0-rhels-7.2-ppc64le is being used by osimage test>

**Comment by bybai** [comment]
After fixed this issue in pull request #1385, rmkit --force can work well. But rmkit call rmkitcomp in its code, rmkitcomp --force return some incorrect error messages, open another issue #1384 to trace rmkitcomp issue.

**Comment by bybai** [comment]
At last， issue #1326 is the same with #1384, so close issue #1384.

**Comment by wwzhubj** [comment]
Have test it on 6/30 build , closed it.
