### ISSUE TITLE
[FVT]lsdef/mkdef commands "Error: Unsupported request" error on rh6.8 ppc64

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#1369]
Description: using latest daily build to install rh6.8 on ppc64, after xcat is installed successfully, the lsdef/makedef commands return error message. See below for details:

Test ENV:
```
[root@c910f02c08p08 ~]# cat /etc/*release
Red Hat Enterprise Linux Server release 6.8 (Santiago)
Red Hat Enterprise Linux Server release 6.8 (Santiago)
[root@c910f02c08p08 ~]# rpm -qa | grep -i xCAT
conserver-xcat-8.1.16-10.ppc64
xCAT-buildkit-2.12.1-snap201606220646.noarch
perl-xCAT-2.12.1-snap201606220645.noarch
xCAT-server-2.12.1-snap201606220645.noarch
xCAT-genesis-scripts-ppc64-2.12.1-snap201606220646.noarch
ipmitool-xcat-1.8.15-1.ppc64
grub2-xcat-2.02-0.16.el7.snap201506090204.noarch
xCAT-2.12.1-snap201606220646.ppc64
xCAT-genesis-base-ppc64-2.12-snap201605051443.noarch
xCAT-client-2.12.1-snap201606220645.noarch
xCAT-test-2.12.1-snap201606220646.noarch
```
Details:

```
[root@c910f02c08p08 ~]# service xcatd restart
Restarting xcatd Error loading module /opt/xcat/lib/perl/xCAT_plugin/DBobjectdefs.pm  ...skipping
                                                           [  OK  ]
[root@c910f02c08p08 ~]# lsdef -v
Error: Unsupported request
[root@c910f02c08p08 ~]# mkdef -v
Error: Unsupported request 
```

**Comment by immarvin** [comment]
btw, there is a warning in:
````
[root@c910f02c08p08 ~]# perl -I /opt/xcat/lib/perl/ -c /opt/xcat/lib/perl/xCAT_plugin/DBobjectdefs.pm 
Variable "$objfiledata" will not stay shared at /opt/xcat/lib/perl/xCAT_plugin/DBobjectdefs.pm line 678.
```` 

the 2 issues are caused by the syntax restrict in perl v5.10.1 

[root@c910f02c08p08 ~]# perl -v

This is perl, v5.10.1 (*) built for ppc64-linux-thread-multi

Copyright 1987-2009, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

fixed in https://github.com/xcat2/xcat-core/pull/1370

**Comment by caomengmeng** [comment]
Works well in daily these days, so close it.
