### ISSUE TITLE
[DEV] record the status change of CN in computes.log file is helpful when debug OS installation. 

### ISSUE THREAD

**Issue by penguhyang** [xcat2/xcat-core#1427]
Currently, the CN installation information can be forwarded to MN without the CN status change.
It's can be helpful for user if they know the CN status and the CN status change time.
For example:
```
...
<node> status: booting
<node> statustime: 06-29-2016 05:51:19
...
<node> status: installing
<node> statustime: 06-29-2016 05:53:08
...
```
Also, if user use ``rpower`` command to change the node status. It should be record in computes.log file in MN.

**Comment by daniceexi** [comment]
yes, I think this is a good idea.

**Comment by immarvin** [comment]
hi @penguhyang , some comments:
1. according to the rsyslog rules shipped by xCAT, computes.log only contains the logs forwarded  from the compute nodes. Since the computes.log is occupied by rsyslog, it is unsafe to write log messages directly to it. So you should write the status change logs via ``logger`` in bash or ``Sys::Syslog`` http://perldoc.perl.org/Sys/Syslog.html in perl  , the right file containing the status change log should be "clusters.log"

2.Since the status log action is trigger by the status reporting with "updateflag" from compute nodes, you can get the ip address of the computes nodes reporting status, you need to contain the ip address or hostname information in your log message

**Comment by immarvin** [comment]
please implement the "booted" status logging first, so that PR https://github.com/xcat2/xcat-core/pull/1424 is no longer needed
