### ISSUE TITLE
xCAT version can not be updated after update the xCAT. 

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1523]
I updated xCAT from Jun 30 to July 7, but after the update, the lsxcatd -v still show  Jun 30. 
after I download the xcat-core-2.12.1-linux.tar.bz2
```
 ls -l /tmp/xcat/xcat-core-2.12.1-linux.tar.bz2
-rw-r--r-- 1 root root 4015741 Jul  8 03:34 /tmp/xcat/xcat-core-2.12.1-linux.tar.bz2
./mklocalrepo.sh
yum update xCAT*
yum update *xCAT*
```
```
[root@c712ems4 ppc64le]# lsxcatd -v
Version 2.12.1 (git commit 86e7530395f4cf7a0ad9a261e203d1fd57b04516, built Thu Jun 30 09:30:56 EDT 2016)
```
then 
```
[root@c712ems4 ppc64le]# rpm -aq | grep -i xcat
perl-xCAT-2.12.1-snap201607070618.noarch
ipmitool-xcat-1.8.15-1.ppc64le
xCAT-2.12.1-snap201607070618.ppc64le
grub2-xcat-2.02-0.16.el7.snap201506090204.noarch
xCAT-genesis-base-ppc64-2.12-snap201605051443.noarch
xCAT-server-2.12.1-snap201607070618.noarch
conserver-xcat-8.1.16-10.ppc64le
xCAT-buildkit-2.12.1-snap201607070618.noarch
xCAT-client-2.12.1-snap201607070618.noarch
xCAT-genesis-scripts-ppc64-2.12.1-snap201607070618.noarch
xCAT-probe-2.12.1-snap201607070618.noarch
[root@c712ems4 ppc64le]# lsxcatd -v
Version 2.12.1 (git commit 86e7530395f4cf7a0ad9a261e203d1fd57b04516, built Thu Jun 30 09:30:56 EDT 2016)
```

The date is not updated until I ran service restart xcatd,

**Comment by daniceexi** [comment]
@wwzhubj Do you still have a message of xCAT update?  
Could you recreate it again? We'd like to take a look your env before you manually restart the xcatd

**Comment by whowutwut** [comment]
@daniceexi  why do you need to look at the environment before restarting xcatd?  

It is re-creatable in our own environment.  I did this today. 

```
[root@fs2vm110 xcat-core]# lsxcatd -a 
Version 2.12.1 (git commit 86e7530395f4cf7a0ad9a261e203d1fd57b04516, built Thu Jun 30 09:30:56 EDT 2016)
This is a Management Node
dbengine=SQLite

[root@fs2vm110 xcat-core]# service xcatd restart 
Restarting xcatd (via systemctl):  Warning: xcatd.service changed on disk. Run 'systemctl daemon-reload' to reload units.
                                                           [  OK  ]

[root@fs2vm110 xcat-core]# lsxcatd -a 
Version 2.12.1 (git commit 0919bf649d99fc957236dbb42cfa3afc087ddad2, built Thu Jul  7 06:18:01 EDT 2016)
This is a Management Node
dbengine=SQLite
```

Seems like without a reload of the daemon, it's not picking up the changes in `/opt/xcat/lib/perl/xCAT/Version.pm`

**Comment by daniceexi** [comment]
I did several updates before when I tested the GA build, but did not see this issue. I'll try to recreate.

**Comment by daniceexi** [comment]
@junxiawang verified several OS, could not recreate this issue.
@whowutwut You could leave it for me to debug before restart xcatd if you can recreate the issue.

**Comment by whowutwut** [comment]
@daniceexi  I will send you the environment/steps in email

**Comment by whowutwut** [comment]
@wwzhubj  As I was re-creating the environment for @daniceexi , I noticed that the first time when I was able to re-create it, I used your method 
```
yum update xCAT*
yum update *xCAT*
```
However, I think this is incorrect, what we document is to run `yum install '*xCAT*' ` using quotes, I believe this is what caused the behavior you are seeing.

**Comment by daniceexi** [comment]
@whowutwut Thanks for recreating this issue.

Yes, the root cause was the incorrect usage of yum:
~~~~
yum update xCAT*
yum update *xCAT*
~~~~

With the above commands order, the package ``xCAT`` was installed first and then the package ``perl-xCAT``. But the version number which displayed by ``lsxcatd -a`` was loaded from the file which is installed by the ``perl-xCAT``. So the result was the new installed xcatd has been restarted, but the **version number** was incorrect since the version file has not been updated when restarting xcatd.
~~~~
# rpm -qi xCAT-2.12.1-snap201607070618.ppc64le |  grep 'Install Date'
Install Date: Sun Jul 17 07:53:50 2016
# rpm -qi perl-xCAT-2.12.1-snap201607070618.noarch |  grep 'Install Date'
Install Date: Sun Jul 17 07:55:38 2016
~~~~

So I mark this issue as invalid. Using ``go-xcat`` can avoid this kind of issue.

**Comment by wwzhubj** [comment]
Close it since it's  incorrect usage.
