### ISSUE TITLE
go-xcat update will continue even if required repoquery command is not installed

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1641]
Using `go-xcat` to update a development version of xCAT... 
```
# /tmp/go-xcat --xcat-version=devel update
....
....
Complete!
Command "repoquery" not found.  <=======================
go-xcat: Above listed required command(s) not found.
Command "repoquery" not found. <=======================
go-xcat: Above listed required command(s) not found.

xCAT Core Packages
==================

Package Name                Installed                      In Repository                 
------------                ---------                      -------------                 
Command "repoquery" not found.    <=======================
go-xcat: Above listed required command(s) not found.
perl-xCAT                   2.12.2-snap201608040616                                      
xCAT                        2.12.2-snap201608040616                                      
xCAT-buildkit               2.12.2-snap201608040616                                      
xCAT-client                 2.12.2-snap201608040616                                      
xCAT-confluent              (not installed)                                              
xCAT-genesis-scripts-ppc64  2.12.2-snap201608040616                                      
xCAT-genesis-scripts-x86_64 (not installed)                                              
xCAT-server                 2.12.2-snap201608040616                                      
xCATsn                      (not installed)                                              
xCAT-SoftLayer              (not installed)                                              
xCAT-test                   (not installed)                                              
xCAT-vlan                   (not installed)            
...
```

we see messages that repoquery is not found.  

I think we should pre-check for required commands, or we do not run go-xcat.  We don't want the user to see errors when running the go-xcat.

**Comment by tingtli** [comment]
update is a second version for the go-xcat, we need to add cases to cover this option

**Comment by neo954** [comment]
It worked as design.

The command ``repoquery`` is provided by the RPM package ``yum-utils`` on RHEL. And package ``yum-utils`` will be installed even if you choose "minimal install" during the operating system installation. Thus, there is no way to get a living RHEL system without the command ``repoquery``.

There is where xCAT involved. When you install a compute node with xCAT. xCAT will pass a package list to the operating system installer. Other then the default package list provided by the operating system installer. In xCAT, the default package list for RHEL provided xCAT has even less packages listed there than the default one, or the minimal one provide by Red Hat. That is how you get a RHEL system without command ``repoquery``. And ``go-xcat`` can do nothing with it. Since you already installed your compute nodes with xCAT. It is not the typical scenario where ``go-xcat`` will face with. In a typical scenario, the end user install the operating system of management node manually, not by xCAT. To say the least, if you intend to install another xCAT management node by xCAT, you need do it with a customized osimage definition, remove the postscript ``syslog``, add package ``yum-utils`` to the package list. The default osimage definition shipped with xCAT is for a regular compute node, not for another xCAT management node.

Further still, without command ``repoquery``, ``go-xcat`` will lack some functions, failed to get the package list from yum repository. Failed to get the version number of a package in the yum repository. Any access for detail information from yum repository will fail. But, even in this situation, ``go-xcat`` will get xCAT installed or updated properly. Of cause with all the limitation I mentioned above.

This is worked as design.

**Comment by neo954** [comment]
BTW, @whowutwut, what is the proper behavior you expect for ``go-xcat`` in this situation?

**Comment by whowutwut** [comment]
@neo954 Sorry for my delay response.  

Yes, I agree that in a normal customer situation, this should not ever occur. 

But many of us in the dev/test teams are using xCAT to install another node to become mgmt nodes. 
It would be better if we do things to ensure that the script runs without any errors.   Seeing WARNINGS is not good and not everyone know that yum-utils provides repoquery. So having a message print out would save us time...   Especially since you can't run `yum install repoquery`. 

While it's not required to install xCAT, i think the end user would be curious as to what is displayed if repoquery is there, so I think it's better to provide any help whenever possible. 

Would expect the following behavior: 
```
# /tmp/go-xcat
ERROR: The 'repoquery' command is not found. Install the 'yum-utils' package and rerun
```

**Comment by whowutwut** [comment]
Looks good regarding the issue opened
```
[root@fs2vm110 ~]# /tmp/go-xcat --xcat-version=devel update
Operating system:   linux
Architecture:       ppc64le
Linux Distribution: rhel
Version:            7.2

Reading repositories ...... done

xCAT is going to be updated.
Continue? [y/n] y
Command "repoquery" not found.
go-xcat: Install the `yum-utils' package and rerun.
go-xcat: Failed to get package list from repository `xcat-core'.
[root@fs2vm110 ~]#
```
