### ISSUE TITLE
incorrect warning message when define an osimage

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#1660]
I have an stanza file: 
```
[root@c712ems4 0809]# cat /tmp/ww.file
# <xCAT data object stanza file>

rh72openpower4DL1632:
    objtype=osimage
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.2-ppc64le
    osname=Linux
    osvers=rhels7.2
    otherpkgdir=/install/post/otherpkgs/rhels7.2/ppc64le/rh72diskless1620
    otherpkglist=/install/custom/gpfs/gpfs.otherpkgs.pkglist,/install/custom/netboot/rh/rh72openpower4diskless1630b.cuda.otherpkgs
    permission=755
    pkgdir=/install/rhels7.2/ppc64le_patch,/install/rhel7220160512
    pkglist=/install/custom/netboot/rh/rh72diskless1625.rhels7.ppc64le.pkglist
    postbootscripts=mountEMS_install.sh,syncfilesfromEMS.sh,restorecap
    postinstall=/install/custom/netboot/rh/rh72diskless1620.ppc64le.postinstall
    postscripts=setupntp,local.tune
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels7.2/ppc64le_patch/rh72openpower4DL1632
```
```
 cat /tmp/ww.file |mkdef -z
Warning: The node name 'rh72openpower4DL1632' contains capital letters which may not be resolved correctly by the dns server.
1 object definitions have been created or modified.
```
The "Warning: The node name ...." confused user.

**Comment by daniceexi** [comment]
@bybai could you take a look of this issue?

**Comment by whowutwut** [comment]
@bybai    We hit something similar recently,.. wanted to share the data... 

If we create the following VMs
1) fs2VM121
2) fs2vm_122 

The uppercase one is OK, we print out that warning, but DNS seems to accept it and nslookup works.
```
# cat fs2VM121 | mkdef -z
Warning: The node name 'fs2VM121' contains capital letters which may not be resolved correctly by the dns server.
1 object definitions have been created or modified.
# makehosts fs2VM121
# makedns fs2VM121
Handling fs2VM121 in /etc/hosts.
...
# nslookup fs2VM121
Server:		10.3.31.100
Address:	10.3.31.100#53

Name:	fs2VM121.pok.stglabs.ibm.com
Address: 10.3.31.121
``` 

However, the underscore case does not work and we are not catching it... 
```
# cat 122 | mkdef -z 
1 object definitions have been created or modified.
# makehosts fs2vm_122
# makedns fs2vm_122
Ignoring line 10.3.31.122 fs2vm_122 fs2vm_122.pok.stglabs.ibm.com  in /etc/hosts, names  fs2vm_122 fs2vm_122.pok.stglabs.ibm.com  contain invalid characters (valid characters include a through z, numbers and the '-', but not '_'
Ignoring line 10.3.31.122 fs2vm_122 fs2vm_122.pok.stglabs.ibm.com  in /etc/hosts, names  fs2vm_122 fs2vm_122.pok.stglabs.ibm.com  contain invalid characters (valid characters include a through z, numbers and the '-', but not '_'
...

# nslookup fs2vm_122
Server:		10.3.31.100
Address:	10.3.31.100#53

** server can't find fs2vm_122: NXDOMAIN

```

So from that message, we should prevent the underscore from being used.   The makedns message that comes out contains a msg about  valid characters.   Uppercase is not listed... maybe the warning is OK  but we should probably handle the _ since it tells us that _ is not valid.  Thoughts?

**Comment by daniceexi** [comment]
@whowutwut We warn the capital character in the node name for makedns, because dns treats hostname as case-insensitive. So that means if you have two nodes which just have capital difference, it would cause problem.

And was you idea to restrict to use ``_`` in the ``mkdef`` command? It's possible that user defines a node which won't use **DNS**.

BTW, @wwzhubj opened this issue because the definition was for osimage. We should not make this capital check for **non-node** objects.

**Comment by whowutwut** [comment]
Oh ok. maybe we should just leave it as is and let the makedns error inform the user to change the node definition.

**Comment by bybai** [comment]
@daniceexi , we can use capital check for node; for osimage, xcat can use capital. I will fix this.

**Comment by immarvin** [comment]
hi @bybai , current xCAT does not restrict the usage of capital letters in osimage names.
[root@c910f04x30v02 initrd]# mkdef -t osimage -o AAA pkgdir=pp imagetype=linux
1 object definitions have been created or modified.

[root@c910f04x30v02 initrd]# lsdef -t osimage -o AAA
Object name: AAA
    imagetype=linux
    pkgdir=pp
