### ISSUE TITLE
[FVT]:use the same way to process the invalid archive and compress method for packimage

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#1706]
xCAT 2.12.2 
This is a low priority requirement. i found when use invalid archive and compress method. The code logic is different. If the return warning message is the same, that would be great!

```
[root@c910f02c01p13 ppc64]# packimage rhels7.2-ppc64-netboot-compute -m test
Packing contents of /install/netboot/rhels7.2/ppc64/compute/rootimg
archive method:test
compress method:gzip
Error: Invalid archive method 'test' requested

[root@c910f02c01p13 ppc64]# packimage rhels7.2-ppc64-netboot-compute -c test
Packing contents of /install/netboot/rhels7.2/ppc64/compute/rootimg
Error: Invalid compress method 'test' requested 
```

**Comment by whowutwut** [comment]
I think that we should error out right away instead of printing any messages if the options are invalid. Do not print the "packing contents of..." message. . do all the error checking up front and  print the error only instead of printing attempting to start the packing or compression.

This is kind is misleading in my opinion
