### ISSUE TITLE
By creating the documentation per tagged release, we have broken old links for xCAT docs

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1786]
In the 2.12.2 release, we tagged the release on GitHub. ReadTheDocs will detect it and we enabled that version of the documentation. 

The 2.12 release docs are ALL the same because we only have 2.12 branch in xCAT, so there's no need to have 2.12, 2.12.1, and 2.12.2 docs built on RTD

![image](https://cloud.githubusercontent.com/assets/10049070/18098181/1be4465e-6eaf-11e6-8a7e-b665029d9408.png)

However, by removing the 2.12 docs, we broke all the links for the release notes in the past for 2.12* releases.  

One possible solution here is to just undo the 2.12.2 and just enable 2.12 documentation

**Comment by whowutwut** [comment]
http://xcat-docs.readthedocs.io/en/2.12/index.html <-- this is a broken link, for example

**Comment by whowutwut** [comment]
For the meantime, since I need to provide links for the documentation, I re-enabled the 2.12 doc build.

**Comment by daniceexi** [comment]
@whowutwut 
I did not realize that. My thought was since we have doc change for each minor release so I'd like to make each release has corresponding doc version. For example, even after the release of 2.12.2, the xCAT 2.12.1 still has a doc of 2.12.1 in RTD which is different with the 2.12.2.

What do you think that we enable all the minor versions for a branch like 2.12, 2.12.1, 2.12.2?

**Comment by whowutwut** [comment]
@gurevichmark is looking at this. I think yesterday we decided it might just be better to link just to the documentation and not a specific build of the doc. If we enable each release we will have so many different versions and really that seems pointless since as always ask the customer to go to the latest mod release. And we will keep around the latest in the doc, 2.12.2 right now

**Comment by daniceexi** [comment]
So you meant all the 2.12.x release should use latest doc of the 2.12 branch. I am fine with that if you are fine with the following two facts 

* There are doc differences between releases
* We do have the RTC doc for each release

**Comment by gurevichmark** [comment]
To make release numbers more consistent, I have created a new release 2.12.0 and tagged it to the same commit number as 2.12_release. So now Read The Docs can display documentation for 2.12.2, 2.12.1, 2.12.0, etc. `stable` is still `2.12.2` and `latest` is still `master` as before. I also changed the release notes documentation links to point to the correct URL for that release.
There is one problem, however. Since I just created the 2.12.0 release 2.12.0, it is now marked as "Latest Release" in GitHub. @daniceexi and @whowutwut Do you think it is important that 2.12.0 is marked as "Latest Release" and not 2.12.2 as it was before ? One of the suggestions I found online is to remove 2.12.2 release and then create it again. Then the release creation date will be after the creation of 2.12.0 and 2.12.2 will be marked as "Latest Release".

**Comment by daniceexi** [comment]
Yes, we can remove the 2.12_release.

**Comment by whowutwut** [comment]
@gurevichmark  agreed. Can you also update the release process wiki so we are consistent with the tagging conventions

**Comment by gurevichmark** [comment]
Release `2.12_release` removed and "Release process" wiki page modified.

**Comment by samveen** [comment]
`README.rst` needs the update too, as it uses `2.12` for the docs badge and the doc URL instead of `2.12.0` . I've created #1847 for it.

**Comment by whowutwut** [comment]
@gurevichmark  One last thing, can you add a badge on the https://github.com/xcat2/xcat-core README.rst file to show the status of the 2.12.2 doc build?

**Comment by gurevichmark** [comment]
Done. Updated README.rst to include 2.12.2 badge

**Comment by whowutwut** [comment]
Thanks Mark
