### ISSUE TITLE
Documentation for postinstall scripts

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#1932]
Reported from Ralph:  he is documenting how to setup up xCAT installation and noticing there is no documentation for postinstall scripts. 
I looked around our readdoc, and find postscripts is defined in
"http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/references/man5/postscripts.5.html"
and postinstall scripts is defined in:
http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/references/man5/linuximage.5.html"

Ralph wanted to point out the difference between postscripts and postinstall scripts,  and like to put postinstall script description next to postscripts.

**Comment by gurevichmark** [comment]
The doc for osimage at http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/references/man7/osimage.7.html shows them next to each other.

**Comment by daniceexi** [comment]
We have three choices, an individual doc page, an individual man page, part of osimage man page. I preper the first one.

**Comment by whowutwut** [comment]
The prescripts and postscripts are described in a common section between diskful and diskless customizing osimages section in RTD.  However, since postinstall is something with diskless, there's no additional text describing it.  

http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/pre_post_script.html

Perhaps this is the right place to add the addition?

**Comment by immarvin** [comment]
hi @whowutwut , I agree what you that  the url you attached is the right place to add the ``postinstall`` section

**Comment by whowutwut** [comment]
@immarvin  if you are busy these sprints, perhaps we can find someone else to make the documentation addition?

**Comment by immarvin** [comment]
need to mention the problem on this ticket https://github.com/xcat2/xcat-core/issues/1856

**Comment by gurevichmark** [comment]
Documentation changed to add description of postinstall scripts in #2156
