### ISSUE TITLE
should genimage -n only install the specified drivers?

### ISSUE THREAD

**Issue by billwaj** [xcat2/xcat-core#1981]
running genimage -n will add the specified drivers but also adds a bunch of default drivers. These drivers are not needed on our compute nodes and we would like to remove them. So my question is: should genimage only install the specified drivers?

**Comment by immarvin** [comment]
hi @billwaj , "genimage -n" is to add additional drivers, there is no such option you mentioned. in fact, We rarely received any requirement like this before, since it's hard for user to figure out all the necessary drivers for a system. For Redhat, maybe you can try "modprobe.blacklist" kernel option to blacklist specific drivers.

see https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7-Beta/html/Installation_Guide/chap-anaconda-boot-options.html
````
modprobe.blacklist=
Blacklists (completely disables) one or more drivers. Drivers (mods) disabled using this option will be prevented from loading when the installation starts, and after the installation finishes, the installed system will keep these settings. The blacklisted drivers can then be found in the /etc/modprobe.d/ directory.
Use a comma-separated list to disable multiple drivers. For example:
modprobe.blacklist=ahci,firewire_ohci
````

**Comment by immarvin** [comment]
no response, close this ticket first, please reopen it if you need
