### ISSUE TITLE
Statelless image: lsf_startup starts with wrong memlock settings

### ISSUE THREAD

**Issue by LudovicEnault** [xcat2/xcat-core#2003]
Hello!

I have build a stateless image with RHELS7.2
When the system boots, it runs syncfiles (which includes a update version for /etc/security/limits.conf), then it runs lsf_startup.

If a user launchs a "ulimit -l" jobs, it will return "64" whereas "unlimited" is set in the file. Just restarting LSF daemons solves the issue because the bash environment has the "unlimited" value.

So the system is configured properly, but when the server boots, it seems to spawn all processes with the default limits. which is not what I would expect.
Is there anything to do to change that beahvior ?

Here is the list of postscripts defined for my node:
postscripts=syslog,remoteshell,syncfiles,setupntp,confignics -s,lsf_startup

Best Regards

**Comment by daniceexi** [comment]
It's possible to leverage postinstall script to customise the /etc/security/limits.conf when perform genimage.
ThanksBest Regards----------------------------------------------------------------------Wang Xiaopeng (王晓朋)IBM China System Technology LaboratoryTel: 86-10-82453455Email: wxp@cn.ibm.comAddress: 28,ZhongGuanCun Software Park,No.8 Dong Bei Wang West Road, Haidian District Beijing P.R.China 100193
 
 
----- Original message -----From: LudovicEnault <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc:Subject: [xcat2/xcat-core] Statelless image: lsf_startup starts with wrong memlock settings (#2003)Date: Thu, Oct 20, 2016 8:52 PM 
Hello!
I have build a stateless image with RHELS7.2When the system boots, it runs syncfiles (which includes a update version for /etc/security/limits.conf), then it runs lsf_startup.
If a user launchs a "ulimit -l" jobs, it will return "64" whereas "unlimited" is set in the file. Just restarting LSF daemons solves the issue because the bash environment has the "unlimited" value.
So the system is configured properly, but when the server boots, it seems to spawn all processes with the default limits. which is not what I would expect.Is there anything to do to change that beahvior ?
Here is the list of postscripts defined for my node:postscripts=syslog,remoteshell,syncfiles,setupntp,confignics -s,lsf_startup
Best Regards

**Comment by LudovicEnault** [comment]
After some discussions:
For diskless system, xCAT puts a master script in /etc/init.d that is executed when the it boots. the scripts spawns the script in order. Each script inherits the environment from the master script. In the present case, the /etc/security/limits.conf is copied successfully, then lsf_startup is called without taking into account the latest changes
To avoid this issue, people can perform file copy leveraging a postinstall script in the image definition, so it's copied in the image, or update the lsf_startup script with "ulimit -l unlimited".
Best Regards,
Ludo
