### ISSUE TITLE
[fvt]2.12.4 xcatprobe discovery -r will exit if only one node's precheck failed and other node success for discovery

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#2116]
env:fs4
build:[root@fs4 ~]# lsxcatd -v
Version 2.12.4 (git commit d57001530b6d58a3ee0e52ede1f794e065da135f, built Mon Nov  7 22:37:04 EST 2016)
[root@fs4 ~]# 
How to reproduce:
```
[root@fs4 ~]# xcatprobe discovery -n frame23cn18 -m mtms -r 4h
All pre_defined nodes are valid                                                                                   [ OK ]
Attribute 'master' in 'site' table is configured                                                                  [ OK ]
DHCP dynamic range is configured                                                                                  [ OK ]
Genesis files are avaliable                                                                                       [ OK ]
Starting to scan logs which are later than 'Tue Nov  8 20:19:57 2016', please waiting for a while.............    
==================discovery_probe_report=================
All nodes matched successfully                                                                                    [ OK ]
[root@fs4 ~]# xcatprobe discovery -n wjx -m mtms -r 4h
[frame23cn17,frame23cn177] : Duplicate node definition found for the same mtms 8335-GTB*100470A.                  [FAIL]
[root@fs4 ~]# lsdef wjx
Object name: frame23cn17
    arch=ppc64
    bmc=50.23.17.1
    cpucount=128
    cputype=POWER8NVL (raw), altivec supported
    disksize=sda:1000GB,sdb:1000GB
    groups=wjx,disco1
    initrd=xcat/genesis.fs.ppc64.gz
    ip=192.168.23.15
    kcmdline=quiet xcatd=192.168.3.25:3001 destiny=shell
    kernel=xcat/genesis.kernel.ppc64
....
Object name: frame23cn177
    arch=ppc64
    bmc=50.23.17.1
    groups=wjx,disco1
    ip=192.168.23.157
    mgt=ipmi
    mtm=8335-GTB
    ----------------------> In fact one node's discovery success and one node fail ,but replay will exit if failed node's precheck fail.

```

**Comment by hu-weihua** [comment]
@junxiawang， ``discovery probe`` has 2 independent stages,  ``pre-check for configuration`` and ``probe discovery running process``.  Every error happened during ``pre-check for configuration``  stage will result in  this stage stop .   Because if the configuration isn't reliable, the rest check is meaningless. I think it make sense .

Yes, Maybe in your case, node definition error just one little thing, we can move probe forward. Actually just from code implementation point of view, every thing could do. But in ``pre-check for configuration``  stage we don't only check node definition, but check many other things else at same time.  If we do some specific thing for this little scenario, do some specific thing for that little scenario,  it will result in code very complicated，it's hard to maintain and redevelop in future.  After balancing effort and benefit,  we think we don't obtain obvious benefit from it. 

So thanks for your comment, but it is a pity that we won't modify code for this. Now the output of ``discovery`` maybe not perfect for this case, but it's correct at least.

**Comment by whowutwut** [comment]
@hu-weihua  I think if we identify an issue as invalid, we should just close it.  If the originator does not agree, they can always comment and re-open.  I'll let you close this one.
