### ISSUE TITLE
[FVT]:setupntp is failed in postscripts nfs based statelite CN 

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#2232]
xCAT 2.13  rhels7.3 

Steps to reproduce
1. install xCAT 2.13
```
[root@c910f03fsp03v02 result]# lsxcatd -v
Version 2.13 (git commit f7ec4dde7f97f8f588413a186a17f5426cc88314, built Tue Nov 29 08:50:45 EST 2016)
```
2. Define cn 
3. copycds to get the default statelite osimage
```
[root@c910f03fsp03v02 result]# lsdef -t osimage -o rhels7.3-ppc64le-statelite-compute
Object name: rhels7.3-ppc64le-statelite-compute
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.exlist
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.3-ppc64le
    osname=Linux
    osvers=rhels7.3
    otherpkgdir=/install/post/otherpkgs/rhels7.3/ppc64le
    pkgdir=/install/rhels7.3/ppc64le
    pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.postinstall
    profile=compute
    provmethod=statelite
    rootimgdir=/install/netboot/rhels7.3/ppc64le/compute
    synclists=/install/custom/netboot/rh/compute.synclist
```
4. define litefile
```
[root@c910f03fsp03v02 result]# tabdump litefile
#image,file,options,comments,disable
"ALL","/etc/adjtime","tmpfs",,
"ALL","/etc/inittab","tmpfs",,
"ALL","/etc/lvm/","tmpfs",,
"ALL","/etc/ntp.conf","tmpfs",,
"ALL","/etc/ntp.conf.predhclient","tmpfs",,
"ALL","/etc/resolv.conf","tmpfs",,
"ALL","/etc/resolv.conf.predhclient","tmpfs",,
"ALL","/etc/rsyslog.conf","tmpfs",,
"ALL","/etc/rsyslog.conf.XCATORIG","tmpfs",,
"ALL","/etc/securetty","tmpfs",,
"ALL","/etc/ssh/","tmpfs",,
"ALL","/etc/sysconfig/","tmpfs",,
"ALL","/etc/udev/","tmpfs",,
"ALL","/etc/yp.conf","tmpfs",,
"ALL","/opt/xcat/","tmpfs",,
"ALL","/root/.ssh/","tmpfs",,
"ALL","/tmp/","tmpfs",,
"ALL","/var/","tmpfs",,
"ALL","/xcatpost/","tmpfs",,
```
5. nodeset osimage to cn and boot up cn. After cn booted up. the status is failed but not booted
```
[root@c910f03fsp03v02 result]# lsdef -l c910f03fsp03v04 |grep -i status
    status=failed
    statustime=11-30-2016 01:20:51
```
6.

**Comment by bybai** [comment]
Hi @tingtli ,
The status failed is caused by setupntp:
1, login compute node:
[root@c910f03fsp03v04 xcat]# vi xcat.log
xcatdsklspost: updating VPD database
xcatdsklspost: failed to download mypostscript.<nodename>, trying to call getpostscript.awk...
Wed Nov 30 09:57:31 UTC 2016 Running postbootscript: syslog
sed: couldn't open temporary file /etc/sed8Z0Nhs: Read-only file system
Wed Nov 30 09:57:31 UTC 2016 postbootscript syslog return with 0
Wed Nov 30 09:57:31 UTC 2016 Running postbootscript: remoteshell

Wed Nov 30 09:57:34 UTC 2016 postbootscript remoteshell return with 0
Wed Nov 30 09:57:34 UTC 2016 Running postbootscript: syncfiles
Wed Nov 30 09:58:56 UTC 2016 postbootscript syncfiles return with 0
Wed Nov 30 09:58:56 UTC 2016 Running postbootscript: setupntp
cp: cannot create regular file '/etc/ntp.conf.org': File exists
inactive
30 Nov 10:17:07 ntpdate[1782]: step time server 10.3.9.2 offset 1076.073028 sec
Failed to execute operation: Read-only file system
Wed Nov 30 10:17:08 UTC 2016 postbootscript setupntp return with 1
Wed Nov 30 10:17:08 UTC 2016 Running postbootscript: otherpkgs
  Did not install any extra packages.
Wed Nov 30 10:17:08 UTC 2016 postbootscript otherpkgs return with 0
node boot failed,reporting status...

2, from MN:
[root@c910f03fsp03v02 ~]# lsdef c910f03fsp03v04 -i postscripts
Object name: c910f03fsp03v04
    postscripts=syslog,remoteshell,syncfiles,setupntp

3,  After I remove setupntp, the status is booted.  
4, The persistent directory work well in CN:
c910f03fsp03v02:/nodedata/c910f03fsp03v04.pok.stglabs.ibm.com        36G   11G   25G  31% /.statelite/persistent
rw                                                                  2.0G   64K  2.0G   1% /.sllocal/log
c910f03fsp03v02:/nodedata/c910f03fsp03v04.pok.stglabs.ibm.com/test   36G   11G   25G  31% /test

**Comment by tingtli** [comment]
This is also failed on diskless node. Here is some logs
```
Thu Dec  1 01:02:36 EST 2016 Running postbootscript: setupntp
inactive
/usr/sbin/rcntpd ntptimeset
/usr/sbin/rcntpd ntptimeset failed, NTP maynot be synchronized, please wait for NTP synchronized then run updatenode nodename -P setupntp
Thu Dec  1 01:02:37 EST 2016 postbootscript setupntp return with 1
```

**Comment by tingtli** [comment]
@cxhong  Would you please take a look at this defect. Thanks!

**Comment by cxhong** [comment]
I created a statelite compute node.  I think there is permission issue for the statelite os image.
how can we explain this?
````
# ls -ltr /etc/ntp.conf.orig
ls: cannot access /etc/ntp.conf.orig: No such file or directory
# /usr/bin/cp /etc/ntp.conf /etc/ntp.conf.orig
/usr/bin/cp: cannot create regular file ‘/etc/ntp.conf.orig’: File exists
```````
I have no issue to start/stop ntpd service, but couldn't enable it.
````
# systemctl enable ntpd
Failed to execute operation: Read-only file system
# systemctl enable ntpd.service
Failed to execute operation: Read-only file system
````````

@tingtli , for diskless node, did u run on sles?  it works for redhat.

**Comment by tingtli** [comment]
@cxhong  I am sorry. I should mark the os for the diskless. I think this only occurs on sles12.1 
When the diskless node boots up. i can see ntp service is not started. And there is some hints in the message.
```
c910f03c17k24:/var/log/xcat # service ntpd status
ntpd.service - NTP Server Daemon
   Loaded: loaded (/usr/lib/systemd/system/ntpd.service; disabled)
   Active: inactive (dead)
     Docs: man:ntpd(1)

Fri Dec  2 01:11:21 EST 2016 Running postbootscript: setupntp
inactive
/usr/sbin/rcntpd ntptimeset
/usr/sbin/rcntpd ntptimeset failed, NTP maynot be synchronized, please wait for NTP synchronized then run updatenode nodename -P setupntp
Fri Dec  2 01:11:22 EST 2016 postbootscript setupntp return with 1
```

**Comment by bybai** [comment]
Hi @cxhong ,
After I added 2 lines into litefile, setupntp can be successful.
"ALL","/etc/systemd/system/multi-user.target.wants/","tmpfs",,
"ALL","/usr/lib/systemd/system/ntpd.service","tmpfs",,

After statelite node is booted, the log in CN /var/log/xcat/xcat.log

+ '[' -z 'systemctl enable  ntpd' ']'
+ eval systemctl enable ntpd
++ systemctl enable ntpd
Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
+ exit 0
Fri Dec  2 07:51:38 UTC 2016 postbootscript setupntp return with 0

**Comment by tingtli** [comment]
@cxhong @bybai  I will leave this bug to trace ntp issue on statelite but  open a new bug #2248
to trace the issue on sles12.1 stateless.

**Comment by junxiawang** [comment]
I have verified the bug

**Comment by immarvin** [comment]
hi @junxiawang @bybai , 

``"ALL","/usr/lib/systemd/system/ntpd.service","tmpfs",,`` is not mandatory

**Comment by tingtli** [comment]
I think although this is fixed on rhels, we need to verify this on sles . Move to next release.

**Comment by bybai** [comment]
litefile
redhat6 needs:
    "ALL","/etc/rc3.d/","tmpfs",,
    "ALL","/etc/rc2.d/","tmpfs",,
    "ALL","/etc/rc4.d/","tmpfs",,
    "ALL","/etc/rc5.d/","tmpfs",,

sles11 needs:
"ALL","/etc/init.d/rc3.d/","tmpfs",,
"ALL","/etc/init.d/rc5.d/","tmpfs",,

**Comment by bybai** [comment]
In sles12.1:
chdef -t site extntpservers=9.114.120.1
makentp -a

the setupntp can work well, so do not need to update litefile for sles12.1

**Comment by tingtli** [comment]
It is verified by autotest. Close it.
