### ISSUE TITLE
rmdef takes a very long time to remove objects in xCAT DB when the DB is populated, nodeset offline is cause

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2508]
Creating some dummy entries into xCAT, created 1000 node definitions very quickly...

```
[root@fs1 research92]# time mkdef c460c[0001-1000] groups=regEX_CORAL
1000 object definitions have been created or modified.

real	0m2.506s
user	0m0.256s
sys	0m0.005s
```

Removing it was another story.   I tried to first use a wildcard noderange, and  I thought xCAT hung and killed it.... 
```
root        616 142804  0 11:48 ?        00:00:00  \_ sshd: root@pts/5
root        626    616  0 11:48 pts/5    00:00:00  |   \_ -bash
root       2913    626  0 12:00 pts/5    00:00:00  |       \_ /usr/bin/perl /opt/xcat/bin/rmdef /c460c.*

[root@fs1 research92]# time rmdef /c460c.*
Killed

real	53m27.144s
user	0m0.385s
sys	0m0.021s

```

I think after the investigation, it's probably just that it was going to take a very long time to remove the definitions.    DB is Postgres 

Here's some investigation data....  

```
[root@fs1 ~]# time rmdef c460c[0001-0010]
10 object definitions have been removed.

real	0m54.834s
user	0m0.256s
sys	0m0.015s

[root@fs1 ~]# time rmdef c460c[0011-0030]
20 object definitions have been removed.

real	1m48.741s
user	0m0.267s
sys	0m0.005s
```

Removing blocks of 100 (surprising after the first 100 was removed, the time actually increased...

```
[root@fs1 ~]# time rmdef c460c[0061-0160]
100 object definitions have been removed.

real	20m38.523s
user	0m0.313s
sys	0m0.014s
[root@fs1 ~]# time rmdef c460c[0161-0260]
100 object definitions have been removed.

real	34m36.380s
user	0m0.349s
sys	0m0.037s
[root@fs1 ~]# time rmdef c460c[0261-0360]
100 object definitions have been removed.

real	34m34.777s
user	0m0.374s
sys	0m0.005s
```

The good thing here is that ``noderm`` works a lot faster but it has an entry being printed out for each node removed. (Should consider making the output less verbose..) 

```
[root@fs1 ~]# time mkdef c460c[0001-1000] groups="regEX_CORAL"
1000 object definitions have been created or modified.

real	0m2.508s
user	0m0.247s
sys	0m0.015s
[root@fs1 ~]# time noderm c460c[0001-1000] >> /dev/null 

real	0m24.958s
user	0m0.159s
sys	0m0.013s

```

**Comment by gurevichmark** [comment]
So most likely `rmdef` takes longer because it issues `nodeset offline` as implemented for #1524.

@whowutwut @chenglch @zet809 @daniceexi What do you guys think ? Should we not do `nodeset offline` when user issues `rmdef`. The problem then, is that there could be lots of `/tftpboot` config files left over on MN and no easy way to clean them up.

**Comment by whowutwut** [comment]
Yes, looks like this is the reasons.  

I did a quick verification test by commenting out the code a section of code in `DBobjectdefs.pm` around line 4261. 

```
[root@fs3 xcat]# time  mkdef c460c[0001-1000] groups=regEX_CORAL
1000 object definitions have been created or modified.

real	0m3.199s
user	0m0.259s
sys	0m0.006s

[root@fs3 xcat]# time  rmdef /c460c.*
1000 object definitions have been removed.

real	0m8.538s
user	0m0.239s
sys	0m0.026s
```

The original purpose of this change was to really help the user clean up pieces that xCAT touches while the node definition still exists and we have the knwledge/ability to do so.... but this drastically affects the performance of the `rmdef` command.  

My opinion is that we should leave the code to perform at it's best by default... and the user should specify the option if they want us to operate in another manor.  Perhaps even an environment variable can be set so that the command issued is the same.  OR... we provide a utility that will attempt to help clean up the system outside of xCAT commands.  A similar problem to this is when we do `makeconservercf node-<mt>-<sn>` and once we discover the node, we automatically remove the temporary node definition which then we can't easily remove the console config for that node.

**Comment by daniceexi** [comment]
Yes, looks like we prefer to make this behaviour to be default. Then adding an option to disable the offline action sounds good. So that large cluster customer can use it when they are concerning the performance of rmdef. But be sure that the description for this option is understandable for customer to know what happens inside otherwise they would have worry to use it.
ThanksBest Regards----------------------------------------------------------------------Wang Xiaopeng (王晓朋)IBM China System Technology LaboratoryTel: 86-10-82453455Email: wxp@cn.ibm.comAddress: 28,ZhongGuanCun Software Park,No.8 Dong Bei Wang West Road, Haidian District Beijing P.R.China 100193
 
 
----- Original message -----From: Victor Hu <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc: Xiao Peng Wang/China/IBM@IBMCN, Mention <mention@noreply.github.com>Subject: Re: [xcat2/xcat-core] rmdef takes a very long time to remove objects in xCAT DB when the DB is populated (#2508)Date: Fri, Feb 24, 2017 2:39 AM 
Yes, looks like this is the reasons.
I did a quick verification test by commenting out the code a section of code in DBobjectdefs.pm around line 4261.
[root@fs3 xcat]# time  mkdef c460c[0001-1000] groups=regEX_CORAL1000 object definitions have been created or modified.real 0m3.199suser 0m0.259ssys 0m0.006s[root@fs3 xcat]# time  rmdef /c460c.*1000 object definitions have been removed.real 0m8.538suser 0m0.239ssys 0m0.026s
The original purpose of this change was to really help the user clean up pieces that xCAT touches while the node definition still exists and we have the knwledge/ability to do so.... but this drastically affects the performance of the rmdef command.
My opinion is that we should leave the code to perform at it's best by default... and the user should specify the option if they want us to operate in another manor. Perhaps even an environment variable can be set so that the command issued is the same. OR... we provide a utility that will attempt to help clean up the system outside of xCAT commands. A similar problem to this is when we do makeconservercf node-<mt>-<sn> and once we discover the node, we automatically remove the temporary node definition which then we can't easily remove the console config for that node.

**Comment by zet809** [comment]
@daniceexi I think it is a good idea that add an option for rmdef to disable the running of nodeset. It can be added in the sprint plan of next sprint.

**Comment by whowutwut** [comment]
@daniceexi @zet809  Discussed with @gurevichmark , I think there's a few things we need to look at and I think we should have separate pull requests for each.    I actually would prefer preserving the speed of the command by default and have users export a environment variable to do the `nodeset offline`.    

Here's what I think we need...
1) High Priority,  implement an option to allow this to be bypassed to resolve our current situation, OR revert back the old code and add an option to properly clean up the node, at the expense of performance... 

2)  Then can we expand out the noderange? If we know that the action is being run against 20+ nodes, we should print a message saying...  "this command takes a long time, do blah blah to speed it up..." 

3) Need to look at the code for nodeset offline, and make sure we are processing the correct things in the right order...  like make all the changes then run `makedns` once or `makedhcp -d` once at the end...  instead of looping.  Again, i haven't seen the code but we should take a look at that...  this could affect what we plan to do in the above...

**Comment by daniceexi** [comment]
@whowutwut All we want to do is to have the flexibility to control the enable/disable **offline** action when executing the ``rmdef``. We may enhance ``rmdef`` to make it prompt user to choose whether to run **offline**, in the prompt message we could tell user the benefit to run the **offline**. This can resolve all the issues we are struggling.

Of course that we need to add a **-y** to skip this prompt for script to call.

**Comment by whowutwut** [comment]
Yea we also thought about this as well but it will impact those who may be running this inside a script if we introduce interactive prompts

**Comment by daniceexi** [comment]
maybe we could make this prompt just waiting 10s, if no input in 10s, we just continue by default.

**Comment by whowutwut** [comment]
Interesting thought... 

I think also on my test system, all the data is faked and so perhaps `makedns -d` and `makedhcp -d` actually take longer to time out than on real systems because there's no mac addresses or hostnames ...   So maybe the impact is not quite as bad as 5 seconds / node on a real system.. should get some actual data.. 

But I think if the user is unaware of this time, the most likely action would be to `ctrl-c` out of this because they would think the command is hung.  Do we leave a bad state if we interrupt this process? Maybe some status message to inform the user that nodes are actually getting deleted...  .. Every 100 nodes, print a message... ?   Now the scope is just getting large..   I'm okay staging in changes.  will discuss with Mark.

**Comment by gurevichmark** [comment]
@whowutwut @daniceexi @zet809 @chenglch 
What if we do this:
1. Put default `rmdef` code back as it was before - runs faster but does not remove the config files.
2. Add a new options `-c|--cleanup`. With this option we will call `nodeset offline` AND if more than 100 nodes in the noderange, it will display a message to the user: `Performing configuration cleanup. This might take a few minutes`. No blocking or waiting for user input.

**Comment by zet809** [comment]
@gurevichmark Sounds great to me, thx Mark.

**Comment by whowutwut** [comment]
Verifying on build: `Version 2.13.3 (git commit 7bd281016189ca71a1e7c8e93774c077477330b0, built Mon Mar 20 06:15:41 EDT 2017)`

This is a VM so performance is slightly worse than bare metal...

```
[root@fs2vm105 coral]# time mkdef c460c[0001-1000] groups=REGEX_CORAL
1000 object definitions have been created or modified.

real    0m4.141s
user    0m0.402s
sys     0m0.060s
```

And removing...

```
[root@fs2vm105 coral]# time rmdef /c460c.*
1000 object definitions have been removed.

real    0m10.873s
user    0m0.442s
sys     0m0.018s
```

So the default behavior is restored.  Thanks @gurevichmark !
