### ISSUE TITLE
[DEV] convert /etc/init.d/xcatd from sysVinit service unit to systemd service unit

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#2586]
currently, we depended on the backward compatibility of  systemd to manipulate the xcatd service, this caused some problem like https://github.com/xcat2/xcat-core/issues/2322

**Comment by immarvin** [comment]
since this feature might influence the management of xcatd service, should better assigned to some expert on linux administration @neo954 @robin2008

**Comment by whowutwut** [comment]
:+1:  I think this is something that has to be done.. thanks for opening this issue.

**Comment by immarvin** [comment]
hi @whowutwut , seems the xcat postscript service in systemd has been finished in this PR https://github.com/xcat2/xcat-core/pull/2055

**Comment by samveen** [comment]
@immarvin Victor is talking about converting the  xCAT-server init script `/etc/init.d/xcatd` to a proper systemd unit file, instead of depending on systemd's legacy support for init.d scripts.

**Comment by samveen** [comment]
@immarvin #2055 just creates a unit file for xCAT `compute` nodes, not the xCAT `master`/`service` nodes.

**Comment by immarvin** [comment]
hi @samveen , yes, the systemd unit of service on compute nodes to run PS and report node status has been finished. this issue is on the systemd service unit for xcatd itself

**Comment by robin2008** [comment]
Main sub-tasks for this feature:
1, Build the service type unit file for xcatd.service to control xcatd daemon via systemd
2,Handle the systemd unit in install/uninstall/upgrade case for xCAT packages
3,Check if any codes or sample codes in xcat which is using legacy SysV init method via hard coding, and correct them if possible. (Note:  this is an interface change to external user and component)
4,Update document to cover the changes  

Assumption:
Both MN and SN should be covered
It should work on all OS which systemd is enabled by default.

**Comment by robin2008** [comment]
In /etc/init.d/xcatd,  there are 4 action supported: status, start, stop, restart, reload.
To keep the compatible, we need to support them all in systemd service unit file.

If installed systemd unit file,  it is greatly recommended to use "systemctl" to control the service.
But "service xcatd <operation>" is still working as it will redirected to systemctl. 

However the output of systemd is totally different with SysV init, it requires that the usage of xcatd should be refined if any usage rely on the program output. 

#For example:

systemctl status xcatd
xcatd.service - xCAT management service
   Loaded: loaded (/usr/lib/systemd/system/xcatd.service; enabled)
   Active: active (running) since Mon 2017-03-06 20:46:34 CST; 9min ago
  Process: 2342 ExecStart=/opt/xcat/sbin/xcatd -p /var/run/xcatd.pid (code=exited, status=0/SUCCESS)
 Main PID: 2422 (xcatd: SSL list)
   CGroup: /system.slice/xcatd.service
           ├─ 2421 /usr/sbin/in.tftpd -v -l -s /tftpboot -m /etc/tftpmapfile4xcat.conf
           ├─ 2422 xcatd: SSL listener
           ├─ 2423 xcatd: DB Access
           ├─ 2425 xcatd: UDP listener
           ├─ 2426 xcatd: install monitor
           ├─ 2427 xcatd: Discovery worker
           ├─ 2428 xcatd: Command log writer
           ├─46083 xcatd SSL: pcmdimmtemp to __Managed,__mgmtnode for root@localhost
           └─46096 xcatd SSL: pcmsystemstate to __HardwareProfile_IBM_System_p_CEC for root@localhost

Mar 06 20:55:32 xcatmn xcat[46089]: xCAT: Allowing getAllEntries for root from localhost
Mar 06 20:55:32 xcatmn xcat[46091]: xCAT: Allowing getAllEntries for root from localhost
Mar 06 20:55:32 xcatmn xcat[46092]: xCAT: Allowing getAllEntries for root from localhost
Mar 06 20:55:32 xcatmn xcat[46095]: xCAT: Allowing getAllEntries for root from localhost
Mar 06 20:55:36 xcatmn xcat[2427]: xcatd: Processing discovery request from 172.20.7.202
Mar 06 20:55:36 xcatmn xcat[2427]: xcat.discovery.aaadiscovery: (00:1a:a0:0d:5b:4a) Got a discovery request, attempting to discover the node...
Mar 06 20:55:36 xcatmn xcat[2427]: xcat.discovery.blade: (00:1a:a0:0d:5b:4a) Warning: Could not find any nodes using blade-based discovery
Mar 06 20:55:36 xcatmn xcat[2427]: xcat.discovery.switch: (00:1a:a0:0d:5b:4a) Warning: Could not find any nodes using switch-based discovery
Mar 06 20:55:36 xcatmn xcat[2427]: xcat.discovery.mtms: (00:1a:a0:0d:5b:4a) Warning: Could not find any node for *C2BL42X using mtms-based discovery
Mar 06 20:55:36 xcatmn xcat[2427]: xcat.discovery.zzzdiscovery: (00:1a:a0:0d:5b:4a) Failed to discover the node.

/etc/init.d/xcatd.bak status
xcatd service is running

**Comment by billwaj** [comment]
It seems that systemd uses lower values than the values displayed in ulimit -a.  One value in particular that we saw for xcatd on a large P775 cluster was for open filedescriptors which caused actions to not be performed against nodes.  Adding the line "LimitNOFILE=16000" in xcatd.service fixed the problem. Can this be added to the xCAT-server shipped xcatd.service file?  Also, what is the target milestone for this function?

**Comment by whowutwut** [comment]
Any response to @billwaj  ? ^

**Comment by robin2008** [comment]
@billwaj Yes, we can add the parameters into xCAT-server shipped xcatd.service file, and the target milestone is 2.14

**Comment by robin2008** [comment]
2.14 is the target GA for CORAL,  not involve new feature there.
Move it to next.

**Comment by whowutwut** [comment]
If we look at `chkconfig --list` on RHEL 7.5, there are very few services using sysVinit

xCAT product is 40% of this list... 

```
conserver      	0:off	1:off	2:on	3:on	4:on	5:on	6:off
netconsole     	0:off	1:off	2:off	3:off	4:off	5:off	6:off
network        	0:off	1:off	2:on	3:on	4:on	5:on	6:off
rhnsd          	0:off	1:off	2:on	3:on	4:on	5:on	6:off
xcatd          	0:off	1:off	2:off	3:on	4:on	5:on	6:off
```
