### ISSUE TITLE
ENV OPENBMC_DEVEL doesn't work on openbmc plugin

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#2649]
while I am testing rcons for openbmc , found environment variable OPENBMC_DEVEL didn't work.
````
[root@fs1 ~]# export OPENBMC_DEVEL=NO
[root@fs1 ~]# rpower opennode1 stat
Error: This function is currently not supported
[root@fs1 ~]# export OPENBMC_DEVEL=YES
[root@fs1 ~]# echo $OPENBMC_DEVEL
YES
[root@fs1 ~]# rpower opennode1 stat
Error: This function is currently not supported
````
**$ENV{'OPENBMC_DEVEL'}** seems empty, didn't take any value from export.  does plugin routine works differently for env variable?

**Comment by xuweibj** [comment]
Hi @cxhong, after modified ``OPENBMC_DEVEL`` value, did you restart xcatd?

**Comment by cxhong** [comment]
Here is output:
````
[root@fs1 ~]# echo $OPENBMC_DEVEL
YES
[root@fs1 ~]# service xcatd restart
Restarting xcatd (via systemctl):                          [  OK  ]
[root@fs1 ~]# rpower opennode1 stat
Error: This function is currently not supported
````

**Comment by xuweibj** [comment]
Could you use ``restartxcatd`` to have a try?

**Comment by cxhong** [comment]
this command works better
````
[root@fs1 xCAT_plugin]# echo $OPENBMC_DEVEL
YES
[root@fs1 xCAT_plugin]# restartxcatd
restartxcatd invoked by root.

Restarting xCATd                                           [  OK  ]
[root@fs1 xCAT_plugin]# rpower opennode1 stat
Warning: Currently running development code, use at your own risk

opennode1: xyz.openbmc_project.State.Host.HostState.Running
``````

so what's different between ````service xcatd restart```` and ````restartxcatd````?

**Comment by xuweibj** [comment]
Hi @cxhong , we found that my method of export ``OPENBMC_DEVEL`` maybe not right.
If add ``export OPENBMC_DEVEL=YES`` in /etc/profile.d/xcat.sh, command ``service xcatd restart`` will work well too. 
When use ``restartxcatd``, it will load all environment variables in the terminal.
But use ``service xcatd restart``, the ``service`` will only reload value from ``xcat.sh`` and ``xcat.csh``. This is defined by xcat.

**Comment by whowutwut** [comment]
@xuweibj  Is there no way to pick up a variable in the shell?  This seems like it makes it more difficult to just turn on and off function "on demand" if it requires another step.  If there's really no way, then we should change the message to: 
```
This function is currently not supported.  
To enable development code, run the following commands:

    export OPENBMC_DEVEL=yes
    restartxcatd
```

**Comment by immarvin** [comment]
hi @xuweibj , has this issue been fixed? if yes, please paste the link of the PR in the comment and set label "pending" after the PR is merged

**Comment by xuweibj** [comment]
Hi @cxhong , depending on my comment above, do you have more requirements about this issue? Or could you close it?

**Comment by whowutwut** [comment]
@zet809 @daniceexi @xuweibj Just trying to confirm that there's no way pick up the variable on the fly, the xcatd must be restarted?   This leads to some strange behavior with the combination of XCATBYPASS.  

For example, if the OPENBMC_DEVEL is already set, and xcatd is using it, it allows us to run the commands
```
[root@fs2vm105 opt]# rpower openbmc[2] stat
Warning: Currently running development code, use at your own risk.  Unset OPENBMC_DEVEL and `restartxcatd` to disable.
openbmc2: xyz.openbmc_project.State.Host.HostState.Off
```

Once we export XCATBYPASS, it bypasses the daemon, and so it's not exported so it doesn't pick up. 
```
[root@fs2vm105 opt]# export XCATBYPASS=1
[root@fs2vm105 opt]# rpower openbmc[2] stat
Error: This openbmc related function is unsupported and disabled. To bypass, run the following: 
    export OPENBMC_DEVEL=YES
    restartxcatd
[root@fs2vm105 opt]# 
```

It's also strange because this means that I can log into another shell and OPENBMC_DEVEL is always set, or some other user can set it and it affects the entire running cluster. Yes, this is a temporary thing, but we may need to use this type of control in the future and it would be good to understand whether we can have better control or not...

**Comment by zet809** [comment]
Do you think create a flag file is good idea? And if our code, check whether a specified file is exist?
For example, if we'd like to enable the OPENBMC_DEVEL, we can touch a file /opt/xcat/OPENBMC_DEVEL. then within openbmc.pm, it can check the /opt/xcat/OPENBMC_DEVEL file is there and enable the corresponding interfaces.

**Comment by robin2008** [comment]
It cannot set environment variable in terminal for a service,  it is not a linux method. As service is running in backend,  you cannot bind a specific terminal to it.

Normally,  if you want to do some configuration change for a daemon,  you need to send a signal or modify a configuration file (or site), and you daemon handle such changes.

**Comment by xuweibj** [comment]
There is a better method to set and get environment value.

1. ``export XCAT_OPENBMC_DEVEL=xxxxx`` in terminal
2. In code, get value by ``$request->{environment}->[0]->{XCAT_OPENBMC_DEVEL}->[0]`` in preprocess_request function

This way is not needed to restart xcatd.
But for ``XCATBYPASS=1``, we need to use ``$request->{environment}->{XCAT_OPENBMC_DEVEL}`` to get value.

Shall we change code depending on this method?

**Comment by whowutwut** [comment]
Well this is suppsoe to be a temp variable as we develop the openbmc code so we should not get too crazy. But may be used again in other features in the future...

**Comment by zet809** [comment]
So, we can use the method @xuweibj mentioned for the openbmc supporting, right? We can describe how to enable it in the manpage of rpower.

**Comment by whowutwut** [comment]
@zet809  No, there's no point in documenting it.  I think we are still not understanding the purpose for the block.... This is a temporary disablement so that we can develop and commit the code into the product, but it's "disabled" to the end user.  If they enable it , it's at their own risk.  

The location where @xuweibj added the `unsupported()` call is not correct, but I didn't make a big deal when doing the review because we are so early in the development cycle.  We should be calling the unsupported in each of the sub functions that are handled in ipmi.pm. 

For example, if the only function has been tested and opened is rpower and rinv..... then it would look like this:

```
sub rpower() {
    code here is tested and open
} 

sub rflash() {
    # code here is blocked
    unsupported()
}

sub rinv() {
    # code here is tested and open
} 

sub reventlog() {
   #code here is blocked 
    unsupported()
}

etc etc
```

But with this environment, FVT and development can open up all the code path and do testing on the code without affecting normal users ....
