### ISSUE TITLE
Noderange format error

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#2707]
Objects:

```
# lsdef
a01n01  (node)
a01n02  (node)
a01n03  (node)
a01n04  (node)
a01n05  (node)
a01n06  (node)
a01n07  (node)
a01n08  (node)
a01n09  (node)
a01n10  (node)
a01n11  (node)
a01n12  (node)
a01n13  (node)
a01n14  (node)
a01n15  (node)
a01n16  (node)
a01n17  (node)
a01n18  (node)
```

Using noderanges:

```
lsdef a01n[01-10] -i ip -c        <-- OK
lsdef a01n[01-09] -i ip -c        <-- OK
lsdef /a01n[01-10].* -i ip -c    <-- OK
lsdef /a01n[01-09].* -i ip -c    <-- ERROR 
```

```
Error: DBobjectdefs plugin bug, pid 30490, process description: 'xcatd SSL: lsdef for root@localhost: DBobjectdefs instance' with error 'Invalid [] range "1-0" in regex; marked by <-- HERE in m/^a01n[01-0 <-- HERE 3].*$/ at /opt/xcat/lib/perl/xCAT/NodeRange.pm line 336.
```

**Comment by whowutwut** [comment]
Interesting find...

**Comment by bybai** [comment]
Hi @gurevichmark,
``[01-09]`` is not right regular expression since it contains ``1-0``. 
Refer to "It is not uncommon to want to match a range of characters. Luckily, instead of listing all characters in the range, one may use the hyphen (- ). If inside a bracketed character class you have two characters separated by a hyphen, it's treated as if all characters between the two were in the class. For instance, [0-9] matches any ASCII digit, and [a-m] matches any lowercase letter from the first half of the ASCII alphabet." in https://perldoc.perl.org/perlrecharclass.html#Extended-Bracketed-Character-Classes.


So ``lsdef /a01n[01-09].* -i ip -c`` should be ``lsdef /a01n[01-9].* -i ip -c``.
```
[root@bybc0602 autotest]# lsdef /a01n[01-9].* -i ip -c
a01n01: ip=50.1.1.01
a01n02: ip=50.1.1.02
a01n03: ip=50.1.1.03
a01n04: ip=50.1.1.04
a01n05: ip=50.1.1.05
a01n06: ip=50.1.1.06
a01n07: ip=50.1.1.07
a01n08: ip=50.1.1.08
a01n09: ip=50.1.1.09
a01n10: ip=50.1.1.10
