### ISSUE TITLE
[xcat 2.13.2] addkcmdline not working

### ISSUE THREAD

**Issue by Phhere** [xcat2/xcat-core#2738]
Hello,
today i updated from 2.13.1-snap201701110845 to 2.13.2-snap201702222242 from yum repo.
Since then i can not use addkcmdline for node specific options. It does not get added to the kickstart file anymore.

Do you have any idea? Has something changed in syntax?
```
Object name: hilbert69
    addkcmdline=R:: ipv6.disable=1
```

**Comment by whowutwut** [comment]
Hi @Phhere  we are sorry about that.  I think you are hitting this issue: https://github.com/xcat2/xcat-core/issues/2614   It was broken when we added some changes in to improve the nodeset time performance.   This issue was fixed on 3/9 with the following PR: https://github.com/xcat2/xcat-core/pull/2620 

Until 2.13.3 comes out, you can either patch with the pull request or update to the latest devel build.  

I checked on my system...  Using a 3/3 build... I added this attribute: 
```
[root@c910f02c05p03 tmp]# lsdef fs2vm105 -i addkcmdline
Object name: fs2vm105
    addkcmdline=modprobe.blacklist=nvidiafb
```

Nodeset resulted in the following, nothing is added from the addkcmdline, like you experienced.

```
[root@c910f02c05p03 tmp]# cat /tftpboot/boot/grub2/fs2vm105
#install rhels7.3-ppc64le-compute
set timeout=5
set default="xCAT OS Deployment"
menuentry "xCAT OS Deployment" {
    insmod http
    insmod tftp
    set root=tftp,10.2.5.3
    echo Loading Install kernel ...
    linux /xcat/osimage/rhels7.3-ppc64le-install-compute/vmlinuz quiet inst.repo=http://10.2.5.3:80/install/rhels7.3/ppc64le inst.ks=http://10.2.5.3:80/install/autoinst/fs2vm105 BOOTIF=42:01:23:2d:8f:25  ip=dhcp  inst.cmdline  console=tty0 console=hvc0,115200
    echo Loading initial ramdisk ...
    initrd /xcat/osimage/rhels7.3-ppc64le-install-compute/initrd.img
```

Updating to today's dev build, running nodeset, it's added back to the kickstart config 

```
[root@c910f02c05p03 tmp]# cat /tftpboot/boot/grub2/fs2vm105
#install rhels7.3-ppc64le-compute
set timeout=5
set default="xCAT OS Deployment"
menuentry "xCAT OS Deployment" {
    insmod http
    insmod tftp
    set root=tftp,10.2.5.3
    echo Loading Install kernel ...
    linux /xcat/osimage/rhels7.3-ppc64le-install-compute/vmlinuz quiet inst.repo=http://10.2.5.3:80/install/rhels7.3/ppc64le inst.ks=http://10.2.5.3:80/install/autoinst/fs2vm105 BOOTIF=42:01:23:2d:8f:25  ip=dhcp  inst.cmdline  console=tty0 console=hvc0,115200 modprobe.blacklist=nvidiafb
    echo Loading initial ramdisk ...
    initrd /xcat/osimage/rhels7.3-ppc64le-install-compute/initrd.img
```

**Comment by whowutwut** [comment]
Dup to https://github.com/xcat2/xcat-core/issues/2614

**Comment by whowutwut** [comment]
Closing for now, please feel free to re-open or continue to discuss if needed.
