### ISSUE TITLE
performing yum update xCAT* overwrote our log rotate settings.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#2795]
We have the following log rotate settings for xcat (which we modified after install).

```
/var/log/xcat/*.log {
    missingok
    sharedscripts
    compress
    postrotate
        test -f /var/run/rsyslogd.pid && kill -HUP `cat /var/run/rsyslogd.pid 2> /dev/null` 2> /dev/null || true
        test -f /var/run/syslogd.pid && kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
        test -f /var/run/xcat/cmdlogservice.pid && kill -HUP `cat /var/run/xcat/cmdlogservice.pid 2> /dev/null` 2> /dev/null || true
    endscript
}
```

After doing a yum update xCAT* we were left with:
```
/var/log/xcat/*.log {
    missingok
    sharedscripts
    postrotate
        test -f /var/run/rsyslogd.pid && kill -HUP `cat /var/run/rsyslogd.pid 2> /dev/null` 2> /dev/null || true
        test -f /var/run/syslogd.pid && kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
        test -f /var/run/xcat/cmdlogservice.pid && kill -HUP `cat /var/run/xcat/cmdlogservice.pid 2> /dev/null` 2> /dev/null || true
    endscript
}
```

```
FILE COMPARISON
Produced: 3/31/2017 3:28:53 PM

Mode:  Just Differences

Left file: c:\wtools\r92gitlab\research-92-cluster\r92config\system\etc\logrotate.d\xcat
Right file: c:\wtools\r92gitlab\research-92-cluster\r92config\r92rsync\system\etc\logrotate.d\xcat
    compress +-
----------------
```

Please don't throw away our settings after performing an update...

**Comment by whowutwut** [comment]
@robin2008  can you take a look at this?

**Comment by robin2008** [comment]
xCAt don't want customer modify the OOB configuration for this files as we don't know if those changes w/o the support of xCAT will impact xCAT functionalities. (In this case, it seems no impact as only compress the historic logs.)

In that, xCAT does not consider this file as a config file (%config) in spec, but a normal package file(%file). And no additional steps in spec scripts to do the backup and restore.  Then, this file will be always be replaced with the file in package of the new version.
refer http://rpm5.org/docs/max-rpm.html#s2-rpm-upgrade-config-file-magic for more detail 

To fix this issue is simple enough, but it introduce a more bigger question to us as there are more  configuration files there, rsyslog, ntpd, named, dhcp, etc.

**Comment by immarvin** [comment]
hi @whowutwut @robin2008 , it is a problem that we take config files the same as ordinary files in %files in xCAT spec. From the rpm packaging guide, the suggestion for the rpm shipped config files is:

````
Configuration files should be placed in /etc and are normally specified like this (which makes sure user changes aren't overwritten on update):

%config(noreplace) %{_sysconfdir}/foo.conf
If the update uses a non-backwards-compatible configuration format, then specify them like this:

%config %{_sysconfdir}/foo.conf
"%attr(mode, user, group)" can be used for finer control over permissions, where a "-" means use the default:

%attr(0600, root, root) FOO.BAR
````

I think we should modify xCAT spec files to confirm to the standard guideline.

**Comment by robin2008** [comment]
@immarvin we still need more discussion about the change as it is hard for us know if the user's customization will impact our function. Like here,  to use "compress" might impact xcat-probe.

In addition, when we change the configuration files to introduce new feature,  *.rpmsave, *.rpmnew *.rpmorig will be generated in the same directory by package management tool, sometimes it will  mess the service when it ignore the config file name suffix.  We have to handle them in our postscript.

I prefer to use a conservative way, for example, to backup the orig config file to somewhere, and prompt user to check it.

@ralphbellofatto what's your comments?  and do you have any other customization requirement on the config file?

**Comment by ralphbellofatto** [comment]
why would compressing old log files have any affect on xcatprobe.   the compress option only affects the rotated files.

I really don't appreciate systems that wipe out our settings when we do a yum updatenode xxx

**Comment by immarvin** [comment]
hi @ralphbellofatto , how about we backup the original "/etc/logrotate.d/xcat" and replace the config file with the one shipped in xCAT on upgrade? then if you want, you can take the backup config file back

**Comment by ralphbellofatto** [comment]
How about not touching the fields we changed when dealing with logging.  We added compress to this system because the xCAT log files managed to completely fill up our management node hard drive and crash the system.

Once we set these values, and rpm update should NOT overwrite them.

**Comment by robin2008** [comment]
@ralphbellofatto 
Thanks for the clarification, we know it is an real issue on your environment.  We had gone through the codes carefully,  and found that if using 'compress' here the xcat-probe feature might be impacted as it will look information in log files and not considering a compress mode.

I think I can fix the log config file specifically as the 'compress' option should be general enough. But it will not be a general fix for all the configuration files. We do not encourage user to customize the internal xcat config file,  as any non-documented customization might be out-of-control and bring side effect to xcat normal functions.

**Comment by whowutwut** [comment]
What about considering to ship the xCAT configuration file with compress? What seems to be the downside of using compress all the time to save space on the system? 

@immarvin I do think if we have configuration files, we might want to preserve the changes that the user makes and not overwrite, if we can change that in the spec, it might be good.  @robin2008 we don't need to change all of them right now, but currently this file is something that @ralphbellofatto  has changes to...  i don't think the change he is doing is bad, so maybe we should either adopt it and ship by default, or do not overwrite users config...  

The same issue happens with our rsyslog configuration file, perhaps we need to see a better way to modify that file so that we do not overwrite users config.  we have an XCAT section in there to identify our own configuration.. but if there's a better way. we should consider it.

**Comment by immarvin** [comment]
hi @whowutwut @ralphbellofatto @robin2008 , created a fix in https://github.com/xcat2/xcat-core/pull/2884/files.

I think it solved the requirement from @ralphbellofatto and the possibility that xCAT changed the /etc/logrotate.d/xcat , please see the descriptions of the PR for details

**Comment by robin2008** [comment]
It is a safe method currently for handling the log rotate configuration in xcat,  and it is the way used in most of other open source project.

**Comment by daniceexi** [comment]
@immarvin @robin2008 The change is using the keyword ``config``, I'd like to know the default action of **config** file when do the update if the origin file was changed by customer.

**Comment by robin2008** [comment]
If no change for this config file new xCAT version,  the user modified file will be still there.

Original file = X, Current file = Y, New file = X

Here we have a file that was changed at some point. However, the new file is identical to the existing file prior to the local modifications.

In this case, RPM takes the viewpoint that since the original file and the new file are identical, the modifications made to the original version must still be valid for the new version. It leaves the existing, modified file in place. 

If we don't change the config file in new version,  the user modified file will be still there.

If changes are made for this config file by new xCAT version,  the default behavior is to use the latest config file, but the user modified file will be still kept as *.rpmsave in the same directory.

**Comment by daniceexi** [comment]
@robin2008 thanks for the clarification.
