### ISSUE TITLE
yum update xCAT on 2.11 complains about Juniper file rename

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#287]
Starting with the 2.11 build on Oct 7th...
```
# lsxcatd -a 
Version 2.11 (git commit 136b9319f3ac952261f40738e6f83e87c58285c6, built Wed Oct  7 07:30:46 EDT 2015)
This is a Management Node
cfgloc=Pg:dbname=xcatdb;host=10.2.5.3|xcatadm
dbengine=Pg
dbname=xcatdb
dbhost=10.2.5.3
dbadmin=xcatadm
```

And pointing to the yum repo on xcat.org... I issued ``yum update "*xCAT*"``
The following error messages comes out when updating xCAT-server.  

```
# yum update "*xCAT*"
...
  Updating   : 4:xCAT-server-2.11-snap201510151931.noarch                                                 3/14 
Error unpacking rpm package 4:xCAT-server-2.11-snap201510151931.noarch
error: unpacking of archive failed on file /opt/xcat/share/xcat/devicetype/EthSwitch/Juniper: cpio: rename
```

**Comment by whowutwut** [comment]
@bybai  @cxhong Can one of you look at this bug?

**Comment by whowutwut** [comment]
Oh I just noticed that this causes xCAT-2.11 to fail installing.  I hit this before too and so my xCAT is at 2.10 version... also genesis base is at 2.10... 
```
# rpm -qa | grep xCAT
xCAT-genesis-base-ppc64-2.10-snap201505172314.noarch
xCAT-genesis-scripts-ppc64-2.11-snap201510151931.noarch
xCAT-server-2.10-snap201506232220.noarch   <=====================
perl-xCAT-2.11-snap201510151930.noarch 
xCAT-buildkit-2.11-snap201510151931.noarch
xCAT-2.11-snap201510151931.ppc64
xCAT-client-2.11-snap201510151930.noarch
xCAT-confluent-2.11-snap201510151931.noarch
```

**Comment by whowutwut** [comment]
I have a fix for this

**Comment by bybai** [comment]
@whowutwut  
Although I cannot reproduce the defect when I execute ``yum update "*xCAT*"`` in my environment, your fix is an enhancement  to  "remove the old directory otherwise the symlink won't get created correctly", it is a save fix. 
I tried this fix in my another MN as following:
[root@c910f04x41 xcat-core]# rpm -Uvh xCAT-server-2.11-snap201510210035.noarch.rpm
Preparing...                          ################################# [100%]
\+ '[' -d /opt/xcat/share/xcat/devicetype/EthSwitch/Juniper ']'
\+ rm -rf /opt/xcat/share/xcat/devicetype/EthSwitch/Juniper
\+ set +x
Updating / installing...
   1:xCAT-server-4:2.11-snap2015102100################################# [ 50%]
Cleaning up / removing...
   2:xCAT-server-4:2.10-snap2015072405################################# [100%]
[
root@c910f04x41 EthSwitch]# ls -lt
total 4
drwxr-xr-x 2 root root  19 Oct 21 00:41 Mellanox
drwxr-xr-x 2 root root  19 Oct 21 00:41 BNT
drwxr-xr-x 2 root root  19 Oct 21 00:41 Cisco
drwxr-xr-x 2 root root  19 Oct 21 00:41 Jun
lrwxrwxrwx 1 root root   3 Oct 21 00:41 Juniper -> Jun
-rw-r--r-- 1 root root 439 Oct 21 00:35 config

**Comment by whowutwut** [comment]
Closing out this issue
