### ISSUE TITLE
Support variable substitution in synclists

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#2963]
It would be convenient if syncfiles supported variable substitution.  The two that make the most sense are node and profile.  For example:
```
/install/custom/syncfiles/etc/hosts.%PROFILE% -> /etc/hosts
/install/custom/syncfiles/etc/ssh/sshd_config.%NODE% -> /etc/ssh/sshd_config
````
(Note: the %VARNAME% syntax is just an example, it might make more sense to use $VARNAME or some other format)
For a host with profile `compute` and hostname `node01`, it would try to use files `/install/custom/syncfiles/etc/hosts.compute` and `/install/custom/syncfiles/etc/ssh/sshd_config.node01`

**Comment by mattaezell** [comment]
We might be able to get what we need with much-more-verbose noderange syntax:
```
/install/custom/syncfiles/etc/hosts.compute -> (node[01-03]) /etc/hosts
/install/custom/syncfiles/etc/ssh/sshd_config.node01 -> (node01) /etc/ssh/sshd_config
/install/custom/syncfiles/etc/ssh/sshd_config.node02 -> (node02) /etc/ssh/sshd_config
/install/custom/syncfiles/etc/ssh/sshd_config.node03 -> (node03) /etc/ssh/sshd_config
```
Does the noderange syntax also support groups?

**Comment by immarvin** [comment]
hi @mattaezell ,  noderange  and node group are supported in synclist

``file -> (noderange for permitted nodes) file``

please see details in http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/common/deployment/syncfile/syncfile_synclist_file.html#support-nodes-in-synclist-file

for the feature request on supporting variable substitution in synclist, since synclists is an attribute of osimage instead of node(the provmethod="install/netboot" case in the Doc above is deprecated, in most cases, the provmethod will be osimage name).  All the osimage attributes , like %PROFILE% in your example,  are binded to the osimage definition. For each osimage, I do not think it is a frequent scenario to modify its key attributes like   ``osarch``, ``osvers``, ``profile`` and ``provmethod ``.  The variable like %NODE%, it has been covered in the noderange or node groups in synclist.

**Comment by mattaezell** [comment]
So for a 5,000 node cluster I will need to configure 5,000 lines per unique file in my synclist?

**Comment by daniceexi** [comment]
**(noderange)** can be any valid noderange in xCAT. So the signal synclist with noderange ``node[1-5000]`` does work for the 5000 nodes.

**Comment by immarvin** [comment]
no response over 2 weeks, close this ticket. please reopen this if any problem
