### ISSUE TITLE
[FVT] For MLNX_OFED diskless support on RHEL, need to hack command uname while run genimage

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#316]
The management node runs RHEL 7.2 Beta 1, which has kernel version ``3.10.0-313.el7.ppc64le``. And the compute node will use kernel version ``3.10.0-316.el7.ppc64le``. In this case the kernel module of Infiniband failed to compile during the ``genimage`` procedure.

In this case, hacking of ``uname`` is needed, like what xCAT did against Ubuntu.

**Comment by whowutwut** [comment]
@zet809 will these kind of things resolve themselves once we are running GA version of RHEL instead of the beta versions where the kernel level is changing?  

Is hacking the uname just the work around for the current testing situation. Would seem like end users would generally not be using xcat with beta os images?

**Comment by zet809** [comment]
No, it is kind of chroot environment issue, within chroot, uname still return the information of the host rather than the chroot system info. So we have to hack uname to read the system infor within the chroot env such as the kernel version.

**Comment by neo954** [comment]
Already fixed. I will close this one.
