### ISSUE TITLE
[cumulus support]FVT of ztp based autodiscover and autoconfiguration

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3212]
1. Go through the mini-design mentioned in #3176 
2. Go through the document about ztp discovery
3. Write test plan, cover at least one full steps scenario.
4. Do FVT based on the test plan in step3.

**Comment by tingtli** [comment]
Verified on fs3.  Here is the steps
1. Verified version
```
[root@fs3 ~]# lsxcatd -v
Version 2.13.5 (git commit 65d882b9901f6b4346a610c05c6c68b847fc6bee, built Thu Jun 22 22:52:00 EDT 2017)
```
2. on fs3, clean the dhcp lease
```
makedhcp -d mid05tor10
```

3. predefine the switch node
```
[root@fs3 ~]# lsdef -z mid05tor10
# <xCAT data object stanza file>

mid05tor10:
    objtype=node
    groups=switch,edge_switch
    ip=172.21.205.10
    mgt=switch
    nodetype=switch
    switch=mgmtsw01
    switchport=10
```

4. run makehosts to add this node to /etc/hosts
```
[root@fs3 ~]# makehosts mid05tor10
[root@fs3 ~]# cat /etc/hosts |grep -i mid05tor10
172.21.205.10 mid05tor10 mid05tor10.pok.stglabs.ibm.com
```
5. ssh to the switch with default user/pw and run "sudo ztp -R" to enable ZTP

6. reboot switch with "sudo reboot"

7. wait several minutes

8. verify that switch has been discovered and configured
```
[root@fs3 ~]# lsdef -l mid05tor10
Object name: mid05tor10
    arch=armv7l
    groups=switch,edge_switch
    ip=172.21.205.10
    mac=8c:ea:1b:e8:78:c0
    mgt=switch
    netboot=onie
    nodetype=switch
    postbootscripts=otherpkgs
    postscripts=syslog,remoteshell,syncfiles
    serial=11S01FT690YA50YD73EACH
    status=configured
    statustime=06-23-2017 02:45:56
    supportedarchs=armv7l
    switch=mgmtsw01
    switchport=10
    switchtype=Edgecore Networks Switch
```
9. verify the switch can be access with ssh with root without password

10 verify that the static network configuration file can be found in /etc/network/interfaces.d/eth0
```
root@mid05tor10:/etc/network/interfaces.d# ls
eth0  lo  xCAT.intf
root@mid05tor10:/etc/network/interfaces.d# cat eth0
auto eth0
iface eth0 inet static
  address 172.21.205.10
  netmask 255.255.0.0
  hwaddress ether 8c:ea:1b:e8:78:c0
  gateway 172.21.253.27
```

**Comment by hu-weihua** [comment]
@tingtli has finished the basic verification, @neo954 need to do detailed test in 2.13.6 sprint1 first week.

**Comment by cxhong** [comment]
We need to run another test, remove all the configuration file, reinstall OS, then install license file.

**Comment by neo954** [comment]
The basic ZTP procedure has been verified with xCAT 2.13.5 RC2 build.

But I think the scenario I tested and verified is not a typical user scenario. Since all cumulus switch shipped from Mellanox will have operating system installed and ZTP feature disable. Unless the end users choose to reinstall operating system on their cumulus switch, there is no chance the ZTP feature to be used.

Below are the items I think xCAT team need to be

* Define in which situation ZTP feature will be called by the end user. And how xCAT will interact with the end user and the switch.
* With ZTP feature disable out of the box, find a way to initialize and configure the cumulus switch.
