### ISSUE TITLE
[CRL E2E] To support service node pool for petitboot and grub2 +rh7.3 diskless

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3243]
@immarvin had verified service node pool doesn't work for petitboot and grub2. This task is used to trace the fixing of the issue.
The modification for grub2 is lower priority.

**Comment by immarvin** [comment]
PR created https://github.com/xcat2/xcat-core/pull/3268

**Comment by whowutwut** [comment]
@zet809  I'm not sure I understand the problem here.   What part of service node pools does not work? 
I'm reading the following documentation: http://xcat-docs.readthedocs.io/en/stable/advanced/hierarchy/define_service_node.html?#service-node-pools

Is it the `servicenode` keyword? 
Is it the `sharedtftp` site attribute?

**Comment by zet809** [comment]
Hi, @whowutwut , if there are multiple service node specified in 'servicenode' attribute, makedhcp will fail since it simply try to translate the string in 'servicenode' attribute to IP address. It of course will failed that *multiple service nodes* can not be *a* valid hostname, and no IP address will be got.
As mentioned in the pull request #3268, the *servicenode* is only used when dispatch request, once request is running on SN, it will use its facing CN ip or 'xcatmaster' set for CN to be the default DHCP/tftp/http server.
