### ISSUE TITLE
[FVT] add test case for issue 3254: Couldn't find ID in the discinfo database

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3343]
What to do:
* [ ] offer a test cases scope
* [ ] add test cases for issue #3254

**Comment by hu-weihua** [comment]
The requirement is not clear, remove from 2.13.6 first.

**Comment by whowutwut** [comment]
@hu-weihua I don't think the test case requested only affects rhels 7.0 but maybe the way to handle this is to make the code change bad was fixed in the pull request and see if we have a test case that can be created to detect the copyds issue on other ISO files that are more current. That is what we want to detect. If something broke the copycds command in general

**Comment by hu-weihua** [comment]
Has added test case by #5236
