### ISSUE TITLE
[FVT] add test case for issue 1950: Setting the ipmi password incorrectly in the site table causes infinite loop in rpower: Unauthorized name

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3347]
What to do:
* [ ] offer a test cases scope
* [ ] add test cases for issue #1950

**Comment by junxiawang** [comment]
Add new testcase:
rpower_ipmi_wrongpasswd

**Comment by whowutwut** [comment]
@hu-weihua @zet809 I'm still not convinced that we should be opening additional issues to track work on adding testcases that slipped through... .  I think by utilizing the "testcase:requested" and "testcase:added" labels, we can avoid having this extra issue in the middle.  The Pull request 3385 should be linking directly to 1950 and from 1950's perspective, we can see that a testcase was added directly instead of having this issue between....  1950 also contains all the information about the problem.  This intermediate issue does not and I think it's adding confusion
