### ISSUE TITLE
[FVT] FVT of confignetworks

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3365]
what to do:

* [ ] new feature verification test for ``confignetwork``

**Comment by tingtli** [comment]
The test scenarios includes
1) installnic and secondarynic configurations on rhels/suse/ubuntu platforms.  Manually run case confignetwork_s_installnic_diskful, confignetwork_s_installnic_diskless and confignetwork_secondarynic_diskless since they are not put in the daily run bundle.
2) run verification for vlan, bond and bridge cases
