### ISSUE TITLE
[CORAL]incorrect petitboot configuration for nodeset shell in flat hierarchical  

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3414]
The xcatd in petitboot configuration file shall be in the same subnet with CN.
[root@fs3 xcat]# lsdef mid05tor12cn04 -i ip -c
mid05tor12cn04: ip=172.20.140.4
[root@fs3 ~]# cat /tftpboot/petitboot/mid05tor12cn04
#shell
default xCAT Genesis shell
label xCAT Genesis shell
	kernel http://172.20.253.27:80/tftpboot/xcat/genesis.kernel.ppc64
	initrd http://172.20.253.27:80/tftpboot/xcat/genesis.fs.ppc64.gz
	append "quiet xcatd=172.21.253.27:3001 destiny=shell"  ===> The xcatd shall be 172.20.x.x
[root@fs3 ~]# lsdef -t site -i master
Object name: clustersite
    master=172.21.253.27

**Comment by whowutwut** [comment]
@zet809  Let me sync up with @cxhong  today and look at the end to end steps.  Is this to avoid the need to set the master node attribute for the node definitions since we have different operating networks?   In reality, it should not be the master but <xcatmaster> for the network.. could be service node.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/3419
