### ISSUE TITLE
kickstart file is not correct in hierarchy mode

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat-core#3428]
In an hierarchy mode with service pool:
site.master = 172.21.

For nodes under sn01 and sn02,  and with below settings:
    noderes.servicenode=sn01,sn02
    noderes.xcatmaster=''

In the design (not using share /install),  the kickstart file generated on sn01 and sn02 should using the CN facing IP address (172.20.x.x),  but now  it contains the IP of site.master.  It will cause installation failed and loop install again and again.

BTW:
This could be workaround by set noderes.xcatmaster='172.20.x.x' explicitly.

**Comment by whowutwut** [comment]
@robin2008 Is this a feature that we need ? Or the "work around" is just a documentation/configuration error that we have? 

@daniceexi, you mentioned that `xcatmaster` on the nodedefintion controls the mgmt/sn that the compute node goes to.  So if that is the way to resolve it, we should just fix the documented process so the users know how to configure a hierarchy environment where the SN -> CN network are separated from the MGMT -> SN subnet, rather than making a feature enhancement...

**Comment by robin2008** [comment]
This is a feature we want for service node pool,  it means to auto-detect the value of `xcatmaster` when  `xcatmaster` is not set. It will grant service node pool  the capability of failover for OS installation.

We have already fix such issue  for dhcp lease/grub2/petitboot (if not set,  using the CN facing IP address by default), and then it could works for stateless provision.  Now for stateful,  we still need cover the kickstat/yast2/preceed.

**Comment by robin2008** [comment]
Actually,  there is still another issue here.  If using shared /install for both MN and SN,  the file generated on one SN will be overridden by another SN as the file name is the same.

Discussed with @immarvin before,  we may need to figure out if there are any method to handle it.

**Comment by robin2008** [comment]
Fixed by #3696 
For service node managed CN, use the facing IP address as higher priority when no xcatmaster is set.
