### ISSUE TITLE
go-xcat, without the required packages has a bunch of tee error messages 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3437]
Ran go-xcat using version 1.0.20, I see these error messages coming out: 

```
[root@fs2vm112 yum.repos.d]# chmod +x /tmp/go-xcat 
[root@fs2vm112 yum.repos.d]# /tmp/go-xcat --xcat-version devel update
Operating system:   linux
Architecture:       ppc64le
Linux Distribution: rhel
Version:            7.3

Reading repositories ...... done

xCAT is going to be updated.
Continue? [y/n] y
[root@fs2vm112 yum.repos.d]# tee: /tmp/go-xcat.45qYjTRF/update_xcat.stderr: No such file or directory
Command "repoquery" not found.
go-xcat: Install the `yum-utils' package and rerun.
go-xcat: Failed to get package list from repository `xcat-core'.
tee: /tmp/go-xcat.45qYjTRF/update_xcat.stdout: No such file or directory
```

**Comment by neo954** [comment]
I will look into this one.

**Comment by neo954** [comment]
@vhu, I cannot recreate your problem.

The script `go-xcat` use a temporary directory as its working place. In your case, it is `/tmp/go-xcat.45qYjTRF`. Actually, the only way I can recreate the problem is remove its temporary directory where the script is running.

So here is the re-creation steps.

1. Run the script

   # /tmp/go-xcat --xcat-version devel update
   Operating system:   linux
   Architecture:       ppc64le
   Linux Distribution: rhel
   Version:            7.3

   Reading repositories ...... done

   xCAT is going to be updated.
   Continue? [y/n] y

2. Where the script prompt you to continue, open another terminal, check the directory name of the temporary directory and delete it.

    # ls -ld /tmp/go-xcat*
    -rwxr-xr-x 1 root root 40687 Jun  9 03:16 /tmp/go-xcat
    drwx------ 2 root root  4096 Jul 12 23:28 /tmp/go-xcat.8mwvvnai
    # rm -rf /tmp/go-xcat.8mwvvnai

3. Now switch back the terminal which is running `go-xcat`. Press `y` and `Enter` to make the script continue running. And get the error message.

    Continue? [y/n] y
    tee: /tmp/go-xcat.8mwvvnai/update_xcat.stdout: No such file or directory
    tee: /tmp/go-xcat.8mwvvnai/update_xcat.stderr: No such file or directory
    Command "repoquery" not found.
   go-xcat: Install the `yum-utils' package and rerun.
   go-xcat: Failed to get package list from repository `xcat-core'.

**Comment by neo954** [comment]
Even in this case, I don't think it is bug. The error message shows what it mean.

**Comment by whowutwut** [comment]
Thanks for checking
