### ISSUE TITLE
[CORAL]investigate the MN HA requirement in CORAL

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#3484]
Need to investigate which HA solution is required in CORAL.
1. #1267 
2. shared data
3. #3938 
...

**Comment by bybai** [comment]
Based on share data HA doc :http://xcat-docs.readthedocs.io/en/latest/advanced/hamn/setup_ha_mgmt_node_with_shared_data.html#setup-ha-mgmt-node-with-shared-data;
During setup primary xcat mn and switch database to postgresql using `pgsqlsetup -i -V`,  the script hang on "Restoring the xCAT Database with /root/xcat-dbback to PostgreSQL database."

**Comment by bybai** [comment]
There are 2 main issue I hit:
1, The old share data HA doc mainly focus on aix/db2, it is different from our plan. So the old share data HA doc is not suitable for current redhat/postgresql situation. I start to draft a new steps 
2, Based on old doc, /install dir is mounted from nfs server. In redhat7.4, genimage hit problem to install iputils, so if using nfs based share data, /install directory can not be mounted from nfs server. /install dir can rsync from primary MN to secondary MN.

**Comment by bybai** [comment]
I setup xcat MN HA using nfs shared data, the steps command list is in https://github.com/bybai/xCAT_features/issues/6; I used nfs shared data is to imitate the shared data HA main process based on rh7.4 and postgresql since current shared data HA doc is mainly based on AIX and DB2.  Except the shared data using nfs or not is different, the HA process for xcat on rh7.4 and postgresql is the same. My next plan is to update current HA doc based on rh7.4 and postgresql.

**Comment by zet809** [comment]
The investigation result can be found at https://github.com/bybai/xCAT_features/issues/6, so, @bybai , pls close this task. Thx!
