### ISSUE TITLE
p9 rpower off/on of a hung node does not recycle a hung OS.

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#3498]
p9 rpower off/on of a hung node does not recycle a hung OS.
Levels:
Updated xCAT to latest dev build and currently running 1724a on a water cooled witherpoon:
[root@c685mgt02 ~]# lsxcatd -v
Version 2.13.6 (git commit 6ca241c9d0d361895d2246f410910248a1b06fbc, built Tue Jul 18 06:15:37 EDT 2017)

```
root@c685f4bmc02:~# pflash -r /dev/stdout -P VERSION
Reading to "/dev/stdout" from 0x027e0000..0x027e1000 !
[                                                  ] 0%IBM-witherspoon-ibm-OP9_v1.17_1.20
	op-build-v1.16-87-g5e69953-dirty
	buildroot-2017.02.2-7-g23118ce
	skiboot-05b8834-p7542d9b
	hostboot-d02273f
	linux-4.11.1-openpower1-p77ac250
	petitboot-v1.4.2-pf0e80a2
	machine-xml-e536539
	occ-8a7df03
	hostboot-binaries-d8f4ab7
	capp-ucode-9c73e9f
	sbe-d770027
[==================================================] 100%
root@c685f4bmc02:~# cat /etc/*release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="ibm-v1.99.6"
VERSION_ID="ibm-v1.99.6-0-r1"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) ibm-v1.99.6"
BUILD_ID="ibm-v1.99.6-0-r1"
```

Description:
c685f4n02 hung around 15:30 and the user tried an rpower off/on around 16:00.
They opened a console but nothing was generated.
16:30 I tried rpower off, rpower status reflected off. 
           rpower on/opened a console and did not see any data flow to the screen.
I checked the bmc and observed the power was off but 
CurrentHostState:   xyz.openbmc_project.State.Host.HostState.Running
I then ran obmcutil poweroff and poweron from the bmc and the OS started booting.
It looked like because of the OS hang, the power off was not quiescing or shutting down the Host so the power on was not recycling the OS. (Not sure tho).
You may be able to recreate this way:
1) On the node "echo 1 > /proc/sys/kernel/sysrq"
2) open a console to the node
3) ctl-O x (control letter O, then x) this will enter xmon and the OS will be unresponsive.
Then rpower the node off and check the "obmcutil state" and "obmcutil power" status.
Try to power the node on, watch the console to see if the OS boots and check the CurrentHostState.

**Comment by immarvin** [comment]
hi @xuweibj , would you please take a look at this?

**Comment by whowutwut** [comment]
@xuweibj Just to provide you some information...  I know for the firmware levels that are > 1724A/B, the "soft off" function was implemented in the openbmc side and so sending a transition OFF to the host object, results in soft off.    I supported this in https://github.com/xcat2/xcat-core/pull/3425

During this  "timeout" period for softoff, I don't think we can send a transition OFF to the chassis object.  Once the chassis actually powers off, the states are not reflected correctly as I have indicated in this issue: https://github.com/openbmc/openbmc/issues/1933

However, @markprez issue is a little different, because he is running 1724 and also updated to the latest xCAT development build.  So the power off should be reflected in `rpower <> state` which I think it is.... But the issue he brings up here is that they were not able to boot the node and see console messages using `rpower <> on`.  .....  but without the ability to re-create or look at the logs, we cannot really tell.. so i'm not sure how much time you want to spend on this today...

@markprez On the BMC, can you provide us with the journalctl logs that show the rest call to power on/off?   I can help find this tomorrow if you cannot easily find them.

**Comment by xuweibj** [comment]
I think I did not get the point. Is this that when run rpower off or on, got nothing msg on the screen for a long time? Or run rpower successfully, but the nodes did not off or on?

**Comment by whowutwut** [comment]
@xuweibj  With the problem @markprez  mentioned

1) something hung on the OS side 
2) rpower <> off is run,  CurrentPowerState=Off,  CurrentHostState=Running,   This is probably a issue reporting correct states with openbmc in https://github.com/openbmc/openbmc/issues/1933.  But if CurrentPowerState=Off, the power should be off to the chassis. 
3) At this point, rpower on does not work anymore...  
4) Resolved it by ssh to the BMC and using `obmcutil poweron` 

I think this is a firmware issue, but need to gather some more information.

**Comment by whowutwut** [comment]
Talked to Andrew, there's some bug 
> using chassis object isn’t not a good idea right now, it gets the host target in a messed up state if the system is booted

So the best way to power off is to do a "softoff" until the bug is fixed.  @markprez This means you should be doing `rpower <> softoff` instead of off for now.  As long as we are running 1728 and higher, the softoff timer is reduced to 5 minutes so if the OS hangs, the most it will wait is 5 minutes before cold off is sent. 

There's no fix planned for xCAT, but will leave this issue open to track.

**Comment by whowutwut** [comment]
This should be resolved in 1730C/D firmware, if more issues arise, please re-open or open another and we will pursue with Firmware Team.
