### ISSUE TITLE
cumulus switch enablesnmp does not program the community password to match the site or switch table.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#3614]
our site table contains:
    snmpc=our_site_password

In our system we have a common pw for all switches.

However after running 
updatenode c685tors05 --scripts=enablesnmp

```
xdsh c685tors05 grep community /etc/snmp/snmpd.conf
c685tors05: #rocommunity public localhost
c685tors05: rocommunity public default
c685tors05: rocommunity public  default    -V systemonly
```

So xcat does not work with this properly unless we manually configure this, because leaving the snmp settings as a public key is a known security problem.

**Comment by cxhong** [comment]
the default password is "public",  need to modify based on snmpc attribute in the site table or password in the switches table.

**Comment by whowutwut** [comment]
@immarvin @cxhong, need to take a look into this and get something in place for the cluster being brought up by @ralphbellofatto. 

@mattaezell Are you hitting this similar issue on your switches in your lab?

**Comment by mattaezell** [comment]
@whowutwut I've only used end-to-end switch setup using a switch on my desk connected to my desktop.  I didn't have any snmp passwords setup in my _passwd_ table, so it configured a RO community as _public_ and a rw community using a hardcoded value.  I hope to get to an end-to-end test on our Garrison cluster late next week.

**Comment by whowutwut** [comment]
@immarvin any ideas on how to implement this?

**Comment by immarvin** [comment]
hi @whowutwut @cxhong , I went through the description of ``site.snmpc`` of ``switches.snmpversion``, ``switches.username`` and ``switches.password``, I think the logic to determine the SNMPv1 community for a specified switch("sw1" as an example) is :
1. if "sw1" is specified in switches table, and ``switches.snmpversion``!= "3", take ``switches.password`` if specified as the community; otherwise goto step 2
2. take ``site.snmpc`` as the community if specified; otherwise goto step 3
3. take "public" as the community string

For the switches(BNT, Mellanox) other than cumulus,  the "community" string  is only used as the authenticate info to get switch information via SNMPv1, we won't set this to the SNMPv1 configuration of the switch. But for cumulus switches, the SNMPv1 is disabled by default,  currently we just enable the SNMPv1. So if we decide to support setting SNMPv1 community, this is a little inconsistency with other switch types we support, I think it's ok. 

hi @cxhong , what do you think? would you please take a look at the implementation according to the description above? we might need to pass community as a environment variable or argument to the enablesnmp script, the usage of enablesnmp script might need to be restricted, for example,  "xdsh xxx snmp" might not work well. thanks

hi @mattaezell , although the description of ``switches.password`` mentions:
````
password:	The password string for SNMPv3 or community string for SNMPv1/SNMPv2.  Falls back to passwd table, and site snmpc value if using SNMPv1/SNMPv2.
````
I went though our code and do not think ``passwd`` table will be used while determining the community

**Comment by cxhong** [comment]
xCAT didn't use **passwd** table and it is using **swtiches.password** to determine the community, the description of **switches.password** is correct.  If nothing define in the **switches.password** or **site.snmpc **, it will default to **public**.    If user has community string other than default, it needs to be define in the **switches.password** or **site.snmpc**.  I will implement the code to export the variable to mypostscripts , so **updatenode sw1 enablesnmp** will set correct community string.

**Comment by ralphbellofatto** [comment]
xcat when deciding what passwords to use looks in the switches.password first and then looks in the site table

[root@c460mgt01 ~]# lsdef -t site clustersite -i snmpc
Object name: clustersite
    snmpc=NONPUBLICPASSWORD


As a result the programming of the cumulus switches need to also reflect this.

**Comment by cxhong** [comment]
will close this.
