### ISSUE TITLE
[fvt] the same typo in 7 cases against confignetworks

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#3753]
In below cases 

    confignetwork_2eth_bridge_br0 
    confignetwork_2eth_bridge_br22_br33
    confignetwork_bond_eth2_eth3
    confignetwork_bond_false
    confignetwork__bridge_false
    confignetwork_installnic_2eth_bridge_br22_br33
    confignetwork_vlan_bond

There is the same typo in line 
    
    cmd:chdef $$CN nicips.$$THIRDNIC=12.1.0.100 nictypes.$$SECONDNIC=Ethernet nicnetworks.$$THIRDNIC=12_1_0_0-255_255_0_0

It should be 

    cmd:chdef $$CN nicips.$$THIRDNIC=12.1.0.100 nictypes.$$THIRDNIC=Ethernet nicnetworks.$$THIRDNIC=12_1_0_0-255_255_0_0

**Comment by bybai** [comment]
Hi @tingtli , Since there is no brctl command in compute node, all bridge related cases are failed. So `bridge-utils` should be installed in compute node before all these running. So you can add bridge-utils into diskful osimage pkglist, or you can add `yum -y install bridge-utils` into all bridge related cases.

**Comment by hu-weihua** [comment]
Has been verified in automation environment. close this defect.
