### ISSUE TITLE
[OpenBMC] Add trace log to record request and response

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#3796]
If ``xcatdebugmode`` is 1/2, will print debug info on the screen and add into /var/log/xcat/cluster.log.
Output:
```
# rpower openbmctest stat
openbmctest: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://9.3.185.29/login
openbmctest: [openbmc_debug] login_response 200 OK
openbmctest: [openbmc_debug] curl -k -b cjar -X GET -H "Content-Type: application/json" https://9.3.185.29/xyz/openbmc_project/state/enumerate
openbmctest: [openbmc_debug] rpower_status_response 200 OK
openbmctest: on
```

Log:
```
Aug 29 23:04:59 c910f03c05k04 xcat[3507]: DEBUG [openbmc_debug] openbmctest curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://9.3.185.29/login
Aug 29 23:04:59 c910f03c05k04 xcat[3507]: DEBUG [openbmc_debug] openbmctest login_response 200 OK
Aug 29 23:04:59 c910f03c05k04 xcat[3507]: DEBUG [openbmc_debug] openbmctest curl -k -b cjar -X GET -H "Content-Type: application/json" https://9.3.185.29/xyz/openbmc_project/state/enumerate
Aug 29 23:05:00 c910f03c05k04 xcat[3507]: DEBUG [openbmc_debug] openbmctest rpower_status_response 200 OK
```

**Comment by whowutwut** [comment]
@zet809 @xuweibj Before you spend too much time on this. What does the response look like when it's printed into the logs. The best output is really what is printed by Dumper() but that doesn't directly go into the logs (esp for hierarchy...)  So I don't want to waste time trying to format JSON data into xCAT logs...  

My suggestion, and I also mentioned this on the call...  is to just generate the curl command for the user to execute when xcatdebugmode=1.  

This would save us a lot of time when we need to ask the user to capture more data.  Instead of trying to piece together the curl command, they can just copy/paste it on the command line.   So our response would be: 
1.  Set `xcatdebugode=1` , give us that output 
2.  Run the curl command that's printed when debugmode is on and send us that output. 

then we also are not printing large amounts of data, it would affect performance.

**Comment by xuweibj** [comment]
@whowutwut, thank you for your comments.
I modified the description, do you have any other comments?

**Comment by whowutwut** [comment]
So that code was really there for us to debug the power issues that we were experiencing and also to implement the transition states, (powering-on, powering-off) but the firmware has been very buggy to this point and we just temporarily removed the transition states with #3812 ... If we have the curl output that you added in with the above PR, then maybe there's no need to print this info.. when we are ready to implement it we would easily copy/paste the debug to get the response. But it won't be real time... we may miss the status..     

@gurevichmark any thoughts on this question?  Maybe leave it until we implement the transition states?
