### ISSUE TITLE
[cumulus] support the cumulus os upgrade procedure

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat-core#3820]
* [ ]  propose a design for the cumulus os upgrade procedure under the scenario of CORAL
* [ ]  finish the xCAT code update if any modification needed
* [ ]  create a Documentation on cumulus os upgrade procedure

**Comment by immarvin** [comment]
hi @cxhong , since you have managed to upgrade the cumulus os to 3.2.2, how did you do that? would you please take a look at the steps on cumulus os update? 

thanks

**Comment by cxhong** [comment]
Upgrading Cumulus Linux via Package Upgrade
---upgrading only the changed packages, configuration data stays in place.
---The process takes long time to complete.  (took one and half hour for me from wget to complete upgrade)
---if user changed syslog conf file, the upgrade process will prompt few times for user to choose different options. (I choose N for do not upgrade syslog conf file)
---the license file needs to reinstall,  otherwise ifreload command will be failed.

most switch doesn't have internet access, need to download cumulus OS repo to xCAT MN. The wget process took at least half hour to download the files.  User can download it once in some location, compress them, then transfer to xCAT MN, uncompress them.
````
 # mkdir -p /install/mirror/cumulus
# cd /install/mirror/cumulus
# wget -m --no-parent http://repo3.cumulusnetworks.com/repo/
````
The following steps need to have a postscripts (or xdsh), modify the /etc/apt/sources.list to change cumulus repo to xCAT MN
````
# cat sources.list
deb     http://172.21.253.37/install/mirror/cumulus/repo3.cumulusnetworks.com/repo CumulusLinux-3 cumulus upstream
deb-src http://172.21.253.37/install/mirror/cumulus/repo3.cumulusnetworks.com/repo CumulusLinux-3 cumulus upstream

deb     http://172.21.253.37/install/mirror/cumulus/repo3.cumulusnetworks.com/repo CumulusLinux-3-security-updates cumulus upstream
deb-src http://172.21.253.37/install/mirror/cumulus/repo3.cumulusnetworks.com/repo CumulusLinux-3-security-updates cumulus upstream

deb     http://172.21.253.37/install/mirror/cumulus/repo3.cumulusnetworks.com/repo CumulusLinux-3-updates cumulus upstream
deb-src http://172.21.253.37/install/mirror/cumulus/repo3.cumulusnetworks.com/repo CumulusLinux-3-updates cumulus upstream

#xdsh mid08tor10 "cp /etc/apt/sources.list /etc/apt/sources.list.cumulus"
#xdcp mid08tor10 sources.list /etc/apt/sources.list
#xdsh mid08tor10 "apt-get upgrade"    <<<<<< seems took a hour to finish from 3.1.0 to 3.4.1
#xdsh mid08tor10 reboot
````

after upgrade,  license file need to install again (not sure if restart switchd will be enough, need to verify)
````
#/opt/xcat/share/xcat/scripts/configonie --switches mid08tor10 --license licensefile.txt
#xdsh mid08tor10 "systemctl restart switchd;ifreload -a"
````

**Comment by cxhong** [comment]
**Upgrade cumulus OS with image bin file.**
Prepare the Cumulus installation image, /install/onie/onie-installer is the hard-coded path for the Cumulus installation image, link this file to the Cumulus installation image on the management node
````
mkdir -p /install/onie/
cp /install/custom/sw_os/cumulus/cumulus-linux-4.1.0-bcm-armel.bin /install/onie/
ln -s /install/onie/cumulus-linux-4.1.0-bcm-armel.bin /install/onie/onie-installer
````
use onie-install to install image (need to have process to save config files, then restore after installation)
````
#xdsh mid08tor10 "onie-install -a -f -i  http://172.20.253.37/install/onie/onie-installer;reboot"
````
please checking the /var/log/messages and /var/log/xcat/computers.log or cluster.log

once xCAT got dhcp request again,  it will get to node discover process (@yangsong, can u verify if ZTP involve here).   once the switch up,  the snmp should be configured, and base interface is in place also.

after upgrade, license file need to install again
````
#/opt/xcat/share/xcat/scripts/configonie --switches mid08tor10 --license licensefile.txt
#xdsh mid08tor10 "systemctl restart switchd;ifreload -a"
````
