### ISSUE TITLE
If service node is down, control to OpenBMC node never returns

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#3888]
I use never, but I didn't wait forever for this command to come back, maybe 2-3 minutes before I `ctrl-c` out.  

```
[root@briggs01 ~]# rpower mid05tor12cn02 state
^C^C^C
```

turns out the service node is not installed and in anaconda...
```
[root@briggs01 ~]# ssh sn02
ssh: connect to host sn02 port 22: Connection refused
```

Changing to a responding service node resolves it...
```
[root@briggs01 ~]# chdef mid05tor12cn02 servicenode=fsn01
1 object definitions have been created or modified.

[root@briggs01 ~]# rpower mid05tor12cn02 state
mid05tor12cn02: [openbmc_debug] curl -k -c cjar -H "Content-Type: application/json" -d '{ "data": ["root", "xxxxxx"] }' https://172.12.140.102/login
mid05tor12cn02: [openbmc_debug] login_response 200 OK
mid05tor12cn02: [openbmc_debug] curl -k -b cjar -X GET -H "Content-Type: application/json" https://172.12.140.102/xyz/openbmc_project/state/enumerate
mid05tor12cn02: [openbmc_debug] rpower_status_response 200 OK
mid05tor12cn02: off
```

I thought there was something added @xuweibj to time out...?? Maybe in this case it's something inside xCAT that holds up the service node communication?

**Comment by xuweibj** [comment]
I tried to reproduce this issue, but I got the response quickly.
```
[root@briggs01 ~]# time rpower mid05tor12cn02 status
Error: Unable to dispatch hierarchical sub-command to sn02:3001.  Error: Connection failure: IO::Socket::INET: connect: No route to host at /opt/xcat/lib/perl/xCAT/Client.pm line 248.
.

real	0m3.290s
user	0m0.087s
sys	0m0.009s
```
Test env:
```
# rpower sn02 status
sn02: off
# lsdef mid05tor12cn02 -i servicenode -c
mid05tor12cn02: servicenode=sn02
```
Hi @whowutwut , what else should I do to reproduce it?

**Comment by zet809** [comment]
Hi, @whowutwut , can we close this issue if it can not reproduced?

**Comment by immarvin** [comment]
hi @whowutwut , I made some investigation on this, I guess the root cause is like this:
during redhat provision, a process will open a tcp socket on 3001 in %pre section of anaconda to process the debug commands sent by "runcmdinstaller", so when the xcatd on mn  forward a request to the provisioning service node, the 2 sides of the socket  cannot understand each other and cannot respond correctly.

@xuweibj will do some work to confirm whether this is the real root cause

we might need to discussion on which port should be used and list all the ports used by xcat in the doc, since issuing the commands to cn during service node provision is a rare case, is it to move this to 2.13.8?

**Comment by zet809** [comment]
Move to 2.13.8 to fix this issue.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/4083

**Comment by immarvin** [comment]
hi @whowutwut ， can this issue be closed?

**Comment by zet809** [comment]
Hi, @whowutwut , in PR #4083, @immarvin have modified the port 3001 to 3054 to work around this problem so, shall we close this defect? Thx!

**Comment by whowutwut** [comment]
@immarvin @zet809 Sorry for the delay, lets close this and if further issues arise, we can open another issue
