### ISSUE TITLE
［FVT］Uncompleted pages in documentation

### ISSUE THREAD

**Issue by caomengmeng** [xcat2/xcat-core#392]
# Uncompleted Docs
1. Link:  https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/x86_64/index.html
   Description: Pages in this section are all not completed. Click next one page after another, then you can see all till page: https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/x86_64/virtual_machines/index.html
2. Link: https://xcat-docs.readthedocs.org/en/latest/guides/admin-guides/manage_clusters/ppc64le/diskless/customize_image/install_new_kernel.html
   Description: There is an "TODO“ to complete.
   Already comfirmed with @tingtli, this is just listed here and mark it in this issue.
3. Link: https://xcat-docs.readthedocs.org/en/latest/advanced/hierarchy/configure_dhcp.html
   Description:
   Failed to link doc for 
   XCAT_pLinux_Clusters/#configure-dhcp
   Confirmed with Cheng Long, there isn't this content in doc now
# Docs Need be Moved from SF
## High Priority
1. Planning xCAT (Hierarchy and HA)
   https://sourceforge.net/p/xcat/wiki/XCAT_Overview%2C_Architecture%2C_and_Planning/#xcat-planning
2. xCAT Redbooks and Papers
   https://sourceforge.net/p/xcat/wiki/XCAT_Redbooks_and_Papers/
3. BootTarget
   https://sourceforge.net/p/xcat/wiki/BootTarget/
4. Support HMC based PowerVM Server
   https://sourceforge.net/p/xcat/wiki/XCAT_System_p_Hardware_Management_for_HMC_Managed_Systems/
5. Support x86_64
   https://sourceforge.net/p/xcat/wiki/XCAT_iDataPlex_Cluster_Quick_Start/
6. Advanced Topics for x86_64
   https://sourceforge.net/p/xcat/wiki/XCAT_iDataPlex_Advanced_Setup/
7. Configure syslog and auditlog on xCAT MN
   https://sourceforge.net/p/xcat/wiki/Syslog_and_auditlog/
8. Configure NTP
   https://sourceforge.net/p/xcat/wiki/Setting_up_NTP_in_xCAT/
9. Configure IPv6
   https://sourceforge.net/p/xcat/wiki/Configuring_IPv6_in_xCAT_Cluster/
10. Manage MN itself
    https://sourceforge.net/p/xcat/wiki/Managing_the_Management_Node/
11. Backup and Restore xCAT MN
    https://sourceforge.net/p/xcat/wiki/xCAT_Mgmt_Node_Backup_and_Restore/
12. xCAT Support page in IBM web site
    Buy an 'xCAT Support Contract' from IBM through 'Passport Advantage'.
    http://www-03.ibm.com/systems/technicalcomputing/xcat/support.html
    http://www-01.ibm.com/software/passportadvantage/paselectedsupportprograms.html#xcat
13. xCAT Customer list (Not sure all of them can be published.)
    https://sourceforge.net/p/xcat/wiki/Xcat_users/
## Low Priority
1. xCAT Monitoring
   https://sourceforge.net/p/xcat/wiki/Monitoring_an_xCAT_Cluster/
2. Vmware Support
   https://sourceforge.net/p/xcat/wiki/XCAT_Virtualization_with_VMWare/
3. Xen Support
   https://sourceforge.net/p/xcat/wiki/XCAT_Xen/
4. zVM Support
   https://sourceforge.net/p/xcat/wiki/XCAT_zVM_Setup/
5. HP server Support
   https://sourceforge.net/p/xcat/wiki/XCAT_Linux_Cluster_on_HP_Hardware/

**Comment by daniceexi** [comment]
@caomengmeng Thanks. We will keep this issue to track the uncompleted doc pages for RTD

**Comment by cxhong** [comment]
completed item 3 on pull request #403

**Comment by whowutwut** [comment]
@chenglch  for item 8 above, I think we should remove this entire appendix page.  Right now it says that in order to migrate Mgmt Node -> Service Node you have to work with the xCAT Team.  If that is the solution, then we should not even document this scenario until we have a defined step to migrate Mgmt Node to Service Node.

**Comment by whowutwut** [comment]
@caomengmeng  why is this moved to 2.12, I think we should attempt to finish a few in the 2.11 time frame...

**Comment by caomengmeng** [comment]
@whowutwut  As we discussed in daily meeting, it should be moved to 2.12 if can't complete all.
But in this morning meeting, @bybai is looking at them one by one now to determine which will be added to 2.12 sprint7 job list.

**Comment by whowutwut** [comment]
Thanks, I think if it's NOT necessary for 2.11 GA, we should not rush to get the documentation over to RTD just to get the work done...  I think this is a good opportunity to refine the documents and improve the clarity... I think the past few pull requests have been rushed into the docs and now we lose the ability to take our time to make it better...    I think we have many pages that are still very confusing for the user.   I am looking at the install guide to make some quick start guides right now....

* the softlayer item should be moved to 2.12 because I think this should only be moved if we have some time to verify the steps
* Docker support can wait until we have a better integration
* ports --- do we even need this? Is any user even looking at it? 
* zones - i actually want @pdlun92  to look into the ssh zones and learn that since Lissa left, I think this would be good opportunity to re-write that section to something easy to understand. 

....

**Comment by dletai** [comment]
Not sure if this belongs here or as a new issue - an xcat-doc repository on github seems to be missing.
https://xcat-docs.readthedocs.org/en/2.11/help.html
has as 3rd link:
https://github.com/xcat2/xcat-doc/issues
but github/xcat2/xcat-doc doesn't seem to exist

Another issue - it used to be possible from sf to download entire docs as html tar but on rtd I can't find this capability anymore. How can I download docs for offline (no net connection) installations?
An rpm of the docs (as is done by slurm) would be very convenient.

**Comment by whowutwut** [comment]
@dletai, thanks for pointing out that broken link. I will fix it. Next time you can feel free to open another issue 

As for downloading the doc, ReadTheDocs provides this functionality.  In the lower left corner of read the docs you can click on the bar that has version  2.11. It brings up a small context window where you can download the PDF or HTML copy for offline viewing

**Comment by whowutwut** [comment]
Probably need to rethink this issue or open smaller issues, this one risks never being completed and pushed out forever.

**Comment by zet809** [comment]
Let's close this issue and open when we encounter issues for document.
