### ISSUE TITLE
Switch-based node discovery failed on cumulus switch

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat-core#4007]
For a cumulus switch haven't have ssh passwordless configured, our current code logic will fail to get mac table from it. 

Our code will use command `ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no c685f2u26vc 'bridge fdb show|grep -i -v permanent|tr A-Z a-z  2>/dev/null' 2>/dev/null` to get mac table from cumulus switch.
```
# ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no c685f2u26vc 'bridge fdb show|grep -i -v permanent|tr A-Z a-z  2>/dev/null' 2>/dev/null
```
But when using this command with xcat subroutine 'runcmd', `2>&1` will be appended to the command above and will cause the command have output like below:
```
# ssh -o StrictHostKeyChecking=no -o PasswordAuthentication=no c685f2u26vc 'bridge fdb show|grep -i -v permanent|tr A-Z a-z  2>/dev/null' 2>/dev/null 2>&1
Permission denied (publickey,password).
```
Then, the `refresh_switch` subroutine will get nothing from the cumulus switches.

**Comment by immarvin** [comment]
encountered some issue on the return value of `runcmd`, in the MacMap.pm, the command is success  but `$?` and `$::RUNCMD_RC` are "-1", might be a issue in runcmd, need to take a look at this

**Comment by immarvin** [comment]
thanks for the help of @neo954 and @robin2008 , we found a fatal issue in MacMap.pm,  this pm rewrite the signal handler for SIGCHLD
````
534     $SIG{CHLD} = sub { while (waitpid(-1, WNOHANG) > 0) { $children-- } };
````
which introduced 2 problems:
1). breaks the return value of ``xCAT::Utils->runcmd()``, since `qx` relies on SIGCHLD to pass back the return value of shell commands
2)if the child processes of `refresh_switch` forks their own children process, the SIGCHLD signal will be passed upward to `refresh_switch` and break the children count down

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/4022
