### ISSUE TITLE
Support http repos for otherpkgs

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4042]
For RedHat currently, the `osimage` `otherpkgdir` only supports a single local directory.  Ideally, we would like to provide a delimited list of HTTP addresses (two requirements there: support http and support multiple entries).  `pkgdir` already supports this.

**Comment by mattaezell** [comment]
I started looking at this in depth last night, and it's actually fairly complicated.  There's currently support so that if you point to an `otherpkgdir` that has subdirectories, it will create repo entries for each subdirectory.  Then, as xCAT is going through the different `pass`es (if you have `#NEW_INSTALL_LIST#`) it will enable only the repos that are relevant for that `pass`.  Is that complexity actually needed?

When we support multiple on-disk directories, we don't know which one has the packages we need unless we go inspect the contents (we really don't want to do that).  Then with HTTP repos, we have even less chance of knowing.

Would it be OK to just leave *all* the repos enabled for all `pass`es?

**Comment by bybai** [comment]
Hi, Matt,
 
For on-disk rpm/deb packages:
There is kit mechanism in xcat to simplify install differently software stack in multiple sub-directories/otherpkglist, doc link: http://xcat-docs.readthedocs.io/en/latest/advanced/kit/index.html
 
If you want to manually install different rpm/deb packages through on-disk multiple sub-directories in otherpkgdir, the basic doc is : http://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/common/deployment/additionalpkg/nonubuntu_os_other_pkg.html?highlight=otherpkgdir and http://xcat-docs.readthedocs.io/en/latest/guides/admin-guides/manage_clusters/common/deployment/additionalpkg/ubuntu_os_other_pkg.html?highlight=otherpkgdir
 
If you want to use advanced configuration like `#NEW_INSTALL_LIST#`, `#NEW_INSTALL_LIST#` means these packages use yum/zypper standalone. For exmaple, if you want to install several different versions of the same software, you can use this label for each version,  yum/zypper will install one version, then another yum/zypper will imstall another version. if you just want to install the latest software, you do not need to use `#NEW_INSTALL_LIST#`, you just need to add sub-directory/packages list into otherpkglist. And `#NEW_INSTALL_LIST#` is used by kit also,  if using kit, you do not need to manually configure otherpgkdir/otherpkglist.
 
What OS do you use?  
Usually, ubuntu uses http repo.
For redhat/sles, xcat currently support on-disk subdirectories packages repo or kit mechanism for otherpkg.
 
Best Regards--------------------------------------------------Yuan Bai (白媛)CSTL HPC System Management DevelopmentTel:86-10-82451401E-mail: bybai@cn.ibm.comAddress: IBM ZGC Campus. Ring Building 28,ZhongGuanCun Software Park,No.8 Dong Bei Wang West Road, Haidian District,Beijing P.R.China 100193IBM环宇大厦北京市海淀区东北旺西路8号，中关村软件园28号楼邮编:100193
 
 
----- Original message -----From: Matt Ezell <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [xcat2/xcat-core] Support http repos for otherpkgs (#4042)Date: Mon, Oct 16, 2017 10:42 PM 
I started looking at this in depth last night, and it's actually fairly complicated. There's currently support so that if you point to an otherpkgdir that has subdirectories, it will create repo entries for each subdirectory. Then, as xCAT is going through the different passes (if you have #NEW_INSTALL_LIST#) it will enable only the repos that are relevant for that pass. Is that complexity actually needed?
When we support multiple on-disk directories, we don't know which one has the packages we need unless we go inspect the contents (we really don't want to do that). Then with HTTP repos, we have even less chance of knowing.
Would it be OK to just leave all the repos enabled for all passes?

**Comment by immarvin** [comment]
hi @bybai , thanks for your info, it makes much clear about the usage of `#NEW_INSTALL_LIST#`, so is it intended for KIT support?

@mattaezell , yes, the logic of otherpkgs is a little complex.
````
There's currently support so that if you point to an otherpkgdir that has subdirectories, it will create repo entries for each subdirectory. 
````

what your mentioned is not true, it only create directories which are identified in otherpkglist file, for example `xcat-core/xcatsn`,  we need to add a repo to subdirectory "$otherpkgdir/xcat-core". this is because 
1. only the directory contain subdirectory "repodata" is a valid repo path for yum, otherwise, an invalid repo path will be added to /etc/yum.repo.d and it is an error while installing packages with yum commands
2. in most cases, each subset of 3rd party packages requires a individual repo, user will create a subdirectory and place the packages and repos under this dir.



in otherpkgs script. it first create the repo paths for PKGDIR, since the 3rd party packages in otherpkglist might have dependency on the packages under PKGDIR shipped by os iso, then create repo paths for subdirectories composed by otherpkgdir and otherpkglist

**Comment by bybai** [comment]
@immarvin , `#NEW_INSTALL_LIST#` is used in KIT support. We also use it in otherpkglist,  we have exposed it in our  otherpkgdir related docs.

**Comment by immarvin** [comment]
fixed in https://github.com/xcat2/xcat-core/pull/4275
