### ISSUE TITLE
Incorrect IP address for xcatmaster

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4059]
Our xcatmaster has legs into multiple networks.  xCAT uses the `my_ip_facing` subroutine to pick the appropriate IP address to talk to clients, but not for generating `mypostscript`.  That seems to just look at the `xcatmaster` attribute on the node, if it exists, or use the `master` attribute from the `site` table.  To make progress, I've just set `xcatmaster` to the alternate IP address for the groups that should use the alternate network.

Should this work 'automatically' or is this step required?

**Comment by bybai** [comment]
Hi Matt
 
The <xcatmaster> value for a node is the name of it’s server as known by the node.
By default, the node will auto use master from site table, since xcatmaster has legs into multiple networks, you should specify manually xcatmaster for the node, then the node uses the correct xcatmaster.
 
 
Best Regards--------------------------------------------------Yuan Bai (白媛)CSTL HPC System Management DevelopmentTel:86-10-82451401E-mail: bybai@cn.ibm.comAddress: IBM ZGC Campus. Ring Building 28,ZhongGuanCun Software Park,No.8 Dong Bei Wang West Road, Haidian District,Beijing P.R.China 100193IBM环宇大厦北京市海淀区东北旺西路8号，中关村软件园28号楼邮编:100193
 
 
----- Original message -----From: Matt Ezell <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [xcat2/xcat-core] Incorrect IP address for xcatmaster (#4059)Date: Sun, Oct 8, 2017 12:27 AM 
Our xcatmaster has legs into multiple networks. xCAT uses the my_ip_facing subroutine to pick the appropriate IP address to talk to clients, but not for generating mypostscript. That seems to just look at the xcatmaster attribute on the node, if it exists, or use the master attribute from the site table. To make progress, I've just set xcatmaster to the alternate IP address for the groups that should use the alternate network.
Should this work 'automatically' or is this step required?

**Comment by bybai** [comment]
Hi @mattaezell ,
xcatmaster - defines which Service Node the Compute Node should boot from and should be set to the hostname or IP address of the service node that the compute node can contact it by.  If you do not use service node and do not set xcatmaster for the compute node, the compute node will contact the master in ``site`` table, the default is xcat MN.
1, So do you use service node for this compute node ? if yes, you must use `chdef` command to add xcatmaster for this compute node or its node group, like:
```
chdef -t group -o rack1 servicenode=r1n01 xcatmaster=r1n01
```
2, if you do not use service node, the compute node is managed by MN directly, you do not need to set xcatmaster value, the compute node will contact xcat MN directly.

**Comment by robin2008** [comment]
It depends on the networking in you cluster. In current experience,  it is recommended to set `xcatmaster` explicitly for CN in large hierarchy cluster in case not be managed by an unexpected SN (for example, to reach the SN from CN need multiple switches ).

But in an small environment, the MN and SNs are peer to each other (we say it is a pool), then no need to set  `xcatmaster` for the node. the maste IP will be determined by the one who answer the bootp.
For the pool supporting, it is done in recent release to adjust the IP of master for CN, ( Now it should be `noderes.xcatmaster` > facing IP > `site.master `).  It seems `Postage.pm` is not covered by the above change.

**Comment by mattaezell** [comment]
We have explicitly assigned service nodes for our compute nodes, but this device is an ethernet switch that is on a different network from the main compute management/provisioning network.  The assumption was that we didn't need to set `xcatmaster` and it would just use the management node.  But it seems that we need to manually set the `xcatmaster` to the management node's IP address in the `netmgmt` network.  That translation (`my_ip_facing`) does not happen automatically.

**Comment by bybai** [comment]
Hi @mattaezell ,
Could you provide your related definition data from site table, node definition and networks table?
