### ISSUE TITLE
xCAT - does it plan to support VMware ?

### ISSUE THREAD

**Issue by yardan11** [xcat2/xcat-core#4108]
Hi

Does xCAT plan to have support with VMware , or only KVM ?
If yes - which versions of VMware are supported , and where i can find documentation on it ?

**Comment by whowutwut** [comment]
@bybai @immarvin can you help answer this question?

**Comment by immarvin** [comment]
hi @yardan11 , xCAT once supported ESXi , Please see  https://sourceforge.net/p/xcat/wiki/XCAT_Virtualization_with_VMWare/ for details.

Since there is no more customers request on ESXi support then, we do not verify ESXi support in each release, so the ESXi support is supposed to work but not sure.

**Comment by daniceexi** [comment]
For Exsi, 4.x 5.x and 6.x should work well.
Best Regards----------------------------------------------------------------------Wang Xiaopeng (王晓朋)
 
Manager for HPC SW Dev: xCAT, ESSL, SMI, Test
IBM China Systems Laboratory (CSL)
Tel: 86-10-82453455Email: wxp@cn.ibm.com
 
 
----- Original message -----From: yangsong <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: Re: [xcat2/xcat-core] xCAT - does it plan to support VMware ? (#4108)Date: Mon, Oct 16, 2017 9:39 PM 
hi @yardan11 , xCAT once supported ESXi , Please see https://sourceforge.net/p/xcat/wiki/XCAT_Virtualization_with_VMWare/ for details.
Since there is no more customers request on ESXi support then, we do not verify ESXi support in each release, so the ESXi support is supposed to work but not sure.

**Comment by yardan11** [comment]
Hi

Thanks i will check it in my lab.

**Comment by immarvin** [comment]
hi @yardan11 , I will close this ticket first, please reopen it when you want to keep on discussion , thanks
