### ISSUE TITLE
config networks failing when not all devices are defined in stanza.

### ISSUE THREAD

**Issue by ralphbellofatto** [xcat2/xcat-core#4116]
we have a situation where we don't want to define all the ib devices.  so we defined the following only:

```
[root@c699mgt00 ~]# lsdef c699login01 -i nicips
Object name: c699login01
    nicips.ib0=10.10.100.9
    nicips.enP48p1s0f0=129.40.234.11
    nicips.ib1=10.11.100.9
[root@c699mgt00 ~]# 
```

yet when we boot this system confignetwork shows the following error:
```
Tue Oct 17 15:45:40 EDT 2017 postbootscript custom/rh74_compute/compute.postboot return with 0
Tue Oct 17 15:45:40 EDT 2017 Running postbootscript: confignetwork
[E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for enP48p1s0f0.
[E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for ib2.
[E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for ib3.
[I]: All valid nics and device list:
[I]: ib0,ib1
[I]: NetworkManager is inactive.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
configure nic and its device : ib0,ib1
[I]: Call configib for IB nics: ib0,ib1, ports: 
[I]: NIC_IBNICS=ib0,ib1 NIC_IBAPORTS= configib
Tue Oct 17 15:46:25 EDT 2017 postbootscript confignetwork return with 1
node boot failed,reporting status...
```

```
[root@c699mgt00 ~]# lsdef c699login01 -i status,statustime
Object name: c699login01
    status=failed
    statustime=10-17-2017 16:22:34
```
[root@c699mgt00 ~]# scp c699login01:/var/log/xcat/xcat.log /tmp/c699login01.xcat.log.txt
/etc/profile.d/zlsf.sh: line 6: /shared/lsf/conf/profile.lsf: No such file or directory
xcat.log                                                               100%   15KB  15.0KB/s   00:00    

[c699login01.xcat.log.txt](https://github.com/xcat2/xcat-core/files/1392585/c699login01.xcat.log.txt)

```
Tue Oct 17 15:45:40 EDT 2017 postbootscript custom/rh74_compute/compute.postboot return with 0
Tue Oct 17 15:45:40 EDT 2017 Running postbootscript: confignetwork
[E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for enP48p1s0f0.
[E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for ib2.
[E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for ib3.
[I]: All valid nics and device list:
[I]: ib0,ib1
[I]: NetworkManager is inactive.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
configure nic and its device : ib0,ib1
[I]: Call configib for IB nics: ib0,ib1, ports: 
[I]: NIC_IBNICS=ib0,ib1 NIC_IBAPORTS= configib
Tue Oct 17 15:46:25 EDT 2017 postbootscript confignetwork return with 1
```

however we do define the fields other than the nicips field and we still get this above error.
```
[root@c699mgt00 ~]# lsdef c699login01 -i nictypes,nicnetworks | sort
Object name: c699login01
    nicnetworks.enP48p1s0f0=pub_yellow
    nicnetworks.enP48p1s0f1=xcat_util
    nicnetworks.enP5p1s0f1.4=xcat_bmc
    nicnetworks.enP5p1s0f1.5=xcat_infra
    nicnetworks.enP5p1s0f1.6=xcat_pdu
    nicnetworks.enP5p1s0f1=xcat_compute
    nicnetworks.ib0=IB00
    nicnetworks.ib1=IB01
    nicnetworks.ib2=IB02
    nicnetworks.ib3=IB03
    nictypes.enP48p1s0f0=Ethernet
    nictypes.enP48p1s0f1=Ethernet
    nictypes.enP5p1s0f1.4=vlan
    nictypes.enP5p1s0f1.5=vlan
    nictypes.enP5p1s0f1.6=vlan
    nictypes.enP5p1s0f1=Ethernet
    nictypes.ib0=Infiniband
    nictypes.ib1=Infiniband
    nictypes.ib2=Infiniband
    nictypes.ib3=Infiniband
```

**Comment by ralphbellofatto** [comment]
specifically we want to define all the values that don't change in a group and then only define the ports we actually use with an address. This used to work with confignics,

there should be a way to make it work with confignetworks, even if we would be required to do nicips.ip2=null or something to clue us that we really don't want an address right now.

**Comment by ralphbellofatto** [comment]
there is also something strange here:
```
4: enP48p1s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 98:be:94:58:5e:e0 brd ff:ff:ff:ff:ff:ff
    inet 129.40.234.11/27 brd 129.40.234.31 scope global enP48p1s0f0
       valid_lft forever preferred_lft forever
    inet6 fe80::9abe:94ff:fe58:5ee0/64 scope link 
       valid_lft forever preferred_lft forever
```

we have a definition for those fields for this one:
[E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for enP48p1s0f0.

```
Error: Could not find an object named 'c4699login01' of type 'node'.
[root@c699mgt00 ~]# lsdef c699login01 | grep enP48p1s0f0
    nichostnamesuffixes.enP48p1s0f0=-yellow
    nicips.enP48p1s0f0=129.40.234.11
    nicnetworks.enP48p1s0f0=pub_yellow
    nictypes.enP48p1s0f0=Ethernet
```

**Comment by whowutwut** [comment]
@bybai can you help take a look?

**Comment by bybai** [comment]
Hi @ralphbellofatto  and @whowutwut ,
1,
From the above description, you want to configure ib0,ib1,enP48p1s0f0, other nics do not want to configure nicips, so you do not configure them in nics table.
From the xcat.log, ib0 and ib1 are configured successfully, the return 1 is from the Error part.

So the following error messages should better be warning.
```
[E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for ib2.
[E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for ib3.
```
Since confignetwork is enhanced, `confignetwork` cannot identify if user forget configure nicios,nictypes or nicnetworks or user does not want to configure them, so we give this error messages to remind user, warning may better than error.
2,
In `confignics`, the script always return 0 in the past. Currently, both `confignics` and `confignetwork` enhance the return code, so here `confignetwork` return 1, it has error messages. 
3, 
For the strange error "Error: nicips,nictypes and nicnetworks should be configured in nics table for enP48p1s0f0.", it should not be there.
From compute node, enP48p1s0f0 is will configured, so there should not be error like that,  let me use your data try to reproduce it in my environment.

Will give your further progress later.

**Comment by bybai** [comment]
Hi @ralphbellofatto and @whowutwut ,
I tried to reproduce the strange error in above (3,), I did not reproduce it, I used the same data with your definition:
```
bybc0607: xcatdsklspost: downloaded postscripts successfully
bybc0607: Wed Oct 18 01:45:37 EDT 2017 Running postscript: confignetwork
bybc0607: [E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for enP48p1s0f1.
bybc0607: [E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for enP5p1s0f1.
bybc0607: [E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for enP5p1s0f1.4.
bybc0607: [E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for enP5p1s0f1.5.
bybc0607: [E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for enP5p1s0f1.6.
bybc0607: [E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for ib2.
bybc0607: [E]:Error: nicips,nictypes and nicnetworks should be configured in nics table for ib3.
bybc0607: [I]: All valid nics and device list:
bybc0607: [I]: enP48p1s0f0
bybc0607: [I]: ib0,ib1
bybc0607: [I]: NetworkManager is inactive.
bybc0607: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by bybai** [comment]
Hi @ralphbellofatto and @whowutwut 
Summary:
1, based on above investigate, currently, `confignetwork` work the same way with our original `confignetwork` design; 

2, about your confusion and requirements, I have 2 concerns as following for enhancements, do you give me confirmation ? 

 a. based on your example, some nics are configured but have no nicips, `confignetwork` cannot identify if it is miss configured or if it is customized, `confignetwork` return 1 and print error. In this case, if `confignetwork` print warning instead of error and return 0, does it meet your requirements?  If yes, we can add `--nonicip` to enhance `confignetwork` ignore no nicips error.

b. If you want to create configure files in CN for nics defined in nics table, and does not configure ips for these nics, for example, define  enP48p1s0f1 in nics table without nicips, after execute `confignetwork`, it create ifcfg-enP48p1s0f1 in CN. it is a different requirement from a;

a or b, which one can meet your requirements?  from your comments, `nicips.ip2=null` this one may break our some scripts or commands like `makehosts`, so  `nicips.ip2=null` cannot be a good choice. Thanks.

**Comment by ralphbellofatto** [comment]
right now the bigest problem is two fold, 1 the error is marked as [E] error,

And 2 it causes the entire script to return a 1 which results in this:

```
 lsdef c699login01 -i status,statustime
Object name: c699login01
    status=failed
    statustime=10-17-2017 16:22:34
```

This is particularly  BAD because we use this as an over status to indicate that the node came up correctly or in error.  

These messages are actually not even warnings because it is normal for systems with large number of ports are commonly not ALL configured.  As in our case with this port: enP48p1s0f0.  I would object to these being warnings because administrators should never be trained to ignore warnings.  Certainly these are not errors in this case.

so an informational message of "[I] nic enP48p1s0f0 found, but no configuration in node definition" would be a suitable reminder.

**Comment by bybai** [comment]
Hi @ralphbellofatto,
I enhance `confignetwork` in pull request #4130, I add "--noips" for `confignetwork` to control ignoring the error and print information and return code.
You can try to use the fix, and add "--noips" as the last input parameter for `confignetwork`, the output will like:
```
..........
bybc0607: xcatdsklspost: downloaded postscripts successfully
bybc0607: Thu Oct 19 02:21:04 EDT 2017 Running postscript: confignetwork
bybc0607: [I]: nic enP48p1s0f1 found, but incomplete configuration in node definition.
bybc0607: [I]: nic enP5p1s0f1 found, but incomplete configuration in node definition.
bybc0607: [I]: nic enP5p1s0f1.4 found, but incomplete configuration in node definition.
bybc0607: [I]: nic enP5p1s0f1.5 found, but incomplete configuration in node definition.
bybc0607: [I]: nic enP5p1s0f1.6 found, but incomplete configuration in node definition.
bybc0607: [I]: nic ib2 found, but incomplete configuration in node definition.
bybc0607: [I]: nic ib3 found, but incomplete configuration in node definition.
bybc0607: [I]: All valid nics and device list:
bybc0607: [I]: enP48p1s0f0
bybc0607: [I]: ib0,ib1
bybc0607: [I]: NetworkManager is inactive.
........
```

**Comment by ralphbellofatto** [comment]
how do i add a parameter to a postscript in a group?

someotherscript,confignetwork --noips,someotherscript

**Comment by bybai** [comment]
Hi @ralphbellofatto ,
You can use as following:
`somescripts,confignetwork --allownoip,somescripts`
If configure both installnic and additional nics:
 `somescripts,confignetwork -s --allownoip,somescripts`
If configure additional nics including configure IB:
`confignetwork --ibaports=2 --allownoip`

**Comment by bybai** [comment]
Hi @hu-weihua,
need add test cases for `--allownoip` for `confignetwork`.Thanks.

**Comment by ralphbellofatto** [comment]
I am not happy with this solution as 1 it is guarenteed to cause the status=fail on almost every-time we advise people they need to use confignetwork as the new way of doing things.

The error message should be changed to an informational message AND change the status of the output to 0 in this case.  As it is quite normal for devices to be found on the system and not programmed with an address.  That is not an error, but an unused device by design.

**Comment by zet809** [comment]
Hi, @bybai , pls answer @ralphbellofatto 's concerns. Thx!

**Comment by bybai** [comment]
Hi, @ralphbellofatto ,
We design `confignetwork` to check if `nicips` is configured or not based on the following 2 reasons:
1, General speaking, `confignetwork` cannot identify if `nicips` is forgot configuring by user or it is unused device by design. 
2. In the past, `confignics` and `confignetwork` always return 0, that cause some confusion from some users. When user forgot configuring `nicips`, after executing `confignetwork` or `confignics`, the nic is not configured but the script return 0, like #2797 #3794 #3429 etc.
There are lots of configurations in `nics` table, user hard to find the reason easily, so we enhance `confignetwork` and `confignics` return code, and check `nicips,nictypes,nicnetworks` to avoid user usage mistakes.

In our current enhancement, `--allownoip` is to let `confignetwork` does not check `nicips` for an unused device by design and return 0, it is a balance between hard check `nicips` or not.

Any comments are welcome, thanks.

**Comment by ralphbellofatto** [comment]
I am not finding this solution acceptable.

The addition of an un-obvious option is not a good thing.   If you need to have something where you require a user to define all devices without throwing an error then you need a way to express in the configuration that that device is not configured.

It is quite normal to have unconfirmed devices.  Requiring something explicit that tells the system this is deliberate is a much better way to go.

I can see a number of different ways of doing that without tripping over the the uses of the nicips field.

Such as the nictypes field, where one tells the system that the devices is unused.  

for example:
```nictypes.enP48p1s0f0=unused``` that could be handled in the same place that the device is
or
```nictypes.enP48p1s0f0=Ethernet:unused```  would do it.

**Comment by bybai** [comment]
Hi @ralphbellofatto ,
We think that : most of users define all confirmed devices in nics table, while they do not define unconfirmed devices in `nics` table. Or they use different groups to control confirmed devices or unconfirmed devices in `nics` table. Or they can use `--allownoip` not to check nicips. Based on these reasons, current `confignetwork` can meet the general requirements, including above your described requirement.

But I want to get further confirm about your specific requirements to make `confignetwork` more acceptable.  Do you have scenario like the following?
There is a group  defined in `nics` table for all systems, for exmaple, 5 systems, but there is one system that is unconfirmed devices, it is not ready now, may not connet the cable. For 4 confirmed systems, they should have `nicips,nictypes,nicnetworks`, for the 1 unconfirmed system, it belongs to the group, it has `nictypes,nicnetworks`, but it does not have `nicips`. In this scenario, all configurations look reasonable,  `confignetwork` should check `nicips,nictypes,nicnetworks` for 4 systems, but it is no need to check `nicips` for 1 unconfirmed system, and after `confignetwork` is executed, it should return 0. Using a label to identify confirmed and unconfirmed systems is reasonable here. Among `nicips,nictypes,nicnetworks`, the value of `nictypes` is more specific than others, it can be a choice of the label.

**Comment by ralphbellofatto** [comment]
it is quite common to have a 4 port NIC card and actually use only 3 ports, this is NOT an error, but a deliberately un-populated nic connection.

Adding a mystery flag to the config nics is exactly the WRONG way to do this.  This is NOT one system with an unconfirmed device, it is 5 systems ALL with 4 port NIC cards which we are using 3 of them.

There is no cable connected to the 4th port.  Same goes for the ib connection in this case.  

There needs to be a way to be able to have xcat properly configure setups where you don't actually use ALL ports on the card.

**Comment by robin2008** [comment]
@bybai  No need to introduce a new column for it, let's extend `nictypes` to cover the requirement of `Not-be-Configured`

**Comment by ralphbellofatto** [comment]
perfect...  that will do it. thanks.
