### ISSUE TITLE
Custom-built genesis does not contain mlx5_core

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4128]
Our service nodes have Mellanox Connect-X4 cards in Ethernet mode.  Neither the default genesis or a custom-built genesis had that driver available.  I had to manually edit the genesis `buildrpm` to add the following to the `dracut` line:
```
--add-drivers mlx5_core
```
Should `dracut` have picked this up automatically, should `buildrpm` have command line options for specifying additional drivers to include, or should the xCAT documentation explain how to modify the dracut.conf?

**Comment by whowutwut** [comment]
@zet809 can you take a look here?

**Comment by zet809** [comment]
Hi, @mattaezell , I have uploaded a new genesis-builder package onto xcat.org to include mlx5_core module. You can find it through https://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xCAT-genesis-builder-2.13.8-snap201710190001.noarch.rpm
Hi, @whowutwut , I have applied PR #4131 to include the mlx5_core,mlx5_ib driver to genesis-base, pls help to review. Thx!

**Comment by robin2008** [comment]
Although it is added by default, but @mattaezell  give an good suggestion as customer may hit other driver issue with different hardware.

**Comment by zet809** [comment]
Hi, @mattaezell , we are planing to include all the drivers installed in the kernel to be included in xCAT-genesis-base. If there is new driver installed, rebuild genesis-base will include it.

**Comment by whowutwut** [comment]
Using the latest genesis-builder here: http://xcat.org/files/xcat/xcat-dep/2.x_Linux/beta/xCAT-genesis-builder-2.13.8-snap201710190001.noarch.rpm and re-creating the genesis base, we have verified that the Mellanox adapter can be seen in the Scaling cluster.  Reference internal issue: http://github.ibm.com/DCS-research/WSC-coral/issues/411#issuecomment-3838674. 

@zet809 is there plans from your comment above to include more drivers?

**Comment by zet809** [comment]
Thx, @whowutwut 
Yes, plan to include all drivers installed on the build server to xCAT-genesis-base package.

**Comment by whowutwut** [comment]
@zet809 This specific problem opened here was resolved by your PR #4131 
And since @mattaezell is running Power9, until changes are pushed upstream, the Fedora26 version will not work.  The work around is to build xCAT-genesis-base on-site using RHEL 7.4 for PowerLE (Power9). Described here: http://xcat-docs.readthedocs.io/en/latest/references/coral/known_issues/genesis_base.html

We did forget to build xCAT-genesis-base with the changes you pushed for 2.13.8 so we need to do that...  but I think you should open another issue to track the other drivers if it won't happen anytime soon. This way we can tag this issue to 2.13.8 and track the new one for the upcoming sprints.

**Comment by zet809** [comment]
hi, @whowutwut , in PR #4281 , all the kernel modules can be included in xCAT-genesis-base, so let's move this issue to pending.

**Comment by whowutwut** [comment]
This one we should probably be able to close out, @mattaezell Did you pick up the new Genesis Builder and build the xCAT-genesis-base on site?  Will also check with LBS to verify.

**Comment by mattaezell** [comment]
Yes, we built our own genesis using the updated scripts.  Our stateless service nodes are booting from the 40G mlx cards.  Thanks!
