### ISSUE TITLE
rinstall using rpower boot on p9

### ISSUE THREAD

**Issue by markprez** [xcat2/xcat-core#4150]
[root@mgt03 ~]# rinstall f7n01 osimage=rhels7.4-ss7.DF
Provision node(s): f7n01
Command rpower boot is not supported now.
Please run 'rpower <node> off' and then 'rpower <node> on' instead.
Error: Failed to run 'rpower' against the following nodes: f7n01

**Comment by whowutwut** [comment]
@markprez Currently this function does not work because we cannot successfully ensure that a rpower reset will actually take against the OpenBMC firmware.  The power reset they support is a "warm reset", and not a "cold reset" and in our testing, doing an off/on too close together via xCAT does not ensure the power is recycled on the server because the firmware does not queue up rest calls....

@xuweibj is working on supporting a cold off, then checking the BMC, then on for xCAT's `rpower reset` call, and once that works and we can ensure the power will be cycled, we will re-enable `rinstall` which relys on this function

**Comment by immarvin** [comment]
hi @whowutwut ， can this issue be closed?

**Comment by zet809** [comment]
Let's close this since the `rpower reset/boot` have been supported in 2.13.8 release package.
