### ISSUE TITLE
Can we do any better logging for commands.log

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4173]
As I've been using the commands.log file in the past few weeks, the most important thing that I've used it for is...
* Tracking what commands were issued against a certain node (did someone power it off?, did I really reboot it..?) 
* Checking the time that it took to execute a command (for performance reasons) , if i forgot to wrap the command in `time`. 

The logging is bad in that we can't grep through the logs to find specific commands issued against a specific node.    I had to go onto a fairly large system and look for entries made against a specific node.  Since the cluster was over 100 machines in size, it took me 10 minutes just to reduce the log file down to something manageable and find the commands I was looking for. 

Some questions I have:
1. Why is the format the way it is? Is some other utility suppose to consume it in this form? 
2. Is there a way to have some setting to reduce the output?  For example, what if I don't want response?  If I do ... `lsdef` over 1000 nodes we're writing so much data into the logs.  
3. Was this done for auditing?  Are we suppose to just record the commands issued or even save all the response info?  It just seems like some level of output should be configurable... maybe it is. 

Can we start some discussion on this?

**Comment by immarvin** [comment]
hi @whowutwut , some thoughts on the questions:
1. suggest to keep the output of commands as it is for post audit and debug, make it configurable for some certain commands might introduce additional complexity for user, it is hard to decide whether the output should be preserved before user really need to look into the logs 
2. suggest to provide some helper scripts or interface to analyze clusters.log and commands.log, for example, filtering commands for specific node. The clusters.log and commands.log themselves should provide sufficient information with friendly format for the analysis tool. We should encourage user to leverage the analysis interface provided by xcat instead of looking into the logs by themselves in most cases.
3.  the time of each command should be logged, this is quite helpful for performance test in scaling env. we can also monitor the performance change on a daily basis.

pull @hu-weihua @robin2008 for the discussion

**Comment by hu-weihua** [comment]
@whowutwut, The original purpose of ``commands.log`` is to help debug and audit. So the output of command is everything.  That was why the log format was designed like this(to wholly intact show every command's output).   Soon afterwards, I thought ``ElapsedTime`` of every command maybe helpful, so I appended it after the each command output.  

The output of each command are really helpful for debug, I agree with @immarvin, it is better for us to keep the output of commands and add filter tools to resolve your problem.

**Comment by robin2008** [comment]
Logging is a key capability of a complex system, well-design, readable is a useful tool for helping debug the system issue. The focusing is easy to find the potential problem (not only for xCAT developer, but who is running xCAT)

And I think it is hard to define which log is mandatory, which logs are in trace level, and which are in INFO, but we still need rethink it from an Admin angle who is running a cluster.

**Comment by chenglch** [comment]
Maybe the script https://github.com/xcat2/xcat-core/blob/master/xCAT-probe/scripts/dbstats.py
could help summarize the command list and the elapsed time (precision: 1 second).

The format is like below, the table time is 0 as the `dbtracelevel` in site table is set to 0. If `dbtracelevel` is 0, it means that the command time is less than 1 second.

command | elapsed(precision: 1s) | get_sub_time(s) | set_sub_time(s) | del_sub_time(s) | get_sql_time(s) | set_sql_time(s) | del_sql_time(s) | build_cache(times) | cache_hit(times) | get_tables(times) | set_tables(times) | del_tables(times)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
nodeset nytperfguest[1-90]   'osimage=ubuntu16.04.1-x86_64-install-compute'(2017-10-24 23:29:18) | 17 | 0 | 0 | 0 | 0 | 0 | 0 |   |   |   |   |  
lsdef -t osimage(2017-10-24 23:29:01) | 0 | 0 | 0 | 0 | 0 | 0 | 0 |   |   |   |   |  
tabdump site(2017-10-24 23:28:39) | 0 | 0 | 0 | 0 | 0 | 0 | 0 |   |   |   |   |  
lsdef(2017-10-24 23:28:29) | 0 | 0 | 0 | 0 | 0 | 0 | 0 |   |   |   |   |

**Comment by hu-weihua** [comment]
@whowutwut, I am not sure how do you filter the command for specific node. Due to xcat support node range and group, so sometimes the specific node name won't appear in command line when customer operate it.  

And there is a trick in the code of ``commands.log``,  the intact CLI input just can be captured in xcat client side, in xcatd (server)side, the CLI input has been restructured to xml, then to a hash, so it is hard for ``commands.log`` to recombine the hash exactly same as original  CLI input, maybe the order is different, maybe the format of node range is different.  So it is hard for customer to search ``commands.log`` by using node name as key word.

**Comment by whowutwut** [comment]
@immarvin  @hu-weihua Im not objecting to the content that is saved in the logs, I'm just wondering if there's a reason for the format and whether we could more easily grep for data... 

Going back to the log, I am able to have obtained the information that I needed if I approached it differently...  I initially approached it as "How do i find all the commands that were executed on a node..."  But really, for what I was looking for, I only needed to look for `rflash` and `rpower` commands against the node and I would have found what I needed... 

```
[vhu@c910loginx01 debug_commands]$ grep c685f4n18 commands.log | egrep "rflash|rpower"
[Request]    rpower c685f4n18 status
[Request]    rpower c685f4n18 off
[Request]    rflash c685f4n18 -a '/install/Updates/PRPQ/DD21/ServerFirmware/1742b_sbepnor/obmc-phosphor-image-witherspoon.ubi.mtd.tar'
c685f4n18: rflash started, please wait...
[Request]    rpower c685f4n18 bmcreboot. <---- here
[Request]    rflash c685f4n18 -l
[Request]    rflash c685f4n18 -l
[Request]    rflash c685f4n18 -a '/install/Updates/PRPQ/DD21/ServerFirmware/1742b_sbepnor/witherspoon.pnor.squashfs.tar'
c685f4n18: rflash started, please wait...
[Request]    rflash c685f4n18 -l
```

Then go back into the commands.log file to search for the actual request and look at the response data... 

I guess this is OK and the reduction of the `getopenbmccons` messages would help reduce the size of the file too...

**Comment by immarvin** [comment]
@whowutwut ,yes,  the current format is friendly to human but not to parser, maybe a strictly defined json format will help
