### ISSUE TITLE
 `addkitcomp -n` man page need to be  updated for its extra function

### ISSUE THREAD

**Issue by wwzhubj** [xcat2/xcat-core#418]
*man addkitcomp*
   *-n|--noupgrade*
            *Allow multiple versions of kitcomponent to be installed into*
              *the osimage, instead of kitcomponent upgrade*
 In some situation, we add "-n "not for "noupgrade", but for the package installation order, which is , those packages with "-n " will be installed behind those packages without "-n".

**Comment by bybai** [comment]
manpage for "-n | --noupgrage" will be modified as:
1, Allow multiple versions of kitcomponent to be installed into the osimage, instead of kitcomponent upgrade
2, Allow these batch of kitcomponents to be installed separately, these kitcomponents will be installed behind those kitcomponents using addkitcomp without -n option

**Comment by wwzhubj** [comment]
I have verified it.
[root@c910f03c05k07 ~]# lsxcatd -v
Version 2.11 (git commit 51316df775cb2e410708aab98c3afe9c8ef6ea1d, built Thu Nov 19 03:01:29 EST 2015)
