### ISSUE TITLE
[xcattest] Test framework does not export values into environment for external scripts to pick up

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#4329]
I'm trying to write a shell script to do some testing function, however, it looks like when I pass in a config file, the values are not sent into the shell for the script to consume... 

In my testcase, I print the environment to see what I can leverage... 
```
set -x
env | grep mid05
set +x
```

When I call xcattest with the following: `xcattest -f ./briggs01/linux.conf.template -b ./UT_performance.tmp.bundle` 
```
******************************
...
Varible:
    CN = mid05tor12cn13
    MN = briggs01
******************************
```

But the result is: 
```
+ env
+ grep mid05
+ set +x
```

If i call with: `XCATTEST_CN=mid05tor12cn05  xcattest -b ./UT_performance.tmp.bundle`
Then I see it...

```
+ env
+ grep mid05
XCATTEST_CN=mid05tor12cn05
+ set +x
```

So how to external shell scripts leverage the framework and get values from the config?

**Comment by hu-weihua** [comment]
@whowutwut, xcattest configuration file does not work like you expected, the attributes in ``[System]`` section is not used as  "env attribute'', they are just used to replace some key words. 
For example, if you define ``CN = mid05tor12cn13``,  when ``xcattest`` load test cases, ``xcattest`` will replace all ``$$CN`` to ``mid05tor12cn13``, then when the case run, there is no ``$$CN`` any more, there just is ``mid05tor12cn13``.  So as a workaround, when you want to pass an attribute in config file ``[System]`` section into a script, you can write like below:

```
cmd: /<your_path>/<your_script>  $$CN
check: rc==0
```

For env attribute ``XCATTEST_CN``, it is contributed by @robin2008, which avoid to prepare a config file when just need to pass one CN name to ``xcattest``. But the internal logic is the same with what described above. Just because it generate an env attribute ahead, so you can call this special attribute in your script, but there is only one such attribute (``XCATTEST_CN``)now.

**Comment by hu-weihua** [comment]
@whowutwut , if you have any suggestion about how to use ``xcattest``, feel free to let me know. thanks.

**Comment by whowutwut** [comment]
👍  Thanks for the explanation.   I am trying to write a bash script that will take in environment variables or use environment variables so that the scripts do not hard code configuration values... Are there any examples that show this?

**Comment by hu-weihua** [comment]
@whowutwut , generally, all the attribute used by test case are set in xcattest config file.
For example, if need to set ``ISO`` file for a case, it will work like below:
```
[root@MN] # cat test.conf
[System]
ISO=/xxx/rhels7.4-ppc64le-dvd1-stable.iso

[root@MN] # cat example_test_case
start:example_test_case
cmd: /tmp/example_script  $$ISO
check:rc==0
....
end

[root@MN] #cat /tmp/example_script
#!/usr/bin/bash
echo "the attribute form CLI : $1"
exit 0;

[root@c910f03c09k03 autotest]# xcattest -f test.conf  -t example_test_case
xCAT automated test started at Tue Nov 21 01:59:40 2017
....
------START::example_test_case::Time:Tue Nov 21 01:59:41 2017------

RUN:/tmp/example_script  /home/rhels7.4-ppc64le-dvd1-stable.iso [Tue Nov 21 01:59:41 2017]
ElapsedTime:0 sec
RETURN rc = 0
OUTPUT:
the attribute form CLI : /home/rhels7.4-ppc64le-dvd1-stable.iso
CHECK:rc == 0	[Pass]

------END::example_test_case::Passed::Time:Tue Nov 21 01:59:41 2017 ::Duration::0 sec------
...
```

**Comment by whowutwut** [comment]
Ok thanks
