### ISSUE TITLE
[fvt] there is "......" in the output of "rinv <> serial"

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#4399]
xcat version:
Version 2.13.9 (git commit db20025558aed1822cd8a45b81b8c3673485f043, built Tue Nov 28 21:56:18 EST 2017)

There is a "....." in the output of ``rinv <> serial`` and ``rinv <> model``

```
[root@briggs01 1742Ee]# rinv mid05tor12cn05 serial
mid05tor12cn05: SYSTEM SerialNumber : 1318C4A.........

[root@briggs01 xcat]# rinv mid05tor12cn11 model
mid05tor12cn11: SYSTEM Model : 8335-GTC........
```

**Comment by whowutwut** [comment]
@hu-weihua This is a byproduct of the backplane VPD update process to get our ITC machines to 1738+ firmware. They had a bug in their script that wrote out those, but since it's a hassle to put machines to the 9.network to fix it, we just have to ignore for now.  The machines coming out of MFG  do not have this issue.  These node will go back and get refurbished and should not contain those issues too.... 

Internal defect tracking those extra dots. 
https://w3.rchland.ibm.com/projects/bestquest/?verb=view&id=SW404220
