### ISSUE TITLE
[Epic]OpenBMC support on Python

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat-core#4553]
Move all OpenBMC support to Python code.

**Comment by whowutwut** [comment]
@xuweibj   Before we get really far into this.. 

This is really a major EPIC task...
 
* have we looked into the LWP::Parallel library and it cannot solve this problem?  I have asked this many times but no one seems to answer yes or no.. or we just want to move forward with Python to not give that a chance?  @zet809 ? 
* Is there a POC to prove that we can call Python from Perl and it works well? 

If that works, then i think the first step is to do smaller tasks and show the results in the issues that you created...  instead of "move all OpenBMC code to Python" , We need to prove that the python framework can scale before we do anything. 

For example, an idea...

1) Write a python program that just returns JSON or simply calls curl and prints out the "data"  value to stdout.  For example:  
```
[root@briggs01 State]# curl -c cjar -b cjar -k -H 'Content-Type: application/json' -X GET https://172.11.139.18/xyz/openbmc_project/state/chassis0
{
  "data": {
    "CurrentPowerState": "xyz.openbmc_project.State.Chassis.PowerState.On",
    "RequestedPowerTransition": "xyz.openbmc_project.State.Chassis.Transition.Off"
  },
  "message": "200 OK",
  "status": "ok"
}
```

2) The new xCAT Perl .pm file would call the python program and then become the JSON parser...and output would be similar to what we have today: 

```
rpower cn01 state
cn01: on 
```

This is just looking at CurrentPowerState and return `On`, don't make it very complicated. 

3) Then if that works, we make the python code handle a lot of calls in parallel and try to do `rpower p9up state`  and see if the time it take to return the results is a lot better than what we have today.

**Comment by zet809** [comment]
hi, @whowutwut , after basic reading source code of LWP::Parallel, it use similar logic (select) as HTTP::Async to deal with every http request in a single process, so, it won't be able to work better than our current framework. @xuweibj will give some simple test against LWP::Parallel.

**Comment by xuweibj** [comment]
Test steps:
1. check status of mid05tor12cn02,mid05tor12cn13 ---> on
2. rpower mid05tor12cn02 bmcreboot
3. ping 172.11.139.2 to check whether could ping again
4. if could ping again, run my script use "LWP::Parallel", just send login request

Result: (spent more than 1m to get result)
```
# perl lwpp.pm
Registering 'https://172.11.139.2/login'
Registering 'https://172.11.139.13/login'
Segmentation fault
```

Error:
Should get correct "mid05tor12cn13" result, but not. 
I think LWP::Parallel could not resolve our problem.

**Comment by whowutwut** [comment]
@zet809 @xuweibj  thank you!

**Comment by whowutwut** [comment]
Another thing I'd like to keep in the back of our minds here..  One way that I envisioned this is for the python utility to have a good user interface and option parsing and should be able to be invoked stand alone.  This addresses the following problems: 

* The utility can be separated from xCAT and live on it's own 
* Users that have 1-2 servers and do not need overhead like xCAT can get the tool by itself 
* I don't need to create unit test scripts to hit against the REST API, I can use this tool

The more we use the tool, the better it is and we are continuously testing it. 

One thing with the openbmctool is that it doesn't allow for an `--raw` option where the return is exactly the same as running a curl command in raw json...  The firmware team is very used to this output and it's better that we provide a method for displaying the json text as if we ran a curl command directly.  It also will allow us to see if xCAT code processing has issues , or the JSON data is returned with errors. 

I also suggest that we use `docopt` to make our option parsing standard and automatically created by creating a usage comment in the code. 

So.. something like this (making all this up...) for example:

Without `--raw` we would parse the output to something usable by anyone
```
# openbmc.py --node cn01 --power status 
bmc0:
    CurrentBMCState: xyz.openbmc_project.State.BMC.BMCState.Ready
    RequestedBMCTransition: xyz.openbmc_project.State.BMC.Transition.None
chassis0:
...
...
```
And with `--raw`...
```
# openbmc.py --node cn01 --power status --raw
{
  "data": {
    "/xyz/openbmc_project/state/bmc0": {
      "CurrentBMCState": "xyz.openbmc_project.State.BMC.BMCState.Ready",
      "RequestedBMCTransition": "xyz.openbmc_project.State.BMC.Transition.None"
    },
    "/xyz/openbmc_project/state/chassis0": {
      "CurrentPowerState": "xyz.openbmc_project.State.Chassis.PowerState.On",
      "RequestedPowerTransition": "xyz.openbmc_project.State.Chassis.Transition.Off"
    },
    "/xyz/openbmc_project/state/host0": {
      "AttemptsLeft": 3,
      "BootProgress": "xyz.openbmc_project.State.Boot.Progress.ProgressStages.OSStart",
      "CurrentHostState": "xyz.openbmc_project.State.Host.HostState.Running",
      "OperatingSystemState": "xyz.openbmc_project.State.OperatingSystem.Status.OSStatus.BootComplete",
      "RequestedHostTransition": "xyz.openbmc_project.State.Host.Transition.On"
    }
  },
  "message": "200 OK",
  "status": "ok"
}
```

xCAT will call the SAME code with `--raw` option... and just parse the json

**Comment by zet809** [comment]
We can use the task xcat2/xcat2-task-management#23 to trace the discussion. Close this EPIC as the sub tasks are done. Thx @xuweibj and @whowutwut
