### ISSUE TITLE
setupconserver=2 on diskless SN does not add nodes to goconserver

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#4797]
If `setupconserver=1`, xCAT will call `makeconservercf`, but if `setupconserver=2`, xCAT will just create the server configuration file without generating the node json file.  @chenglch what is the recommended way to generate the `nodes.json` file for a diskless SN on reboot?

**Comment by chenglch** [comment]
@mattaezell ， currently `setupconserver=2` do not help create the nodes file like `makeconservercf -l` which import all of the nodes managed by SN.  This may be a problem because some of nodes are not specified by the user with `makeconservercf <noderange>` command but they are imported.  If this is the only way for diskless SN, I could add it like what `makeconservercf -l` have done.

I have a question about the scenario you mentioned. Currently only `makegocons` command could help generate the server configuration (/etc/goconserver/server.conf), after restarting, this file may be lost. Is the `/etc` directory mounted? If so, the nodes json could be moved from `/var/lib/goconserver/` to `/etc/goconserver/` . If not I think we need to figure out a way to create the server configuration with remote output plugins from xcat.

**Comment by mattaezell** [comment]
We aren't persistently mounting `/var/` or `/etc` but we do have syncfiles and puppet.  I think our SN server configuration is identical, so we could probably put it in syncfiles.  If it has the xCAT tag at the top, it wouldn't be overwritten, correct?  I *could* put individual `nodes.json` files in Puppet, but that's not preferred.

I think it makes sense for the `conserver` and `goconserver` behavior to be the same on diskless SNs.  I'm not opposed to changing the `conserver` behavior because I agree it's a bit confusing.

If I run `makegocons` on a service node, what nodes will it add?  Just the nodes for that SN, or will it forward the command to the management node and out to all the SNs?

**Comment by chenglch** [comment]
Yes, if `/etc/goconserver/server.conf` has xCAT tag, it would not be overwritten. 

Run `makegocons` on SN, it would affect all of the nodes, not just the node for that SN as xcat-client would send this request to MN. `makeconservercf` also do it like this.

xCAT has done a very tricky work around https://github.com/xcat2/xcat-core/blob/master/xCAT-server/lib/xcat/plugins/AAsn.pm#L511 for conserver when starting SN, I would do something similar like this for gocons.

**Comment by neo954** [comment]
This patch was verified with the latest `goconserver` build. I will close this one.
