### ISSUE TITLE
sysclone not working on ppc64le

### ISSUE THREAD

**Issue by bolinches** [xcat2/xcat-core#4852]
The image gets captured with no issues but it cannot be deployed. It seems ppc64le is not yet supported on sysclone. I think the image should not happen on ppc64le until the sysclone deployment is implemented on ppc64le

**Comment by zet809** [comment]
hi, @hu-weihua , any comments?

**Comment by hu-weihua** [comment]
@bolinches , Thanks for using ``sysclone``. ``sysclone`` was developed few years ago, its framework can be used for different node, but need to specific coding for specific node. All supported scenario are listed in http://xcat-docs.readthedocs.io/en/latest/advanced/sysclone/sysclone.html#list-of-supported-arch-and-os.  Due to xCAT team has limited resource, unless we get business justification, we won’t assign resource for this feature right now. xCAT is an open source software, if you can contribute for this feature, we are welcome very much.
