### ISSUE TITLE
systemimager sysclone cannot install grub during provisioning RHEL 7.4

### ISSUE THREAD

**Issue by oxcart400** [xcat2/xcat-core#4970]
Node stuck at blinking cursor during reboot after provisioning with sysclone image.
Near the end of provisioning after image is copied get the message

The boot root device is /dev/mapper/system-root
grub2-install error: unknown filesystem

sed: can't read /boot/grub/menu.lst: No such file or directory
sysclone finishes and system reboots.
Then hangs at blinky cursor

Any ideas?
It would be great to get the system to pause before reboot, so I could look at the file systems.

Thanks,
cb

**Comment by whowutwut** [comment]
@hu-weihua , @immarvin  assigned this to you, not sure if you have any idea about this above issue? ☝️

**Comment by hu-weihua** [comment]
@oxcart400 , Thanks for using ``sysclone``. ``sysclone`` was developed few years ago, its framework can be used for different node, but need to specific coding for specific scenario. All supported scenario are listed in http://xcat-docs.readthedocs.io/en/latest/advanced/sysclone/sysclone.html#list-of-supported-arch-and-os.  Due to xCAT team has limited resource, unless we get business justification, we won’t assign resource for this feature right now. xCAT is an open source software, if you‘d like to contribute for this feature, we are welcome very much.
