### ISSUE TITLE
Node discovery using MAC address

### ISSUE THREAD

**Issue by techie879** [xcat2/xcat-core#5140]
Hi, 

we finally got to the point of starting to use xcat in our cluster environment.    One question that always came from other sysadmins in the team -- for node discovery, if there is a way to the MAC address of the system instead of UUID.  We have considered manual discovery for nodes  ( as we have different kinds of nodes) and having to use UUID is a bit confusing than using a MAC address and identifying a system.  Is there a way to setup node discovery using a MAC address?  What I have read so far, it is not possible to use a MAC address during discovery. 

If there is cool trick to get xcat to do this, I would love to hear from you guys. :-)

thanks.

**Comment by immarvin** [comment]
hi @techie879 , thanks for your interest on xCAT. 

on this feature request, do you mean you want to predefine MAC in node definition, then matching the nodes according to the predefined MAC and MAC discovered ? 

`we finally got to the point of starting to use xcat in our cluster environment`, do you mean you have migrated your cluster from other cluster admin tool to xCAT? would you please describe a little on the background story if convenience?  I am curious about the story here:) 

thx

**Comment by zet809** [comment]
Hi, techie879
 
Glad to hear the news that you choose xCAT for your cluster setup. And try my best to understand your question.
If you know the mac address of your nodes, you can define it directly as a node object in xcatdb following the document http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/discovery/manually_define.html
 
And xCAT also support auto discovery based on Machine Type/Mode of the physical server and switch, switch port the physical server is connected to. http://xcat-docs.readthedocs.io/en/stable/guides/admin-guides/manage_clusters/ppc64le/discovery/index.html have more information.
 
Pls feel free to let us know if there is any more questions.
 
Thx!
Best Regards,-----------------------------------Zhao Er TaoIBM China System and Technology Laboratory, BeijingTel:(86-10)82450485Email: ertaozh@cn.ibm.comAddress: 1/F, 28 Building,ZhongGuanCun Software Park,No.8 DongBeiWang West Road, Haidian District,Beijing, 100193, P.R.China
 
 
----- Original message -----From: techie879 <notifications@github.com>To: xcat2/xcat-core <xcat-core@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Subject: [xcat2/xcat-core] Node discovery using MAC address (#5140)Date: Wed, Apr 25, 2018 3:51 PM 
Hi,
we finally got to the point of starting to use xcat in our cluster environment. One question that always came from other sysadmins in the team -- for ode discovery, if there is a way to the MAC address of the system instead of UUID. We have considered manual discovery for nodes ( as we have different kinds of nodes) and having to use UUID is a bit confusing than using a MAC address and identifying a system. Is there a way to setup node discovery using a MAC address? What I have read so far, it is not possible to use a MAC address during discovery.
If there is cool trick to get xcat to do this, I would love to hear from you guys. :-)
thanks.

**Comment by zet809** [comment]
hi, @techie879 , any updates?

**Comment by techie879** [comment]
Hi Guys, 
Sorry, I could not get to this earlier. 

So, here is an update.  We have worked around the problem with manual discovery with our current wrapper script to provision a node.  We introduced a wrapper script that would allow other admins to quickly run the script to provision a node, update a node, remove a node from xcat, etc. . As we cant do MTMS discovery and switched-based discovery, we have to use the manual discovery.  But as I indicated using UUID is confusing to us when there is a situation where we have more than 1 node wake up and waiting to be discovered and we don't know which node is what (physically).  

Also, there is another issue that we have noticed with the UUID discovery method.  The issue is -- UUID is generated off the serial # of a node.  If for some reason, there is no serial number, UUID shows up as  0000-000-0000-000 , all zeros.:-) .  This can happen after a systems BIOS update, where the serial # was wiped out or it did not get put back.  To solve the issue, we have to put the serial # back in or make up a serial # to get the system to show a UUID -- so we can provision the node.

So, I have a request :-) .  Please give us an optional feature that we can discover a node with its MAC address, along with the UUID method.  This will help in a great deal.  Currently, ROCKS software have this and it actually is an excellent feature set.  That way, regardless of the UUID, we can easily ID a system with a MAC address and discovery could be done just as it was doing with UUID.  The way ROCKS does it is this -- ROCKS shows a MAC address waiting to be discovered and once the user hits the RETURN key, it moves on.

Thanks!

**Comment by immarvin** [comment]
hi @techie879 , what ROCKS does is keep on listening  DHCP discover/request on the MN's NIC in the provision network, the server will send out dhcp discover packets on power on, the mac and other information in the dhcp packet will be parsed, then insert the node definition including the mac info as well as other useful information in dhcp packet into DB. this method is simple, but have some restricts, such as the nodes to discover should be in the same L2 network, no more information will be obtained except the information included in dhcp packet, easy to be polluted by devices or NICs which are connected in provision network

**Comment by zet809** [comment]
Reference #5428
