### ISSUE TITLE
Goldenimage + Sysclone image CentOS 7.3.1611/ CentOS 7.4.1708 not booting

### ISSUE THREAD

**Issue by pharthiphan** [xcat2/xcat-core#5301]
Hello,

After completion of the sysclone, Centos 7 is not booting into OS while trying to boot from HDD only the cursor blinks are seen. Please find the details below and also some screenshots while cloing.

Virtual Box Version: Version 5.2.12 r122591 (Qt5.6.2)
Management Node OS Version : CentOS 7.4.1708
Management Node Kernel Version : 3.10.0-693.21.1.el7.x86_64
xCAT Version : 2.14.1
Golden osimage Version : CentOS 7.3.1611/ CentOS 7.4.1708
![1](https://user-images.githubusercontent.com/18302174/41632106-f031393c-7455-11e8-8b5d-ee4602861c4e.PNG)
![2](https://user-images.githubusercontent.com/18302174/41632107-f083cecc-7455-11e8-92ff-261fdd6c0813.PNG)

**Comment by pharthiphan** [comment]
@hu-weihua @immarvin I have tested this on CentOS 7.0 also and ended up exactly same error as CentOS 7.4

**Comment by hu-weihua** [comment]
@pharthiphan , Thanks for using ``sysclone``. ``sysclone`` was developed few years ago, its framework can be used for different node, but need to specific coding for specific scenario. All supported scenario are listed [here](http://xcat-docs.readthedocs.io/en/latest/advanced/sysclone/sysclone.html#list-of-supported-arch-and-os) and the development environments all based on physical machine, **not support virtual machine**.  Due to xCAT team has limited resource, unless we get business justification, we won’t assign resource for this feature right now. xCAT is an open source software, if you would like to contribute for this feature, we are welcome very much.

**Comment by pharthiphan** [comment]
@hu-weihua I tried this on physical machine [supported scenario as per the URL], I get the following error

![physical machine](https://user-images.githubusercontent.com/18302174/41701870-b0094ccc-754b-11e8-9ddb-5f7b43b0fc6f.png)

sysclone such as nice feature that xCAT has, some help on issues on the tested scenario as per the URL will be a great help to keep it alive and usable.

**Comment by pharthiphan** [comment]
On the virtual machine I was able to fix this by changing the 

/install/sysclone/scripts/post-install/15all.configefi

line number 90
                                #grub2-install -s --recheck $boot_device
                                grub2-install --force /dev/sda

everytime /install/sysclone/scripts/post-install/15all.configefi gets regenerated while running nodeset

**Comment by coengineer** [comment]
Hello 
Is there anybody here to help about how to make Centos 7.4  golden image using syscloning on xCAT 2.15?
