### ISSUE TITLE
Goldenimage + Sysclone /dev/sda3 has unsupported feature(s) : 64 bit

### ISSUE THREAD

**Issue by pharthiphan** [xcat2/xcat-core#5302]
Hello,

I am getting the following error while booting after been successfully sysclone. What could be possibly wrong ?

warning bad format on line 1 of /etc/fstab
/dev/sda3 has unsupported feature(s) : 64 bit
e2fsck get a newer version of e2fsck!

Virtual Box Version: Version 5.2.12 r122591 (Qt5.6.2)
Management Node OS Version : CentOS 7.4.1708
Management Node Kernel Version : 3.10.0-693.21.1.el7.x86_64
xCAT Version : 2.14.1
Golden osimage Version : CentOS 6.9 

![after syslone - centos6 9](https://user-images.githubusercontent.com/18302174/41632143-18a5c1ee-7456-11e8-9887-26d7e2d2ee54.PNG)
![fstab](https://user-images.githubusercontent.com/18302174/41632161-28dec70e-7456-11e8-9e80-b5f2c0770693.png)

**Comment by pharthiphan** [comment]
@immarvin @hu-weihua I have tested this on CentOS 6.4 and ended up with exactly same error as CentOS 7.4. is this something to do with Management Node OS Version ?  For your information I am using CentOS 7.4-1708 with lastest updates

**Comment by hu-weihua** [comment]
@pharthiphan , Thanks for using ``sysclone``. ``sysclone`` was developed few years ago, its framework can be used for different node, but need to specific coding for specific scenario. All supported scenario are listed [here](http://xcat-docs.readthedocs.io/en/latest/advanced/sysclone/sysclone.html#list-of-supported-arch-and-os) and the development environments all based on physical machine, not support virtual machine.  Due to xCAT team has limited resource, unless we get business justification, we won’t assign resource for this feature right now. xCAT is an open source software, if you would like to contribute for this feature, we are welcome very much.
