### ISSUE TITLE
Command Log writer process failed

### ISSUE THREAD

**Issue by nickcevans** [xcat2/xcat-core#536]
Since updating to xcat 2.11 I have now got log files filled with the following types of errors

Dec 15 14:30:58 mgt xcat[126917]: INFO xcatd: Drop request 'tabdump site ' output due to connection with 'Command log writer' process failed

It doesn't seem to have any effect on the output of things like tabdump but this didn't happen on xcat 2.10

If there is anything else you need let me know
Nick

**Comment by hu-weihua** [comment]
hi @nickcevans ，from xcat2.11, xcat offer a new feature called "command log", this feature will record all commands issued by customer and their output to a log file ``/var/log/xcat/commands.log``.  this feature is used to do trouble shooting. So xcat will have one more process called ``Command log writer`` from xcat2.11 

     [root@ xcat]# ps axu|grep xcatd ``Command log writer``
     root     13186  0.0  1.0  55296 44480 ?        Ss   Nov05   0:08 xcatd: SSL listener
     root     13187  0.0  1.0  56704 44992 ?        S    Nov05  28:36 xcatd: DB Access
     root     13188  0.0  1.0  54912 42048 ?        S    Nov05  11:44 xcatd: UDP listener
     root     13189  0.0  1.0  54912 41984 ?        S    Nov05   0:00 xcatd: Discovery worker
     root     13190  0.0  0.9  54784 40704 ?        S    Nov05   0:00 xcatd: install monitor
     root     13191  0.0  1.0  55296 43968 ?        S    Nov05   0:00 xcatd: Command log writer
     root     18426  0.0  0.0 104768  2688 pts/0    S+   01:43   0:00 grep xcatd

You can find this feature in xcat2.11 release notes.
https://github.com/xcat2/xcat-core/wiki/XCAT_2.11_Release_Notes

Due to this new feature is a auxiliary tool，if  ``Command log writer`` process is stopped by any accident, the xcat main function should not been effected. that's why you found "Command log writer' process failed" but "It doesn't seem to have any effect on the output of things".

If you want to know why "Command log writer' process failed" ,  you will find it out  through the log where you got the information you posted above.  if there are too many information, using filter maybe help

    cat <logfile> |grep -i "command log"

If you can't find it out, could you give me more information about your environment or give me more log. I can't tell you why command log process failed directly depending on your limited information posted above.

**Comment by nickcevans** [comment]
Thank you very much for the response and the pointers of where to look for the problem.
After some digging I found that the problem was due to our previous instance writing xcat logs to /var/log/xcat

This meant that there was no /var/log/xcat folder to start a commands.log file in. after moving the xcat log file out of the way and creating the /var/log/xcat folder, the INFO messages stopped appearing and I can now see the start of the commands log file.

Thanks
