### ISSUE TITLE
otherpkgs issue

### ISSUE THREAD

**Issue by IgorKokovkin** [xcat2/xcat-core#58]
otherpkgs postscript not installs packages from otherpkgs.repo on compute nodes.
updatenode <node_list> -P otherpks
found that first file name in a list had typo - libxlmass instead of libxlmass*
that why otherpkgs script stoped wirking and filed to the rpm install procedure instead of continue installing other packages from the list:

content of  - /install/custom/install/rh/cnode.otherpkgs.pkglist: 
  #INCLUDE:/opt/xcat/share/xcat/IBMhpc/compilers/compilers.otherpkgs.pkglist#
  #INCLUDE:/opt/xcat/share/xcat/IBMhpc/pe/pe-1200.rhels6.ppc64.otherpkgs.pkglist#
  #INCLUDE:/opt/xcat/share/xcat/IBMhpc/essl/essl.otherpkgs.pkglist#
  #INCLUDE:/opt/xcat/share/xcat/IBMhpc/loadl/loadl-5103.otherpkgs.pkglist#

content of /opt/xcat/share/xcat/IBMhpc/compilers/compilers.otherpkgs.pkglist:
  libxlmass
  xlsmp
  xlf
  vac
  xlc
 libxl

when i put * at the end of libxlmass
script installed only on file.

rpm installation also failed, that means it should be revised to.

xcat version 2.8.3(also tested 2.8.5 and .6)

**Comment by bybai** [comment]
Hi IgorKokovkin,
This file is an example file for common compiler package,since package names may change due to different version, you can customize it by yourself. 
I look at it in xcat 2.11, contents of /opt/xcat/share/xcat/IBMhpc/compilers/compilers.otherpkgs.pkglist are as following,  could you have a look at it if this one is proper for you? 

compilers/xlmass.lib
compilers/xlsmp.msg.rte
compilers/xlsmp.rte
compilers/xlsmp.lib
compilers/xlf.msg.rte
compilers/xlf.rte
compilers/xlf.rte.lnk
compilers/xlf.lib
compilers/xlf.cmp
compilers/xlf.help.pdf
compilers/xlf.samples
compilers/xlf.man
compilers/vacpp.rte
compilers/vac.lib
compilers/vacpp.lib
compilers/vacpp.rte.lnk
compilers/vac.cmp
compilers/vacpp.cmp
compilers/vacpp.help.pdf
compilers/vacpp.samples
compilers/vacpp.man
# the following packages for xlf.cmp-13.1.0.0-100630.ppc64 and vac.cmp-11.1.0.0-100630.ppc64
compilers/xlf.lic
compilers/vac.lic

**Comment by bybai** [comment]
Since IgorKokovkin had resolved his problem, /opt/xcat/share/xcat/IBMhpc/compilers/compilers.otherpkgs.pkglist in 2.11 use new package names, and currently, HPC use compiler kit to install compiler, set this defect state as pending.
