### ISSUE TITLE
Bootloader pxe/xnba cannot boot node to local disk after OS deployment (x86_64)

### ISSUE THREAD

**Issue by JimmyMa** [xcat2/xcat-core#580]
After run the "nodeset $NODE_NAME boot", the DHCP lease info is still in /var/lib/dhcp/dhcpd.leases

Below are the steps:
```
getslnodes $NODE_NAME | mkdef -z -f || echo "existed"
makehosts $NODE_NAME
makedhcp $NODE_NAME
makedns $NODE_NAME
NetBootImage="centos6.5-x86_64-netboot-compute"
nodeset $NODE_NAME osimage=$NetBootImage
rinstall $NODE_NAME
# install OS with my way
nodeset $NODE_NAME boot   #after this, the node lease infor is still in the MN.
rpower $NODE_NAME reset   #this still get booted from xCAT.
```

**Comment by daniceexi** [comment]
**nodeset <node> boot** command overwrites the xnba configuration file to be 'do nothing' so that the compute node will leave netboot and then start boot from next boot order. Generally, the net boot order will be hard disk.

So you can take a look the xnba configuration file in /tftpboot/xcat/xnba/nodes/<node> after run the **nodeset <node> boot**

**Comment by whowutwut** [comment]
@JimmyMa  FYI, I edited your post and wrapped your code steps with markdown (```) to help readability

**Comment by JimmyMa** [comment]
I googled my problem, and found this: http://sourceforge.net/p/xcat/bugs/3405/  , my problem is same with it, and the workaround in it works for me. Thanks.

**Comment by daniceexi** [comment]
@JimmyMa So the correct name for this issue should be following, right?

~~~~
Bootloader pxe/xnba cannot boot node to local disk after OS deployment
~~~~

**Comment by daniceexi** [comment]
Since we found the work around and don't plan to support it for x86_64, just close this issue as a reference.
