### ISSUE TITLE
[FVT]2.9.2 aix720 compute node:  Run postscripts=syncfiles failed for could not find ParserDetails.ini 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#587]
How to reproduce:
1.download the latest build
2.provision  compute node using xcat 2.9.2 on aix720
3.after provision
on compute node:
cat /var/log/xcat/xcat.log
--------------
 /xcatpost/startsyncfiles.aix
could not find ParserDetails.ini in /usr/opt/perl5/lib/site_perl/5.20.1/XML/SAX
---------------

**Comment by daniceexi** [comment]
This issue caused by the update of  perl XML. Then there's missing file error from ``startsyncfiles.aix``;

The fix is:

* Require to use ``XML::Parser`` in ``startsyncfiles.aix``
~~~~
use XML::Simple;
$XML::Simple::PREFERRED_PARSER='XML::Parser';
~~~~

* Install ``expat-2.0.1-2`` through install_bundler for compute nodes. It is depended by 'XML::Parser'.
