### ISSUE TITLE
xCAT upgrade from 2.10 to 2.14.5 - Centos 6.8 nodes no longer boot

### ISSUE THREAD

**Issue by kjhee43** [xcat2/xcat-core#5984]
I upgraded xCAT to 2.14.5 on a Centos6.8 management node. After the upgrade, I made some changes to the package list and regenerated and repacked the image. I rebooted on of my compute nodes and the node would not longer boot. The device DHCPs and downloads its initrd. At the point any data scrolls by on the screen too fast, but it ends with this:
 
[    6.048876] dracut: FATAL: No or empty root= argument
[    6.050124] dracut: Refusing to continue
 
 
[    6.051687] dracut Warning: Signal caught!
dracut Warning: Signal caught!
[    6.053604] dracut Warning: dracut: FATAL: No or empty root= argument
dracut Warning: dracut: FATAL: No or empty root= argument
[    6.056424] dracut Warning: dracut: Refusing to continue
dracut Warning: dracut: Refusing to continue
 
[    6.060465] init used greatest stack depth: 5196 bytes left
[    6.061927] Kernel panic - not syncing: Attempted to kill init!
 
 
Is there a change I need to make between these 2 versions in order to have the compute node boot correctly?

**Comment by immarvin** [comment]
hi @kjhee43 , ` I rebooted on of my service nodes and the node would not longer boot.`, do you mean the service node cannot boot? 

I guess this might be caused by the dhcp issue, would you please check the dhcp lease for the provision nic of the node refuse to boot? run command `/opt/xcat/share/xcat/tools/detect_dhcpd -i <the provision NIC of MN> -m <the mac address of the node refuse to boot>` and check the output

**Comment by kjhee43** [comment]
Hi, @immarvin, yes i was referring to the service node. Management node rebooted fine after xcat upgrade and all services started correctly.

It is not a dhcp issue. I stated in the initial post, the device gets an IP from DHCP correctly, It also gets its initrd correctly from the server, The issue is with the initrd I believe.

**Comment by immarvin** [comment]
is the service nodes diskless?

**Comment by kjhee43** [comment]
Yes, diskless.

-Keith

**Comment by immarvin** [comment]
did you drop into the emergency shell on panic?

**Comment by robin2008** [comment]
what's the output of `xcatprobe xcatmn`, and `xcatprobe osdeploy ...`

**Comment by kjhee43** [comment]
@robin2008 in order to have my nodes boot again i reverted back to xcat 2.10. I no longer have the xcatprobe command. I would need to re-upgrade in order to get the command. Is there any other info I can get to help with a possible before upgrading and my nodes can't boot anymore?

**Comment by immarvin** [comment]
hi @kjhee43 , the information is not enough for us to get the root cause. Please try the following steps and provide the information:

Let's define some terms:
`cn`: the node to provision 
`osimage-2.10`: diskless osimage that can be successfully provisioned with xcat 2.10
`osimage-2.14.5`: diskless osimage that failed to provision with  xcat 2.14.5

1. the node definition by `lsdef -t node -o cn`
2. the osimage definition by `lsdef -t osimage -o osimage-2.10`  and `lsdef -t osimage -o osimage-2.14.5`
3. the full console snap during the failed diskless node boot up
3.  can you provision `osimage-2.10` with xcat 2.14.5? if no, provide the difference between `osimage-2.10` and `osimage-2.14.5`, if yes, check the kernel options in network boot config file after `nodeset` under `/tftpboot`
the diskless node can be exported by  `imgexport <image_name> `  and imported by `imgimport <image bundle.gz generated by imgexport >`, no need to run `genimage` and `packimage`
4. the output of `xcatprobe xcatmn`, and `xcatprobe osdeploy ...`
5. check whether there are more than 1 dhcp server in the provision network by `/opt/xcat/share/xcat/tools/detect_dhcpd -i <the provision NIC of MN> -m <the mac address of the node refuse to boot>`

**Comment by kjhee43** [comment]
1. I can get this output with xcat 2.10 running
2. Can do first part, second will have to wait until i can upgrade again.
3. What do you mean by the full console snap? The full output of the bootup? I don't have a way to get this. The node has no serial port, is diskless, and does not drop into a shell on boot failure.
4. After upgrading the MN to xcat 2.14.5 and rebooting, the nodes booted successfully using the image created with xcat 2.10. It wasn't until the image was regenerated that boot began to fail. So yes, i can provision osimage-2.10 with xcat 2.14.5
5. Will have to wait until i can upgrade again.
6. There is only 1 dhcp server. It its the only non-diskless node in the system. DHCP has never been an issue. It always DHCPs properly.

**Comment by immarvin** [comment]
so seems the issue is caused by the fact that genimage in xCAT 2.14.5 does not work well with the service diskless osimage.  would you please provide the osimage definition? 


the full console snap mean the `rcons` output you are watching during node boot up, the following you provided is not enough.
```
[ 6.048876] dracut: FATAL: No or empty root= argument
[ 6.050124] dracut: Refusing to continue

[ 6.051687] dracut Warning: Signal caught!
dracut Warning: Signal caught!
[ 6.053604] dracut Warning: dracut: FATAL: No or empty root= argument
dracut Warning: dracut: FATAL: No or empty root= argument
[ 6.056424] dracut Warning: dracut: Refusing to continue
dracut Warning: dracut: Refusing to continue

[ 6.060465] init used greatest stack depth: 5196 bytes left
[ 6.061927] Kernel panic - not syncing: Attempted to kill ini
```

If the `site.consoleondemand` is enabled, the file can be found under `/var/log/consoles`

**Comment by kjhee43** [comment]
Site.consoleondemand is not currently enabled. What do i need to do to enabled it?

**Comment by whowutwut** [comment]
@kjhee43  

You can change the attribute using the following: 

```
# lsdef -t site clustersite -i consoleondemand
Object name: clustersite
    consoleondemand=no

# chdef -t site clustersite consoleondemand=yes
1 object definitions have been created or modified.

# lsdef -t site clustersite -i consoleondemand
Object name: clustersite
    consoleondemand=yes

```

**Comment by kjhee43** [comment]
@whowutwut i changed consoleondemand manually via tabedit (before i saw your comment) and ran a nodeset and rebooted a service node. Nothing is in /var/log/consoles. Anything else needed to make this taek effect?

**Comment by whowutwut** [comment]
@kjhee43  You need to make sure the console file is configured...   `makeconservercf <node>` .. then a file for the node should appear under `/var/log/console/<node>` ..   could you also show `lsdef <node>` so we can validate the console keywords are set correctly.  probably ipmi managed...  so may need `chdef -t node -o <node name> cons=ipmi` ..

**Comment by kjhee43** [comment]
Update on this issue:

I was finally able to upgrade again to 2.14.6 this time and run the boot again. I had options in my bootparams table that were left from 2.10 and it didn't boot immediately with 2.14.6. I cleared my bootparams table and re-ran nodeset and the nodes boot fine now. Bootparams remains empty.  

Old bootparams(from table):
imgurl=http://172.16.10.12:80//install/netboot/rhel6.10/x86_64/rhel610/rootimg.gz XCAT=fserv01:3001 NODE=ws01 FC=yes netdev=eth0 ","i915.enable_psr=0 i915.enable_ips=0 audit=1

New "bootparams"(not in table, cat /proc/cmdline):
imgurl=http://172.16.10.12:80//install/netboot/rhel6.10/x86_64/rhel610/rootimg.cpio.gz XCAT=172.16.10.12:3001 NODE=ws01 FC=yes XCATHTTPPORT=80 netdev=eth0 BOOTIF=01-94-c6-91-1d-81-f5

**Comment by kjhee43** [comment]
@immarvin, does this make sense?

**Comment by immarvin** [comment]
hi @kjhee43 , I am afraid `re-ran nodeset` fix the whole thing instead of `cleared my bootparams table `. did you rerun `nodeset` or `rinstall` in the first place? or just simply reboot the node?

**Comment by sengork** [comment]
As a remark, I've seen the same symptoms (managed Linux hardware nodes not being able to boot after the same upgrade with latest IMM2 firmware). Since the affected notes redirected SOL console from their GRUB Linux kernel boot params they failed to boot. `rcons` reported:
```
Error: Unable to establish IPMI v2 / RMCP+ session
NULL user name not enabled
```
The fix involved `tabedit ipmi` and adding "USERID" username alongside the existing password into the affected group of nodes.

Perhaps older versions of xCAT assumed "USERID" when the field was empty in ipmi table.
