### ISSUE TITLE
If set CN installation nic with static ip, the hostname of CN will be localhost, not node name

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat-core#6088]
When provision a CN, setting CN installation nic with static ip, after regular provision, the ``hostname`` of CN will be ``localhost``, not is the node name. This does not make sense.

How to reproduce:

```
[root@MN]# lsdef c910f04x37
Object name: c910f04x37
    arch=x86_64
    ip=10.4.37.1
    .....
    netboot=xnba
    nicdevices.br097=eno1
    nicips.br097=10.4.37.1
    nicnetworks.br097=10_0_0_0-255_0_0_0
    nictypes.br097=bridge
    nictypes.eno1=ethernet
    .....
    postscripts=syslog,remoteshell,syncfiles,confignetwork


   //After provision 
   # ssh 10.4.37.1
   [root@localhost ~]#

```

**Comment by immarvin** [comment]
if `confignetwork` is in postscripts, there will be no DHCP communication, so there is no chance to obtain hostname,  `confignetwork ` should cover the hostname setting in ifcfg-* files

**Comment by bybai** [comment]
@hu-weihua  and @immarvin,
`confignetwork` is used to configure secondary nics, while `confignetwork -s` will configure persistent `hostname` for ethernet install nic.
If `confignetwork -s` is in postscripts, it will configure persistent `hostname` for ethernet install nic.
@hu-weihua , Could you try to use `confignetwork -s` instead?

Since `hostname` is from DHCP communication, it is easy to lose, in general case, we can set `hostname` as persistent host name in default xCAT postscripts by default, since `confignetwork` is not xCAT default `postscripts`.

**Comment by robin2008** [comment]
@hu-weihua   Do you see that the local hostname is still missing when using `confignetwork -s`?
We may need more clear document about the hostname behavior in RTD.

**Comment by hu-weihua** [comment]
link : https://github.ibm.com/xcat2/task_management/issues/49

**Comment by bybai** [comment]
When using `confignetwork -s`, the hostname is not missing, so make clear document about the hostname behavior.

**Comment by bybai** [comment]
The doc is updated
