### ISSUE TITLE
Consider removing the exlist attribute to the "out of the box" netboot image

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#6235]
I feel like the diskless image that gets created  from copycds includes an `exlist` attribute. I used this as a starting point and working with a  customer on creating an image.  

I hit the problem where I added in  the gcc and header packages, but then on testing the image, it failed to find like  `<sys/types.h>`  and I checked the rootimg, it's there, but on the deployed image, it's not. 

I noticed right away that it's from the  exlist, but I can potentially see a new user to xCAT get hung up on this for a very  long time and not understand why the image  deployed doesn't match the image on the  MGMT  node..   Because it adds complexity and changes the result of the image  from what is intended... I think we should remove that attribute from the out of box sample

**Comment by immarvin** [comment]
For diskless node, the rootimg resides in memory, the `exlist` is there to reduce the size of the rootimg, so that:
1. less memory will be occupier by the rootimg itself, so that more memory is available to run applications
2.small size of rootimg tarball will reduce the diskless boot up time

I suggest not preserve `exlist` there as an interface to carefully tailor the diskless rootimg

**Comment by whowutwut** [comment]
@immarvin ...But this decision on cutting out those packages was made years ago, how much does it change the out of the box image that we ship? 20-100MB?  Is that size savings really  still the case today? 

I am OK for leaving in an example, commented out... so we can show users how that file will be created.   But I can probably say with high confidence that there's no customer using the sample images "out of the box" and straight into production.

So my point is that for new users, stripping out files they expect to be in the image could be a super frustrating thing for them to debug, potentially push new users off of xCAT right from the bat if they can't figure out:  "i have the rpm for the header files installed into the image, but when i boot the image, it's gone. what??"

**Comment by immarvin** [comment]
hi @whowutwut , I made a simple comparation with a base rhels7.6-alt osimage without 3rd party software packages, with and without exlist:
```
# lsdef -t osimage rhels7.6-alternate-ppc64le-netboot-compute
Object name: rhels7.6-alternate-ppc64le-netboot-compute
    exlist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.exlist
    imagetype=linux
    osarch=ppc64le
    osdistroname=rhels7.6-alternate-ppc64le
    osname=Linux
    osvers=rhels7.6-alternate
    otherpkgdir=/install/post/otherpkgs/rhels7.6-alternate/ppc64le,https://mirrors.sonic.net/epel/7/ppc64le/,ftp://abc.com/def
    permission=755
    pkgdir=/tmp/victor/rhels/7.6/rhels7.6-alt-rc1/ppc64le
    pkglist=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.pkglist
    postinstall=/opt/xcat/share/xcat/netboot/rh/compute.rhels7.ppc64le.postinstall
    profile=compute
    provmethod=netboot
    rootimgdir=/install/netboot/rhels7.6-alternate/ppc64le/compute
```

with exlist:
the compressed rootimg tarball:
```
[root@briggs01 ~]# ll -h /install/netboot/rhels7.6-alternate/ppc64le/compute/
...
-rw-r--r--  1 root root 263M May  6 23:09 rootimg.cpio.gz
```

the uncompressed rootimg  size:
```
760M	./rootimg.out/
```

without exlist:
the compressed rootimg tarball:

```
-rw-r--r--  1 root root 350M May  6 23:38 rootimg.cpio.gz
```

the uncompressed rootimg size:
```
958M	./rootimg
```

Since the compressed rootimg tarball is first  downloaded into memory, then uncompressed. so after removing exlist entries, the total memory usage will increase 300MB. And  the total download size during netbooting will increase 100MB. If we recognize this is not a big impact, I think comment out the entries by default is a good idea.

**Comment by whowutwut** [comment]
The response from the community on 7/1/19 on the user list threads...  https://sourceforge.net/p/xcat/mailman/message/36707134/ seems to indicate that a small diskless image  is still preferred... so no changes are planned for now.
