### ISSUE TITLE
Requires: conserver-xcat

### ISSUE THREAD

**Issue by mrpg99** [xcat2/xcat-core#6348]
Dear Sir/Madam,

We are trying to install xcat:

20190329.0315-core-rpms-snap.tar.bz2
together with xcat deps : xcat-dep-201905220119.tar.bz2
on rhel 7.6 server.

We have tried downloading both files and creating local repos.
and also tried the easy install script go-xcat.

Both end up with the same problem : 

Error: Package: xCAT-2.14.6-snap201903290319.x86_64 (xcat-core)
          Requires: conserver-xcat
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest

There is no package called "conserver-xcat"  that we can find.

and installing goconserver does not help

how do we fix this issue?

for now we are installing version :  2.14.5 with xcat-dep-201811190436 that still works fine without this dependency.

Br
Patric

**Comment by whowutwut** [comment]
Hi @mrpg99 

With the packages you specified, I am able to recreate your issue... Did a little digging and with PR https://github.com/xcat2/xcat-core/pull/6242 (merged in April 9, so after 2.14.6 GA) We removed the requirement of `conserver-xcat` and asking customers to use `goconserver`....

It's a utility that we ship in the xcat-depsL: 
`makeconservercf` ==> `makegoconservercf` 

`rcons` should work similar without any changes. 

I think you hit the issue because you're using an older package of xCAT (xcat-core) but then pointing a later deps which the package was removed, so it can't find the dependency....  I got this on my machine.. 

```
Error: Package: xCAT-2.14.6-snap201903290319.ppc64le (xcat-core)
           Requires: conserver-xcat
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@c910f3u25-fs4 yum.repos.d]#
```

```
[root@c910f3u25-fs4 yum.repos.d]# yum search conserver-xcat
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Warning: No matches found for: conserver-xcat
No matches found
```

But goconserver is found....

```
[root@c910f3u25-fs4 yum.repos.d]# yum search goconserver
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
============================================== N/S matched: goconserver ==============================================
goconserver.ppc64le : Independent tool to provide terminal session service.

  Name and summary matches only, use "search all" for everything.
```


I think you can resolve this by doing: 

1. Update `go-xcat` if needed
```
rm /tmp/go-xcat
wget https://raw.githubusercontent.com/xcat2/xcat-core/master/xCAT-server/share/xcat/tools/go-xcat -O - >/tmp/go-xcat
chmod +x /tmp/go-xcat
```

2. To stay on the latest GA, 2.14.6: `/tmp/go-xcat -x 2.14 install/update` 

     This will install conserver-xcat as the xcat-dep it uses still contains it

3. To go to the latest devel build:  `/tmp/go-xcat --xcat-version=devel install/update`

4. If you hit some yum issues you may  want to clean up: `yum clean all` and try again 

I'll also try and re-create on x86...  just to make sure, but let me know if it doesn't work and i'll dig around some more.

**Comment by mrpg99** [comment]
Hi,

Sorry for my late response.

@whowutwut thank you for your investigation.

Can you let me know how we download xcat-core & xcat-dep in the latest stable version manually?without using the go-xcat script? (we usually do not have internet access on the headnodes we install)

Best Regards
Patric

**Comment by cxhong** [comment]
you can download xCAT version from here:
https://xcat.org/files/xcat/

**Comment by mrpg99** [comment]
Hi,
I know where the files are located, the question was more : 
Which version of xcat-core stable, is compatible with which version of the xcat-dep package, so we dont the the dependancy problem with "conserver-xcat"

Br
Patric

**Comment by whowutwut** [comment]
Ah, ok, I see...  the core-snap in the 2.14.x_Linux would be snap builds for the follow up build of xCAT 2.14.X .. but the next planned release is xCAT 2.15. so we have not built that  since March.  That would cause the mismatch when we updated the deps later  on.   But I agree, this is a little confusing (tag @gurevichmark FYI) 

The best bet is to look at the release notes and we have links for the download-xcat: https://github.com/xcat2/xcat-core/wiki/XCAT_2.14.6_Release_Notes#download-xcat

Those combinations are tested together, they are: 
https://xcat.org/files/xcat/xcat-core/2.14.x_Linux/xcat-core/xcat-core-2.14.6-linux.tar.bz2
https://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-2.14.6-linux.tar.bz2

This combination works, I just verified by 
* wget those files... 
* `tar -xvf <file>.tar.bz2`
* `cd xcat-core ; ./mklocalrepo.sh`
* `cd ../xcat-dep/<os>/<arch>; ./mklocalrepo.sh`
* `yum -y install xCAT`

```
[root@fs2vm101 ~]# ls *.bz2
xcat-core-2.14.6-linux.tar.bz2  xcat-dep-2.14.6-linux.tar.bz2
[root@fs2vm101 ~]# sum *.bz2
54235  5057 xcat-core-2.14.6-linux.tar.bz2
61533 276560 xcat-dep-2.14.6-linux.tar.bz2
[root@fs2vm101 ~]# lsxcatd -a
Version 2.14.6 (git commit 7c787c499ebca7a98d6fcdb3577f701ac16d7ab3, built Fri Mar 29 03:19:08 EDT 2019)
This is a Management Node
dbengine=SQLite
```

**Comment by mrpg99** [comment]
Many Thanks, that combination works fine, as they are the same version.

What about if one wants to run the latest version of both packages? , i.e i tried : 
https://xcat.org/files/xcat/xcat-core/2.14.x_Linux/core-snap/20190329.0315-core-rpms-snap.tar.bz2
https://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-201906061433.tar.bz2
and that failed with the same dependancy issue.

Br
Patric

**Comment by whowutwut** [comment]
Hi @mrpg99  

The latest builds that track the master branch are actually  in the  **devel** directory, not in the `2.14.x_Linux` directory... So the one you are using the snap build is from 03/29/2019...  

From: http://xcat.org/files/xcat/xcat-core/ select the devel directory...  Then pick the latest.  We should be doing some cleanup of that directory soon as there's a lot builds in there. 
 
If you use this: http://xcat.org/files/xcat/xcat-core/devel/Linux/core-snap/core-rpms-snap.tar.bz2 that  is a symlink to  the  latest build, which is this morning's  build, or:  http://xcat.org/files/xcat/xcat-core/devel/Linux/core-snap/20190620.0621-core-rpms-snap.tar.bz2

**Comment by whowutwut** [comment]
I think this issue is resolved as it came up because of a mismatch using the latest development xcat-dep when using the snap build from a 2.14.x linux...   

If using the packages specified by the release notes, you should always  be in sync.  `go-xcat` could also pick the correct versions, instructions here: http://xcat.org/download.html
