### ISSUE TITLE
PXE installation of Centos 7.3 fails - Warning: No carrier detected on interface

### ISSUE THREAD

**Issue by leaus** [xcat2/xcat-core#6397]
I found some information.We an be fixed by configuration "rd.net.timeout.ifup=120",but I don't know where to configure it in xcat.
I tried to modify /tftpboot/xcat/xnba/nodes/nodename as "imgargs **** rd.net.timeout.ifup=120".But no work.
Do you have any similar questions, please take a look, thank you very much.

**Comment by bybai** [comment]
Hi leaus,
You can set value in your node definition attribute "addkcmdline", then execute "nodeset <nodename> osimage=<osimage>", after that, you can check your  /tftpboot/xcat/xnba/nodes/”nodename”


For example:
     chdef <nodename> addkcmdline="rd.net.timeout.ifup=120"
     nodeset <nodename> osimage=<its_osimage_name>
     cat /tftpboot/xcat/xnba/nodes/”nodename”


Please send mail by English next time, so that all xcat-core mailing list members can understand your question, thanks.






------------------ 原始邮件 ------------------
发件人: "leaus"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 晚上9:51
收件人: "xcat2/xcat-core"<xcat-core@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [xcat2/xcat-core] xnba pxe安装由于网卡dhcp超时Warning: No carrier detected on interface (#6397)




根据部分资料，需要在安装引导的内核参数中配置rd.net.timeout.ifup=120的参数，不清楚xcat中在何处添加
 手动修改/tftpboot/xcat/xnba/nodes/”nodename”中imgargs后添加参数无效。
 请问你们是否遇到过类似的问题，请帮忙看一下，非常感谢。

**Comment by bybai** [comment]
Hi leaus,
You can set value in your node definition attribute "addkcmdline", then execute "nodeset <nodename> osimage=<osimage>", after that, you can check your  /tftpboot/xcat/xnba/nodes/”nodename”


For example:
     chdef <nodename> addkcmdline="rd.net.timeout.ifup=120"
     nodeset <nodename> osimage=<its_osimage_name>
     cat /tftpboot/xcat/xnba/nodes/”nodename”


Please send mail by English next time, so that all xcat-core mailing list members can understand your question, thanks.


      Best regards,
      Bai Yuan





------------------ 原始邮件 ------------------
发件人: "leaus"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 晚上9:51
收件人: "xcat2/xcat-core"<xcat-core@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [xcat2/xcat-core] xnba pxe安装由于网卡dhcp超时Warning: No carrier detected on interface (#6397)




根据部分资料，需要在安装引导的内核参数中配置rd.net.timeout.ifup=120的参数，不清楚xcat中在何处添加
 手动修改/tftpboot/xcat/xnba/nodes/”nodename”中imgargs后添加参数无效。
 请问你们是否遇到过类似的问题，请帮忙看一下，非常感谢。

**Comment by leaus** [comment]
Thank you very much!
But the "rd.net.timeout.ifup=120" is not correct.I find the correct information.
![image](https://user-images.githubusercontent.com/35684837/62604253-39bd8f00-b92a-11e9-9e8f-f33ff04cf4bc.png)

After I configure addkcmdline="rd.net.timeout.carrier=30", it works.

**Comment by cxhong** [comment]
Thanks,  @bybai , @leaus .  I will close this issue since it has working solutions...
