### ISSUE TITLE
[FVT]: Hard disk boot failed on NextScale SLES11 SP4 after diskful installation

### ISSUE THREAD

**Issue by tingtli** [xcat2/xcat-core#674]
Test OS:  SLES11 SP4
Test xCAT version: xCAT Version 2.10 (git commit 79c7f6949c09e0b49875f10ede4b75b18ad4a0e7, built Fri Jul 24 05:27:07 EDT 2015)
How to reproduce: 
1. Define NextScale node as a compute node
2. Provision SLES11 SP4 on NextScale node
3. reboot NextScale node and find the boot failed.

Here is the output from the console
```
 System initializing
 System initializing memory
 System initializing...
 System initializing
 System initializing memory
 System initializing...
 Loading value-add drivers
 Scanning system, connecting boot device(s)






<F1> Setup<F2> Diagnostics<F12> Select Boot Device
No key pressed. Preparing to boot normally...Optimized Boot ... 11              
Boot Failed - SUSE Linux Enterprise Server 11 SP4: HD(1,GPT,E2A6F59C-6C93-4794-9B46-9FB1623565C0,0x800,0x42000)/\efi\SuSE\elilo.efi
Boot Failed - SUSE Linux Enterprise Server 11 SP4: HD(1,GPT,F245DF20-35F3-4B81-960C-9FFA6E2A6838,0x800,0x42000)/\efi\SuSE\elilo.efi
Boot Failed - PXE Network: PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Ctrl(0x1)/MAC(E41D2D796471,0x0)/IPv4(0.0.0.0,0x0,DHCP,0.0.0.0,0.0.0.0,0.0.0.0)
Boot Failed - PXE Network: PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)/Ctrl(0x2)/MAC(E41D2D796472,0x0)/IPv4(0.0.0.0,0x0,DHCP,0.0.0.0,0.0.0.0,0.0.0.0)

```

**Comment by immarvin** [comment]
this is due to incorrect firmware settings, the firmware settings versus installation mode is:

installllation mode---BootModes.SystemBootMode-------Bootorder.Bootorder-----Mode
Legacy----------------Legacy-----------------------------------X-----------------------------Legacy
Legacy----------------UEFI--------------------------------------with "legacy only"---------Legacy
Legacy----------------UEFI--------------------------------------without "legacy only"-----Fail
UEFI-------------------Legacy-----------------------------------X-----------------------------Fail
UEFI-------------------UEFI--------------------------------------X-----------------------------UEFI

**Comment by immarvin** [comment]
Doc: https://sourceforge.net/p/xcat/wiki/XCAT_iDataPlex_Cluster_Quick_Start/#begin-installation
PR: https://github.com/xcat2/xcat-core/pull/733

**Comment by whowutwut** [comment]
@immarvin  I added the content in table format in your above post using Github Markdown, if that is OK , you can modify the post and remove the initial text based content.

**Comment by immarvin** [comment]
@whowutwut thanks, updatded

**Comment by tingtli** [comment]
Verified with autotest and close it.
