### ISSUE TITLE
enablekdump trashes the install NIC ifcfg file

### ISSUE THREAD

**Issue by mattaezell** [xcat2/xcat-core#6748]
We use `confignetworks -s` to set our boot interface as static. It seems that later `enablekdump` re-enables DHCP on that interface. Is there any reason for that?

I think this was actually the root cause for #1972

**Comment by cxhong** [comment]
We couldn't think any reason why `enablekdump` postscripts re-enables to DHCP .
this code is wrote since  2012.    I think i will like to make changes and keep boot interface as is.

**Comment by bybai** [comment]
@mattaezell , please check if NetworkManager is enabled or not somewhere.

**Comment by mattaezell** [comment]
> @mattaezell , please check if NetworkManager is enabled or not somewhere.

No, we don't have NetworkManager even installed in our compute image:

```
[root@a01n01 ~]# rpm -qa|grep -i NetworkManager
[root@a01n01 ~]#
```

**Comment by gurevichmark** [comment]
@bybai Thanks for your input.
But I think the problem is in ` xcat-core/xCAT/postscripts/enablekdump`
It seems if network adapter does not start with `hf`, we set `/etc/sysconfig/network-scripts/ifcfg-` to dhcp.
![image](https://user-images.githubusercontent.com/16106630/86145699-3a708e00-bac5-11ea-906c-d0e4865bafc6.png)

We do not understand why we need to do that and are planning to remove this whole section of code so that `/etc/sysconfig/network-scripts/ifcfg-` will not be changed.
