### ISSUE TITLE
Add some basic REST API tests to daily bundle

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#6801]
Currently no REST API testcases are being run during daily or weekly regression.
Need to add some basic REST API tests to regression.
REST API documentation for reference is at https://xcat-docs.readthedocs.io/en/stable/advanced/restapi/index.html

There some testcases already written in `testcases/restapi`, but those testcases use `restapitest` script, which appears to be broken. 

This issue should either fix `restapitest` script so that existing testcases can be called from the regression bundles (used to work at some point #5143). Or add a set of simpler testcases to call `curl` directly or `xCAT-server/xCAT-wsapi/xcatws-test.pl` script and not use `restapitest` script.

If latter is chosen, the following probably needs to be done:

- [ ] New `[Table_passwd]` entry in `default.config` file:
```
key = xcat
password=cluster
username=root
```

- [ ] Since the target of REST API is a MN, the new testcases should be called after `go-xcat` testcases, which set up MN on target CN.

- [ ] New testcase file should be created for the new testcases in `xCAT-test/autotest/testcase/restapi/<object>` to separate them from existing ``restapitest` testcases

- [ ] Setup of target CN should include 
```
yum install mod_ssl
service httpd restart
```

- [ ] For simplicity use `root` userid

**Comment by peterwywong** [comment]
Mark, restapitest is broken as you said.

The clearly broken subroutine is parse_json which ia a recursive subroutine and parses the JSON output.

Syntax errors on regular expressions are hit right away and restapitest cannot be used. Since it is expected to be working, it should be fixed. It will take time to study the code and make corrections.

Right now, I am able to use "curl -X GET" to retrieve xCAT objects. For examples:

xdsh $$CN "curl -X GET --cacert /root/ca-cert.pem 'https://fs2vm114/xcatws?userName=$$username&userPW=$$password'"

fs2vm115: ["globalconf","groups","localres","networks","nodes","osimages","policy","services","tables","templates","tokens"]

Note that services, tables, templates and tokens do not seem to contain information.

xdsh $$CN "curl -X GET --cacert /root/ca-cert.pem 'https://fs2vm114/xcatws/nodes/fs2vm115?userName=$$username&userPW=$$password'"

fs2vm115: {"fs2vm115":{"updatestatustime":"08-02-2020 22:33:51","status":"booted","mac":"42:fc:2a:19:df:b4|42:c5:18:30:0e:0d!*NOIP*","serialspeed":"115200","monserver":"fs2vm114","vmnics":"br0,br1","netboot":"grub2","updatestatus":"synced","serialport":"0","postscripts":"syslog,remoteshell,syncfiles","cons":"kvm","currstate":"boot","groups":"all","vmnicnicmodel":"virtio","tftpserver":"fs2vm114","statustime":"08-11-2020 17:47:57","xcatmaster":"fs2vm114","currchain":"boot","postbootscripts":"otherpkgs","profile":"compute","vmstorage":"dir:///var/lib/libvirt/images","id":"115","serialflow":"hard","arch":"ppc64le","vmmemory":"8192","mgt":"kvm","provmethod":"rhels8.1.0-ppc64le-install-compute","nfsserver":"fs2vm114","ip":"10.3.31.115","os":"rhels8.1.0","consoleenabled":"1","vmcpus":"4","vmhost":"c910f3u31-fs2"}}

"curl -x PUT" is used to modify vmmeory of fs2vm115 and create a new node definition fs2vm118.

Will work on POST and DELETE and other resources such as networks and groups.

**Comment by peterwywong** [comment]
Additional PR: Extend the REST test cases to SLES  PR #6848.
