### ISSUE TITLE
go-xcat should display the latest version of xcat-dep package in repository

### ISSUE THREAD

**Issue by gurevichmark** [xcat2/xcat-core#6868]
When running `go-xcat --xcat-version=devel update` the following is displayed:
```
xCAT Dependency Packages
========================

Package Name                Installed                      In Repository
------------                ---------                      -------------
elilo-xcat                  3.14-5                         3.14-4
fping                       (not installed)                3.10-4.el8
goconserver                 0.3.2-snap202005211628         0.3.2-snap201909161515
grub2-xcat                  2.02-0.76.el7.1.snap2019051602 2.02-0.76.el7.1.snap2019051602
ipmitool-xcat               1.8.18-3                       1.8.18-2
net-snmp-perl               5.8-10.el8                     5.8-10.el8
perl-AppConfig              (not installed)                1.71-13.el8
perl-Crypt-CBC              2.33-20.el8                    2.33-20.el8
perl-Crypt-Rijndael         1.13-10.el8                    1.13-10.el8
perl-Crypt-SSLeay           0.72-20.el8                    0.72-20.el8
perl-Digest-SHA1            2.13-23.el8                    2.13-23.el8
perl-Expect                 1.35-6.el8                     1.35-6.el8
perl-HTML-Form              6.03-19.el8                    6.03-19.el8
perl-HTTP-Async             0.30-2                         0.30-2
perl-IO-Stty                0.03-21.el8                    0.03-21.el8
perl-IO-Tty                 1.12-13.el8                    1.12-13.el8
perl-JSON                   2.97.001-4.el8                 2.97.001-2.el8
perl-Mail-Sender            0.903-7.el8                    0.903-7.el8
perl-Net-HTTPS-NB           0.14-2                         0.14-2
perl-Net-Telnet             3.04-9.el8                     3.04-9.el8
perl-SOAP-Lite              (not installed)                1.27-3.el8
pyodbc                      (not installed)                3.0.7-1.el8
syslinux-xcat               3.86-2                         3.86-2
xCAT-genesis-base-ppc64     2.14.5-snap201811160710        2.14.5-snap201811160710
xCAT-genesis-base-x86_64    2.14.5-snap201811190037        2.14.5-snap201811190037
xnba-undi                   1.0.3-131028                   1.0.3-131028
yaboot-xcat                 1.3.17-rc1                     1.3.17-rc1

xCAT is going to be updated.
Continue? [y/n]
```

Some packages in the `In Repository` column are older than the ones in `Installed` column. 
This is because `go-xcat` uses `dnf repoquery ` command to get a list of packages and then picks the first entry in that list, sometimes resulting in wrong package version to be displayed. (In the output above, they are `elilo-xcat`, `goconserver`, `ipmitool-xcat`, `perl-JSON`)
`go-xcat` should sort the list returned from `dnf repoquery` and display all packages found in the repository.
An additional improvement would be to identify which package has all of its dependencies met, and only display that package.

**Comment by peterwywong** [comment]
I have the following observations and questions based on fs2vm104 which runs RHEL 8.1 and xCAT 2.16.1.

go-xcat is modified and print out the result of "dnf repoquery -q --qf '%{name} %{version}-%{release}'" and the following for loop:
```
for i in "${!name[@]}"
do
         if [[ "$1" = "${name[i]}" ]]
         then
                 echo "i=$i -- ${name[i]} -- ${ver[i]}" >> /tmp/ALL
         fi
    . . .
done

i=1 -- elilo-xcat -- 3.14-4
i=2 -- elilo-xcat -- 3.14-5
i=3 -- fping -- 3.10-4.el8
i=4 -- goconserver -- 0.3.2-snap201909161515
i=5 -- goconserver -- 0.3.2-snap202005211628
i=6 -- goconserver -- 0.3.3-snap202011021041
i=7 -- grub2-xcat -- 2.02-0.76.el7.1.snap201905160255
i=8 -- ipmitool-xcat -- 1.8.18-2
i=9 -- ipmitool-xcat -- 1.8.18-3
i=10 -- net-snmp-perl -- 5.8-10.el8
i=11 -- net-snmp-perl -- 5.8-12.el8
i=12 -- net-snmp-perl -- 5.8-14.el8
i=13 -- net-snmp-perl -- 5.8-7.el8
i=14 -- perl-AppConfig -- 1.71-13.el8
i=15 -- perl-Crypt-CBC -- 2.33-20.el8
i=16 -- perl-Crypt-Rijndael -- 1.13-10.el8
i=17 -- perl-Crypt-SSLeay -- 0.72-20.el8
i=18 -- perl-Digest-SHA1 -- 2.13-23.el8
i=19 -- perl-Expect -- 1.35-6.el8
i=20 -- perl-HTML-Form -- 6.03-19.el8
i=21 -- perl-HTTP-Async -- 0.30-2
i=22 -- perl-IO-Stty -- 0.03-21.el8
i=23 -- perl-IO-Tty -- 1.12-13.el8
i=24 -- perl-JSON -- 2.97.001-2.el8
i=25 -- perl-JSON -- 2.97.001-4.el8
i=26 -- perl-Mail-Sender -- 0.903-7.el8
i=27 -- perl-Net-HTTPS-NB -- 0.14-2
i=28 -- perl-Net-Telnet -- 3.04-9.el8
i=29 -- perl-SOAP-Lite -- 1.27-3.el8
i=30 -- pyodbc -- 3.0.7-1.el8
i=31 -- syslinux-xcat -- 3.86-2
i=32 -- xCAT-genesis-base-ppc64 -- 2.14.5-snap201811160710
i=33 -- xCAT-genesis-base-x86_64 -- 2.14.5-snap201811190037
i=34 -- xnba-undi -- 1.0.3-131028
i=35 -- xnba-undi -- 1.20.1-0
i=36 -- yaboot-xcat -- 1.3.17-rc1
```

Notice that elilo, goconserver, impitool-xcat, net-snmp-perl, perl-JSON and xnba-undi have more than one entry.

For example, elilo has two entries:

i=1 -- elilo-xcat -- 3.14-4
i=2 -- elilo-xcat -- 3.14-5

Mark, as you said, the first entry (3.13-4) is picked, so the latest version (3.14-5) is missed.

Q1: How does xCAT decide which version to install? For elilo-xcat, the latest version is installed. It is the same for ipmitool-xcat.

Q2. What is the reason the older version 3.14-4 still included in xCAT 2.16.1 and which distros would use the older version?

Q3: For goconserver, the older version 0.3.2-snap202005211628 is installed, even though a newer version 0.3.3-snap202011021041 is available. Again, how xCAT decide which one to use?

net-snmp-perl is different.

i=10 -- net-snmp-perl -- 5.8-10.el8
i=11 -- net-snmp-perl -- 5.8-12.el8
i=12 -- net-snmp-perl -- 5.8-14.el8
i=13 -- net-snmp-perl -- 5.8-7.el8

Q4: The installed version is 5.8-10.el8. Why is the latest version 5.8.14.e18 not installed?

A simple sorting of versions would return 5.8-7.e18 since "7" is right after "-". So a more detailed examination of the versions is needed. The naming conventions of different packages may pose a challenge to find out the latest versions.

xnba-undi has a similar situation.

Q5: fs2vm104 is a Power system. Why is xnba-undi installed on a Power node? Is xnba only used for x86 systems?

**Comment by peterwywong** [comment]
Mark, thanks for the following explanation:

"go-xcat --xcat-version=devel update" creates xcat-core.repo and xcat-dep.repo under /etc/yum.repos.d. These two files contain paths to access packages, locally or remotely (https://). And the actual packages are then put in /install/xcat for further processing.
"yum install" installs packages stored in /install/xcat. 

The following shows what "yum list" returns.
```
yum list elilo-xcat
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Last metadata expiration check: 1:07:19 ago on Mon 30 Nov 2020 06:00:52 PM EST.
Installed Packages
elilo-xcat.noarch                          3.14-5                           @xcat-dep

yum list net-snmp-perl
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Last metadata expiration check: 1:10:58 ago on Mon 30 Nov 2020 06:00:52 PM EST.
Installed Packages
net-snmp-perl.ppc64le                     1:5.8-10.el8                      @xcat-dep
Available Packages
net-snmp-perl.ppc64le                     1:5.8-14.el8                      xcat-dep
```

The "1" before ":" is the Epoch number which will be looked into.

It says Version 5.8-14.el8 is available. Does it mean this newer version will be installed or is for information purposes?

Based on this, here is the modification to function check_repo_version_dnf() in go-xcat. "yum list" is used to get version numbers. If there are more than version number returned, the one on the last line is selected.

Current:
```
if [[ "$1" = "${name[i]}" ]]
then
        echo "${ver[i]}"
        unset "name[${i}]" "ver[${i}]"
        shift && continue 2
fi
```
Experimental:
```
if [[ "$1" = "${name[i]}" ]]
then
        xyz=`yum list ${name[i]} | tail -1 | grep ${name[i]} | awk '{print $2}'`
        echo "$xyz"
        unset "name[${i}]" "ver[${i}]"
        shift && continue 2
fi
```

Here is the xCAT Dependency output of "go-xcat --xcat-version=devel update":
```
xCAT Dependency Packages
========================

Package Name                Installed                   In Repository
------------                ---------                   -------------
elilo-xcat                  3.14-5                      3.14-5
fping                       (not installed)             3.10-4.el8
goconserver                 0.3.3-snap202011021041      0.3.3-snap202011021041
grub2-xcat                  2.02-0.76.el7.1.snap2019051 2.02-0.76.el7.1.snap2019051
ipmitool-xcat               1.8.18-3                    1.8.18-3
net-snmp-perl               5.8-10.el8                  1:5.8-14.el8
perl-AppConfig              (not installed)             1.71-13.el8
perl-Crypt-CBC              2.33-20.el8                 2.33-20.el8
perl-Crypt-Rijndael         1.13-10.el8                 1.13-10.el8
perl-Crypt-SSLeay           0.72-20.el8                 0.72-20.el8
perl-Digest-SHA1            2.13-23.el8                 2.13-23.el8
perl-Expect                 1.35-6.el8                  1.35-6.el8
perl-HTML-Form              6.03-19.el8                 6.03-19.el8
perl-HTTP-Async             0.30-2                      0.30-2
perl-IO-Stty                0.03-21.el8                 0.03-21.el8
perl-IO-Tty                 1.12-13.el8                 1.12-13.el8
perl-JSON                   2.97.001-4.el8              2.97.001-4.el8
perl-Mail-Sender            0.903-7.el8                 1:0.903-7.el8
perl-Net-HTTPS-NB           0.14-2                      0.14-2
perl-Net-Telnet             3.04-9.el8                  3.04-9.el8
perl-SOAP-Lite              (not installed)             1.27-3.el8
pyodbc                      (not installed)             3.0.7-1.el8
syslinux-xcat               3.86-2                      3.86-2
xCAT-genesis-base-ppc64     2.14.5-snap201811160710     2:2.14.5-snap201811160710
xCAT-genesis-base-x86_64    2.14.5-snap201811190037     2:2.14.5-snap201811190037
xnba-undi                   1.0.3-131028                1.20.1-0
yaboot-xcat                 1.3.17-rc1                  1.3.17-rc1
```
It looks closer to what is expected.

**Comment by peterwywong** [comment]
Elapsed times for "go-xcat --xcat-version=devel update":
   Current: 16 seconds
   Experimental: 106 seconds (6.6x)

**Comment by gurevichmark** [comment]
@peterwywong 
1. I think the `/install/xcat` is only used if you specify the `--xcat-core=` or `--xcat-dep=` flags to `go-xcat` to download specified `.tar.bz2` files. If you just run `go-xcat install` or `go-xcat update`, the xcat.org online repository will be used directly.
2. I think the increase in time is significant. Perhaps running `yum list` on each package can be avoided and somehow skipped for the packages which have only one entry returned by `repoquery` ?
3. Another test would be to install an older version of xcat and upgrade it to latest or devel, like `go-xcat --xcat-version=2.15 install` and then `go-xcat --xcat-version=2.16 update`

**Comment by peterwywong** [comment]
@gurevichmark

check_repo_version_dnf is further modified to run "yum list" **ONLY IF** there are more than one version of the package.

The total elapsed time (**NOT** including package installation) is reduced from 106 seconds to 29 seconds. The current total elapsed time is 16 seconds.

Since it takes about 9 seconds to load packages from the repository, the non-loading time is increased from 7 seconds to 20 seconds (~3X). The additional 13 seconds is needed to get correct package information.

Here is the new code:

```
        local num_ver=0
        local last_index=0

        . . .
        while [[ -n "$1" ]]
        do
                num_ver=0
                for i in "${!name[@]}"
                do
                    if [[ "$1" = "${name[i]}" ]]
                    then
                       (( num_ver++ ))
                       last_index=$i
                    fi
                done
                if [[ $num_ver == "0" ]]; then
                   echo "(not found)"
                elif [[ $num_ver == "1" ]]; then
                    echo "${ver[last_index]}"
                else
                     xyz=`yum list ${name[last_index]} | tail -1 | sed -r 's/[0-9]*://' | grep ${name[last_index]} | awk '{print $2}'`
                     echo "$xyz"
                fi
                shift
        done
```
In addition, **sed -r s/[0-9]*://'** is to remove the Epcoh number, e.g., 1:, 4:. The additional 1: and 4: make invalid version numbers.

Yesterday, the xCAT version was updated from 2.16.1 to devel. It is clear that xnba-undi was upgraded from 1.0.3-131028 to 1.20.1-0.

However, fping is not installed after the update. It will be looked into next.

**Comment by peterwywong** [comment]
Yesterday, we spent some time to discuss the new code for processing **go-xcat --xcat-version=devel update**.

Based on the current code in the repo, we have the following output:

```
xCAT Core Packages
==================

Package Name                Installed                      In Repository
------------                ---------                      -------------
perl-xCAT                   2.16-snap202006161607          2.16.3-snap202105260049
xCAT                        2.16-snap202006161607          2.16.3-snap202105260049
xCAT-SoftLayer              (not installed)                2.16.3-snap202105260049
xCAT-buildkit               2.16-snap202006161607          2.16.3-snap202105260049
xCAT-client                 2.16-snap202006161607          2.16.3-snap202105260049
xCAT-confluent              (not installed)                2.16.3-snap202105260049
xCAT-csm                    (not installed)                2.16.3-snap202105260049
. . .

xCAT Dependency Packages
========================

Package Name                Installed                      In Repository
------------                ---------                      -------------
elilo-xcat                  3.14-4                         3.14-4
fping                       (not installed)                3.10-4.el8
goconserver                 0.3.2-snap202005211628         0.3.2-snap201909161515
grub2-xcat                  2.02-0.76.el7.1.snap2019051602 2.02-0.76.el7.1.snap2019051602
ipmitool-xcat               1.8.18-3                       1.8.18-2
net-snmp-perl               5.8-7.el8                      5.8-10.el8
perl-AppConfig              (not installed)                1.71-13.el8
. . .
```

The xcat-core section looks fine, so I want to have a new bash function to handle the xcat-dep section separately.

The idea is this: run **yum update <package name> --assumeno** to check whether the word **Upgrading** is there or not. If so, get the line that contains the package name and return the third item (the new version number).

For example:
```
======================================================================================================================================================================
 Package                                   Arch                                  Version                                Repository                               Size
======================================================================================================================================================================
Upgrading:
 elilo-xcat                                noarch                                3.14-6                                 xcat-dep                                 68 k

Transaction Summary
======================================================================================================================================================================
Upgrade  1 Package
```

It should work for the xcat-dep section.

In the cases of no update, the version number is **not** in the output. It would take additional time to get the version number. We have decided to leave it blank, which would reduce the overall elapsed time.

Then, I noticed that we have (not installed) in the xcat-core section as well. The new code must work for the xcat-core section too. That is, we should leave the third column blank for those packages where no updates are needed.

It turns out that there is complication there.

The results of **yum update perl-xCAT** and **yum update xCAT** are different from what we saw in the xcat-dep section. The code needs to be modified to handle both sections.

**yum update perl-xCAT** produces the following:

```
Dependencies resolved.
======================================================================================================================================================================
 Package                                          Arch                         Version                                           Repository                      Size
======================================================================================================================================================================
Upgrading:
 perl-xCAT                                        noarch                       4:2.16.3-snap202105260049                         xcat-core                      610 k
 xCAT                                             ppc64le                      2.16.3-snap202105260049                           xcat-core                      251 k
 xCAT-client                                      noarch                       4:2.16.3-snap202105260049                         xcat-core                      443 k
 xCAT-genesis-scripts-ppc64                       noarch                       1:2.16.3-snap202105260049                         xcat-core                       59 k
 xCAT-genesis-scripts-x86_64                      noarch                       1:2.16.3-snap202105260049                         xcat-core                       59 k
 xCAT-probe                                       noarch                       4:2.16.3-snap202105260049                         xcat-core                       92 k
 xCAT-server                                      noarch                       4:2.16.3-snap202105260049                         xcat-core                      1.8 M
 goconserver                                      ppc64le                      0.3.3-snap202011021041                            xcat-dep                       6.8 M

Transaction Summary
======================================================================================================================================================================
Upgrade  8 Packages
```

There are multiple lines returned. In this case, we can simply grep the line with **perl-xCAT** and get the third item (version number). 
<<Note: the epoch number (the number before the colon) is returned as well. An additional **cut** command is needed to remove it.>>

A side question: Why do we need to have epoch numbers for our xCAT RPMs? Is it because we have a different naming or numbering scheme at some point?

**yum update xCAT** gives more challenges. It gives the same output as above. However, the package name "xCAT" is a sub-string of the names of other packages. The "grep" command will return multiple lines, not ONE.

I spent quite some time trying to restrict the output to something quite unique to the xCAT pacakge or use various options of the greb command to get one unique line. Finally, I actually increased the output content with "-v". It has the following:

```
---> Package perl-xCAT.noarch 4:2.16-snap202006161607 will be upgraded
---> Package perl-xCAT.noarch 4:2.16.3-snap202105260049 will be an upgrade
---> Package xCAT.ppc64le 2.16-snap202006161607 will be upgraded
---> Package xCAT.ppc64le 2.16.3-snap202105260049 will be an upgrade
---> Package xCAT-client.noarch 4:2.16-snap202006161607 will be upgraded
---> Package xCAT-client.noarch 4:2.16.3-snap202105260049 will be an upgrade
```

The key is that there is a "space" and a "dot" before and after xCAT so that "grep" can return a unique version number.

That is what we have now for **go-xcat --xcat-version=devel update**. Note that I changed the title in the third column from "In Repository" to "In Repository for Update". It is subject to change based on your input.

```
xCAT Core Packages
==================

Package Name                Installed                      In Repository for Update
------------                ---------                      ------------------------
perl-xCAT                   2.16-snap202006161607          2.16.3-snap202105260049
xCAT                        2.16-snap202006161607          2.16.3-snap202105260049
xCAT-SoftLayer              (not installed)
xCAT-buildkit               2.16-snap202006161607          2.16.3-snap202105260049
xCAT-client                 2.16-snap202006161607          2.16.3-snap202105260049
xCAT-confluent              (not installed)
xCAT-csm                    (not installed)
xCAT-genesis-scripts-ppc64  2.16-snap202006161607          2.16.3-snap202105260049
xCAT-genesis-scripts-x86_64 2.16-snap202006161607          2.16.3-snap202105260049
xCAT-openbmc-py             (not installed)
xCAT-probe                  2.16-snap202006161607          2.16.3-snap202105260049
xCAT-server                 2.16-snap202006161607          2.16.3-snap202105260049
xCAT-test                   (not installed)
xCAT-vlan                   (not installed)
xCATsn                      (not installed)

xCAT Dependency Packages
========================

Package Name                Installed                      In Repository for Update
------------                ---------                      ------------------------
elilo-xcat                  3.14-4                         3.14-6
fping                       (not installed)
goconserver                 0.3.2-snap202005211628         0.3.3-snap202011021041
grub2-xcat                  2.02-0.76.el7.1.snap2019051602
ipmitool-xcat               1.8.18-3
net-snmp-perl               5.8-7.el8
perl-AppConfig              (not installed)
perl-Crypt-CBC              2.33-20.el8
perl-Crypt-Rijndael         1.13-10.el8
perl-Crypt-SSLeay           0.72-20.el8
perl-Digest-SHA1            2.13-23.el8
perl-Expect                 1.35-6.el8
perl-HTML-Form              6.03-19.el8
perl-HTTP-Async             0.30-2
perl-IO-Stty                0.03-21.el8
perl-IO-Tty                 1.12-13.el8
perl-JSON                   2.97.001-4.el8
perl-Mail-Sender            0.903-7.el8
perl-Net-HTTPS-NB           0.14-2
perl-Net-Telnet             3.04-9.el8
perl-SOAP-Lite              (not installed)
pyodbc                      (not installed)
syslinux-xcat               3.86-2
xCAT-genesis-base-ppc64     2.14.5-snap201811160710
xCAT-genesis-base-x86_64    2.14.5-snap201811190037
xnba-undi                   1.0.3-131028                   1.20.1-0
yaboot-xcat                 1.3.17-rc1

xCAT is going to be updated.
Continue? [y/n]
```

And this is the new code for check_repo_version_dnf:
```
function check_repo_version_dnf()
{
        type dnf >/dev/null 2>&1 || return 255

        for i in "$@"
        do
             dnf -v update $i --assumeno 2> /tmp/$i-err 1> /tmp/$i-1
             grep " $i\." /tmp/$i-1 | grep an > /tmp/$i-2
             if [[ -s /tmp/$i-2 ]]
             then
                 awk '{print $4}' /tmp/$i-2 | cut -d ":" -f2
             else
                 echo " "
             fi
             rm -f /tmp/$i-1 /tmp/$i-2 /tmp/$i-err
        done
        return 0
}
```

A similar change will be made to check_repo_version_yum.

It takes much longer time to get the above CORRECT result. Effort will be made to increase its performance.

I will do more testing, e.g., from RHEL 7.6, xCAT 2.16.0 to devel, from RHEL 8.2 xCAT 2.16.0 to xCAT 2.16.1. Just a few more combinations to make sure it works as expected for older and newer RHEL distros.

**Comment by gurevichmark** [comment]
* Perhaps performance can be improved by keeping output of the `dnf` in memory, instead of writing to `/tmp` file.
* Another upgrade path to test is from xCAT `2.14` to xCAT `2.16`

**Comment by peterwywong** [comment]
Can you give an example on keeping the output of dnf in memory? In some tmpfs location?

**Comment by peterwywong** [comment]
Now, when a package is **(not installed)**, we leave its third column empty. But it does not look good when we **FIRST** install it on a system.
```
xCAT Core Packages
==================

Package Name                Installed                      In Repository for Update
------------                ---------                      ------------------------
perl-xCAT                   (not installed)
xCAT                        (not installed)
xCAT-SoftLayer              (not installed)
xCAT-buildkit               (not installed) ...

xCAT Dependency Packages
========================

Package Name                Installed                      In Repository for Update
------------                ---------                      ------------------------
elilo-xcat                  (not installed)
fping                       (not installed)
goconserver                 (not installed)
grub2-xcat                  (not installed) ...
```
There is no package information given.

Indeed, there are two cases. fping will not be installed (leaving the third column blank is fine), but most of the above will be. Need to find a method to distinguish them.

**Comment by peterwywong** [comment]
The following have been tested on Power systems and they are successful. Note I focus on the update information to be displayed, not the actually update.
(1) RHEL 7.6: xCAT 2.14.6 -> xCAT 2.16.2
(2) RHEL 8.0: xCAT 2.16.0 --> devel
(3) RHEL 8.0: xCAT 2.16.0 -> xCAT 2.16.1
(4) RHEL 8.2: xCAT 2.16.1 -> devel
(5) RHEL 8.2: xCAT 2.16.2 -> devel

check_repo_version_yum is modified and used by RHEL 7.x.
It is mostly identical to check_repo_version_dnf, except the change from dnf to yum.

Here are some performance measurements with **go-xcat --xcat-version=devel update**. Each result is an average of 3 runs.
- On RHEL 7.6, it has xCAT 2.16.2:
   The current go-xcat: 6 seconds.
   The new go-xcat: 42 seconds (7x)
- On RHEL 8.2, it has xCAT 2.16.2:
   The current go-xcat: 16 seconds
   The new go-xcat: 102 seconds (6.4x)

We should have the correct display now and are working on improving the performance. There could be a performance difference between yum and dnf.

Note that we also need to handle the distinction between a package will not be installed and one will be installed. For the first installation, both cases have (not installed) in the second column. The additional logic will indeed increase the time inevitably.

**Comment by gurevichmark** [comment]
> 
> 
> Can you give an example on keeping the output of dnf in memory? In some tmpfs location?

I was thinking of something similar to `get_package_list_zypper()`, where the output of `zypper` command and piped into `awk` for more processing.

**Comment by peterwywong** [comment]
Thanks Mark.

I did think of combining the following two commands into one:

             dnf -v update $i --assumeno 2> /tmp/$i-err 1> /tmp/$i-1
             grep " $i\." /tmp/$i-1 | grep an > /tmp/$i-2

And change **2> /tmp/$i-err** into **2> /dev/null**. By doing so, there is no need to remove **/tmp/$i-err** later. Without "2>", some error information, such as the failed dependency information for net-snmp-perl, could show up among three columns of data.

As you said above about awk, I might be able to move it too with the above combined command: in that case, three commands into one. Therefore, no output file in storage is involved.

I will also evaluate the performance of dnf and yum.

**Comment by peterwywong** [comment]
dnf or yum is the top contributor to the elapsed time for running go-xcat with either update or install. Therefore, we should avoid calling them as much as possible.

When there is only one version returned by "dnf -q --qf" or "repoquery -q --qf", that version is displayed in the 3rd column without further inquiry.

When there are multiple versions returned, additional dnf or rpm calls are made to get the version to be installed based on the operating system installed.

Since the existing code does not return correct package versions, its short elapsed time, in a sense, is immaterial.
The times given below are for reference purposes.

The system already has xCAT 2.16.3 installed and "go-xcat --xcat-version=devel update" is run and measured.

On a RHEL 7.6 VM, the existing algorithm takes about 6 seconds, and the new algorithm 6 seconds. Practically, no change.

On a RHEL 8.4 VM, the existing algorithm takes 17 seconds, and the new algorithm 38 seconds, 2.2x longer.
