### ISSUE TITLE
xCAT status?

### ISSUE THREAD

**Issue by kcgthb** [xcat2/xcat-core#7405]
Hi!

I realize that this is not necessarily a straightforward question, but given the lack of releases, commits, or even activity on issues, I guess a number of people are starting to wonder if the project is still actively maintained, or if it's been more or less abandoned.

Could someone clarify what's the current status of the xCAT project?

Thanks!

**Comment by besawn** [comment]
@gurevichmark , @peterwywong , and I have been the primary xCAT maintainers for the past few years. This year, we have moved on to new roles unrelated to xCAT and can no longer continue to support the project. As a result, we plan to archive the project on December 1, 2023. xCAT 2.16.5, released on March 7, 2023, is our final planned release.

We would consider transitioning responsibility for the project to a new group of maintainers if members of the xCAT community can develop a viable proposal for future maintenance. 

Thank you all for you support of the project over the past 20+ years.

**Comment by samveen** [comment]
@besawn I have been a project member on github xCAT organization for the last 4 years. I can help with some of the maintenance load here on github, if required.

**Comment by kcgthb** [comment]
Same here! I'd be happy to help.

**Comment by besawn** [comment]
@samveen @kcgthb Thank you for the offer, I will keep you in the loop as the discussion about future maintenance develops.

**Comment by banuchka** [comment]
Happy to help as well. I have been a user of xCAT since 2011 for our infrastructure deployment. It is my day-to-day tool, to be honest.

**Comment by samveen** [comment]
@besawn @kcgthb @whowutwut I've had a look around the possibilities for management of xCAT as a project and from what I can make out, the best bet seems to be one of the existing umbrella projects, instead of setting up something for xCAT. The following foundations / organizations seem to be good bets:
-  The [Apache Foundation, AKA ASF](https://www.apache.org/)(in particular their  [Incubator](https://incubator.apache.org/) program) (the source needs to be re-licencing under an ASF Compatible license, No GPL variants)
-  [Software in the Public Interest](https://www.spi-inc.org/)
- Eclipse foundation (but they're Java focused)
- The Linux Foundation (We're not as critical-internet-infra as the rest of their projects, though)

There is a whole list over at https://en.wikipedia.org/wiki/List_of_free_and_open-source_software_organizations which could serve for this. 

Requirements for shifting the project would probably need at least the following assigned  from IBM to the the target organization:
- xCAT copyrights
- DNS rights
- Build keys
- Allowing the code to be re-licensed into a compatible license at the target organization if not.
- Lenovo's agreement to everything if they're an interested party?

@kcgthb Killian, does Stanford have some organizational unit that might be interested and able to take responsibility for this? That might bypass issues by allowing IBM to write off this as academic donations (or whatever the equivalent US tax framework names are)?

**Comment by kcgthb** [comment]
> @kcgthb Killian, does Stanford have some organizational unit that might be interested and able to take responsibility for this? That might bypass issues by allowing IBM to write off this as academic donations (or whatever the equivalent US tax framework names are)?

I'll ask around but I don't think Stanford has the structure nor the resources to take this on, unfortunately.

**Comment by besawn** [comment]
Note: On September 1, 2023, the xCAT maintainers announced the archive of the project on December 1, 2023. In response to that announcement, members of the xCAT community have expressed interest in continuing the project and are in the process of forming a plan to maintain the project into the future. In light of these developments, the xCAT project will not be archived on December 1, 2023 in order to allow the community time to develop a plan for future stewardship of the project.

**Comment by viniciusferrao** [comment]
For anyone seeing this, it's 2026 and xCAT is more alive than never.
