### ISSUE TITLE
Unable to start xcatd on RHEL9 using xCAT version 2.16.5

### ISSUE THREAD

**Issue by abhishek-sa1** [xcat2/xcat-core#7451]
I am trying to install xCAT on `RHEL9 `OS using version 2.16.5. With tarball available for xCAT 2.16.5, installation failed due to missing dependency of `perl-Expect`.  This package is available in `epel9 `repository and after configuration of the epel9 repository, installation of xCAT package was successful. 

After installing xCAT, xcatd services is not starting and stuck at activating state. journalctl logs shows following error:

`xcatd[15210]: Error, don't know how to start on this platform`

@samveen @Obihoernchen  Can you please confirm RHEL9 support of xCAT using 2.16.5 tarball.

In next `xCAT 2.17` version, is there a support of RHEL 9.4 OS?

**Comment by ocfmatt** [comment]
Hello,

RHEL9 and derived distributions do not install the deprecated init logic from previous major releases. You should be able to resolve this startup problem by installing `initscripts` from RHEL baseos repo.

The work being done towards xCAT 2.17 will ensure it has full support for RHEL 9 based distributions.

Regards,
Matt.

**Comment by abhishek-sa1** [comment]
@ocfmatt I installed `initscripts `and still facing issue to start xcatd service. Facing same error.

**Comment by ocfmatt** [comment]
Hello,

This issue is caused by xCAT's startup function looking for init functions files in a Redhat and Ubuntu specified location as per https://github.com/xcat2/xcat-core/blob/master/xCAT-server/etc/init.d/xcatd#L56-L74

On RHEL and Rocky 9 systems I have access to `/etc/init.d/functions` is present but looking at the initscripts package it installs functions to `/etc/rc.d/init.d/functions` and only creates a directory for `/etc/init.d` so I'll need to check how this file is being installed.

As a workaround, you should be able to install initscripts, copy or link `/etc/rc.d/init.d/functions` to `/etc/init.d/functions` and then install xCAT to make sure it writes `/etc/init.d/xcatd`.

Regards,
Matt.

**Comment by Obihoernchen** [comment]
If you install xCAT 2.16.5 without initscripts it will break your /etc/init.d/functions file. It will mess up symlinks etc. Installing initscripts afterwards will not fix it.
You need to clean this up (remove /etc/init.d), reinstall initscripts and install xCAT 2.16.5 again. Then it should work.<
If you use go-xcat to install xCAT it will take care of initscripts, epel etc.

**Comment by abhishek-sa1** [comment]
@Obihoernchen @ocfmatt  Thanks for the replies. It worked now

**Comment by abhishek-sa1** [comment]
@Obihoernchen Can i expect xCAT 2.17 release with RHEL9 support on July 31? Is this confirmed?

**Comment by Obihoernchen** [comment]
It's not a fixed date but we aim for it yes.

**Comment by abhishek-sa1** [comment]
@Obihoernchen Thanks for the information
