### ISSUE TITLE
Prototype of xcat.org home page for feedback collection

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat-core#77]
I created a draft xcat.org home page preview for feedback collection. It is a simple page with navigation bar and content I grabbed from xcat.sourceforge.net. Any comment is welcome.

BTW, I think we should create a high quality xCAT logo.

![xcat org](https://cloud.githubusercontent.com/assets/12424088/9219158/665b39c2-410b-11e5-973d-d970e949f959.png)

**Comment by daniceexi** [comment]
yes, I agree that we need to make a beatiful logo for xCAT. 

In the pic, I think the color of head bar need be changed and font size of hyperlink in the head bar need be bigger.

Is it hard to imitate the style of http://kubernetes.io/? We can add the architecture of xCAT in this landing page.

**Comment by bybai** [comment]
I think the word "XCAT.ORG" is not so clear.

**Comment by neo954** [comment]
I think we should use IBM color style. Below is the link.

http://www.ibm.com/design/language/resources/swatch-book.shtml

**Comment by whowutwut** [comment]
Regarding "XCAT.ORG" I think we should just label the logo with "xCAT" 

Is the spelling suppose to be "xcat" or "xCAT" or "XCAT"?  There is some inconsistency all over. 
The XCAT.ORG is the proposed landing page, website URL, not the product name.

**Comment by jjohnson42** [comment]
"I think we should use IBM color style."

I could be quirky and suggest the Lenovo style ;)  Of course I'm color blind so you could do whatever and tell me it's Lenovo's colors and I'd be none the wiser ;)

**Comment by whowutwut** [comment]
@jjohnson42  :+1:   :-)

**Comment by neo954** [comment]
The xCAT logo used in the draft design was collected from the page below. It looks like a quite old page.

http://ibmgeek.shacknet.nu/old_ibmgeek/pics/xcat_logos.html

**Comment by samveen** [comment]
Maybe Nathan (the author of the current logo) can help create a new one :).

Also, is it possible to change the xcat.org redirection from SF to GH?

**Comment by whowutwut** [comment]
Seems like some recent discussion on the xcat-users list indicate that they are enjoying the "crazy cat" logo being used today...

**Comment by daniceexi** [comment]
I am OK with the 'crazy cat', but I'd like to decorate the logo to make it more delicate.

**Comment by whowutwut** [comment]
@neo954 , on xcat.org server, can you upload a version of this page so that we could take a look at it.  For example, put at xcat.org/prototype/index.html or something like that.   Then when we go "live" we can just mv prototype/*  to the base directory 

Some comments on the layout... 

Top navigation bar 
* Are we moving away from SF bugs, so "tickets" should just link to "Issues" -> link to GitHub issues? 
* Git -> change to GitHub and link either https://github.com/xcat2/ or https://github.com/xcat2/xcat-core/
* What does clicking ``mailing-list`` do? 

The only other comment is that we should probably defer Getting started to the new documentation. It would not be that great to maintain two places where we have the same content.

**Comment by neo954** [comment]
The draft edtion main page is online.
http://xcat.org/draft.html

**Comment by arif-ali** [comment]
You got the link to the documentation wrong, The link should point to http://xcat-docs.readthedocs.org/en/latest/ instead of http://xcat.readthedocs.org/en/latest/

**Comment by whowutwut** [comment]
Good eye @arif-ali , I updated that link so we don't point to the wrong project!

**Comment by whowutwut** [comment]
1. I think under Download -> Files, we should get rid of 'OldFiles' and the 'docs' subdirectory. Anything else to clean up?   Are we only hosting from 2.11 onwards? 

2. Should Git renamed to GitHub on the top navigation bar?

3. Seems like the top navigation bar moves and spans the right most portion of the window.  (If i maximize the window) but the content is on a fixed percentage of the screen. Should we allow for the page to span the entire width? or limit the navigation so that it lines up with the release info?

**Comment by daniceexi** [comment]
@whowutwut @tingtli I agree to remove the files which for 2.10 and earlier to meet our decision that xcat.org only holds the files which generated after 2.10 release. Then the release files for 2.10.x will be put in xcat.org instead of SF.

Change name 'Git' to 'GitHub' is good for me.

**Comment by neo954** [comment]
The home page updated

* Git -> GitHub
* News with hyperlinks

**Comment by daniceexi** [comment]
Looks on the real page, the GitHub does not looks good. It make me feel strange that there's a link to Github, it should not have not relationship with xCAT. So I'd like change it to Code/Wiki.
And the Issue also a little confusing, I'd like change it to 'Issue/Bug/Discussion'

**Comment by cxhong** [comment]
the font looks strange to me...  the line spacing is too small?  or try to have different font style?

**Comment by neo954** [comment]
@cxhong Good point. The home page was updated with the following changes.

* Change line-height from not setting to 1.2. The defualt value is somewhere between 1.0 and 1.2. Different browsers have different defaults within this range.
* Change the spacing between paragraph to 2em. The may make the contents more easier to read.

**Comment by neo954** [comment]
@cxhong BTW, which browser do you use, and on which opererating system? I have Chrome / Firefox / Opera / elinks / lynx on my Thinkpad, which is running Linux.

**Comment by tingtli** [comment]
Since this is a discussion for homepage, I move it to 2.12
