### ISSUE TITLE
[feature-request] change mgmt method on the fly

### ISSUE THREAD

**Issue by arif-ali** [xcat2/xcat-core#83]
We have a system at a customer site who have flex systems, and therefore both the mpa/mp tables and ipmi tables have been filled.

There are occasions that you want to use the ipmi method or the blade one, but don't want to have to change the table when I want to stop. 

For example, 

```
rvitals -m ipmi compute001 leds
rpower -m ipmi compute001 off
reventlog -m ipmi compute001
```

The last one is a good one, as sometimes you don't get the same logs in the CMM as the SEL, so it's good to be able to change the mgt method in this way

**Comment by daniceexi** [comment]
I understand your problem.  But I have following arguments to reject this requestment:

1. It's hard to fix, since xCAT complicated mechanism to route a request to specific plugin module. If add a '-m mgt_method' will cause a lot change in the route logic.
2. Even we made the support, It needs deep understand of xcat to know how to use -m 'mgt_method'
3. Only flex customer has this specific requirement. 
4. There's a workaround that user can define two nodes for this machine, one with ipmi, another with blade.

**Comment by arif-ali** [comment]
1. As one who has contributed code before, I can understand the complexity in getting this to work
2. I guess the people who know xCAT, would use it as an advanced feature
3. I agree
4. This can become messy, and too many nodes defined in xCAT. We used to do this many years ago, when `otherinterfaces` wasn't available. I don't like the idea of having duplicate names

If there is significant issue, then no problem. We will have to educate the users
