### ISSUE TITLE
[DEV] apt-get update displays errors when pointing at the xCAT management node. 

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#841]
Installed a fresh copy of Ubuntu 14.04.3 on x86_64 VM.  The problem also occurs on the ppc64le installs and I would guess all installed kicked off by xCAT.  

When we run `apt-get update` on the Ubuntu node, we have some apt sources.list defined that points back to the xCAT management node, those all result in error **404: Not Found**

```

W: Failed to fetch http://10.2.6.23/install/ubuntu14.04.3/x86_64/dists/trusty/Release  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)
W: Failed to fetch http://10.2.6.23/install/ubuntu14.04.3/x86_64/dists/trusty-updates/main/source/Sources  404  Not Found
W: Failed to fetch http://10.2.6.23/install/ubuntu14.04.3/x86_64/dists/trusty-updates/restricted/source/Sources  404  Not Found
W: Failed to fetch http://10.2.6.23/install/ubuntu14.04.3/x86_64/dists/trusty-updates/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://10.2.6.23/install/ubuntu14.04.3/x86_64/dists/trusty-updates/restricted/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://10.2.6.23/install/ubuntu14.04.3/x86_64/dists/trusty-updates/main/binary-i386/Packages  404  Not Found
W: Failed to fetch http://10.2.6.23/install/ubuntu14.04.3/x86_64/dists/trusty-updates/restricted/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Can we investigate the root cause of this?

**Comment by daniceexi** [comment]
My question is in you case whether the xCAT MN still there? If yes, could you still access http://10.2.6.23/install/ubuntu14.04.3/x86_64/?

**Comment by immarvin** [comment]
hi @whowutwut , these entries in /etc/apt/sources.list pointing to MN are added by ubuntu installer, since we told preseed the repo/mirror on MN by specifying "/install/ubuntu14.04.3/x86_64/" in "osimage.pkgdir".

**Comment by whowutwut** [comment]
@daniceexi  Yes, this is a brand new install of Ubuntu from a mgmt node, ssh to the node and run ``apt-get update``.  

@immarvin  Is something wrong with what we specified in the preseed? or should we not use the mgmt node as a repo server?  It seems like the files it needs are not there or it's not configured correctly....

**Comment by daniceexi** [comment]
@whowutwut it because we used the entry like following in the preceed file. 
~~~~
d-i mirror/http/directory string /install/ubuntu15.04/x86_64
~~~~

The path **/install/ubuntu15.04/x86_64** is the one which generated by copycds from an iso. When doing the OS deployment, the ubuntu installer adds the corresponding http path like *http://10.2.6.23/install/ubuntuxx/x86_64/dists/trusty-updates** into the sources.list. The bad things is the ubuntu installer added the repo which does not exist in the xcat copycds repo path (the root cause for this was xcat gave a path, the ubuntu installer assumed there were several official repos in the path and then added. But the fact was some one them did not exist in the path.). Then you saw the error message that when running 'apt-get update', it failed. But this error only happens when try to retrive the repo. It won't affect the package install.

We have two choices:

* keep it as is
* remove the invalid entries from sources.list

We are sure the second choice is better, but it's not easy to figure out al the invalid entries from sources.list accurately.

**Comment by daniceexi** [comment]
It's a big deal to make the change, move it to next build.

**Comment by immarvin** [comment]
I failed to find any preseed configuration to eliminate the "trusty-updates" and "deb-src" lines in the source.list file after fresh installation. We have to add some code in the post.ubuntu to comment out these lines with ``sed`` as a dirty fix. 

Since this defect is not a block issue, the user can modify the source.list by themselves. I think we can keep this as a known issue for 2.12.

**Comment by whowutwut** [comment]
@bybai  I think the pull request needs to be merged first before pending.  @immarvin is assigned to that one currently.

**Comment by daniceexi** [comment]
@bybai's fix cannot cleanly remove all the unnecessary repo from source.list, it may also remove the useful repo. So we need to figure out a regular way.
@immarvin could you open a LTC bug to see whether there's any idea.

**Comment by immarvin** [comment]
opened a ticket to LTC  https://bugzilla.linux.ibm.com/show_bug.cgi?id=143318 to see whether there are any preseed directives to avoid "updates" and "security-updates" entries in sources.list in the installed system

**Comment by whowutwut** [comment]
I just tried to install Ubuntu 14.04.3 on a ppc64le node and I'm not able to install packages after the install for the same reason `apt-get install git` does not find the git package.  What was the solution here, or there is none?

**Comment by immarvin** [comment]
no response from LTC,
