### ISSUE TITLE
[FVT]mysqlsetup -i failed on ubuntu14.04.4 p8le 

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#906]
env:
root@c910f03fsp03v110:~# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://wwww.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
build:
lsdef - Version 2.12 (git commit c9ade4d09e7d719d32d3fe406edbbf098c804278, built Sun Apr 10 09:30:31 EDT 2016)
How to reproduce:
```
root@c910f03fsp03v110:/etc/apt/sources.list.d# mysqlsetup -i
 * Stopping MariaDB database server mysqld                                                                                                                                                    [ OK ] 
Input the alpha-numberic  password for xcatadmin in the MySQL database: 
Input the password for root in the MySQL database: 
 * Starting MariaDB database server mysqld                                                                                                                                                    [ OK ] 
 * Checking for corrupt, not cleanly closed and upgrade needing tables.
Command failed: /usr/bin/mysqladmin -u root password 123456 2>&1. Error message: /usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'.
----------------------------------->failed here
Warning, mysqladmin -u root password command failed, trying to set root password in MySQL. If root id has been defined in MySQL, and has a password then this message can be ignored.
Backing up xCAT Database to /root/xcat-dbback.
This could take several minutes.
Shutting down the xcatd daemon during database migration.
Stopping xcatd  * 
Restoring the xCAT Database with /root/xcat-dbback to MySQL database.
This could take several minutes.
Restarting xcatd isc-dhcp-server start/running, process 31120
 * 
xCAT is now running on the MySQL database
```

**Comment by immarvin** [comment]
seems to be caused by the fact that the root password input  on ``mysqlsetup -i`` is different with the one specified on mariadb installation, need to verify

**Comment by whowutwut** [comment]
@cxhong and I looked at this briefly, i think the cause of this is that we need to grant privileges for the xcatdb user in the newer versions of MariaDB in order to use the xcatdb.  You can verify by going into Mariadb as the xcatdb user and try to run ``use xcatdb``.  It should fail saying no privileges

**Comment by cxhong** [comment]
@whowutwut ,  looks like mysqlsetup code sets up the xcatdb user already.
````
my $createuser =
      "CREATE USER xcatadmin IDENTIFIED BY \'$::adminpassword\';\r";
    my $grantall = "";
    $grantall = "GRANT ALL on xcatdb.* TO xcatadmin@";
    $grantall .= "\'";
    $grantall .= "$::MN";
    $grantall .= "\'";
    $grantall .= " IDENTIFIED BY \'$::adminpassword\';\r";
``````````

and 
``````
MariaDB [xcatdb]> SELECT host,user,password FROM mysql.user;
+-------------+-----------+-------------------------------------------+
| host        | user      | password                                  |
+-------------+-----------+-------------------------------------------+
| localhost   | root      | *8DB8413E28D4DB2FF73A45BACED76C20FE607F41 |
| 10.3.29.100 | xcatadmin | *8DB8413E28D4DB2FF73A45BACED76C20FE607F41 |
| fs1vm100    | xcatadmin | *8DB8413E28D4DB2FF73A45BACED76C20FE607F41 |
| %           | xcatadmin | *8DB8413E28D4DB2FF73A45BACED76C20FE607F41 |
+-------------+-----------+-------------------------------------------+
`````````

**Comment by cxhong** [comment]
There is different between mariadb installation on the ubuntu 14.0.4 with other ubuntu version.  on 14.04.4,  while process "apt-get install mariadb-server",  it will pop up a window to ask to setup root password.
![image](https://cloud.githubusercontent.com/assets/12398836/14626134/ff240178-05b6-11e6-9ee0-0975b33b54e9.png)

i tried put password or just leave empty, the result were same for this command:
````
# mysqladmin -u root password cluster
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'
````
i can get into mariadb database by "mysql -u root -pcluster", and even change the root privileges again.  didn't help.........

Except that error message, mysqlsetup were setup successfully on the xcat MN, all the tables are there and cluster is running fine.  It's possible can we ignore that message as what code said in the mysqlsetup:
````
else
    {
        $cmd = "/usr/bin/mysqladmin -u root password $::rootpassword";
    }

    # secure passwd in verbose mode
    my $tmpv = $::VERBOSE;
    $::VERBOSE = 0;
    xCAT::Utils->runcmd($cmd, 0);
    $::VERBOSE = $tmpv;
    if ($::RUNCMD_RC != 0)
    {
        xCAT::MsgUtils->message(
            "I",
            "Warning, mysqladmin -u root password command failed, trying to set root password in MySQL. If root id has been defined in MySQL, and has a password then this message can be ignored."
            );

    }
`````

**Comment by whowutwut** [comment]
I think because there's a prompt for the user to set the password when doing the apt-get install , we're unable to use the mysqladmin command to set the root password at a later time because it some settings... 
 
@immarvin  any ideas how to resolve?

**Comment by immarvin** [comment]
hi thanks for your investigation.

 , on 14.04.4, "apt-get install mariadb-server" will prompt user 2 or 3 times to specify the root password for mariadb, if user just press "Enter" to proceed, the root password will be left blank, otherwise, user need to remember the password he/she set.

For "mysqlsetup -i",   the script will first prompt user to specify the root password and xcatadmin password for mysql, these specified values are intended to set the passwords if they are not set. then suppose the root password is blank and try to set the root password with "mysqladmin -u root password <password>"; if the root password has been set on mariadb-server installation,  this step will fail and prompt the warning message(just a warning and will not stop the script executing)
````
Warning, mysqladmin -u root password command failed, trying to set root password in MySQL. If root id has been defined in MySQL, and has a password then this message can be ignored.
````

then the script will verify the root password of mysql with the one specified at the beginning of "mysqlsetup -i", if it is blank, the script will prompt user to specify the password set previously, 

````
Warning, mysqladmin -u root password command failed, trying to set root password in MySQL. If root id has been defined in MySQL, and has a password then this message can be ignored.
Enter password: 
````
if the specified password is correct, the "mysqlsetup -i" will continue to execute  ; otherwise, the "mysqlsetup -i" will failed with
````

Wrong MySQL root password
```` .

so for this issue, the error message can be ignored as prompted, it is the case that the password has been set on installation and specified t the beginning of "mysqlsetup -i". The process is right but the message might be confused for the user.

**Comment by immarvin** [comment]
I think the mysqlsetup code involves some ambiguity between setting up and authenticating root password. we can refine the code like this:
(1) check whether the root password has been set before 
     with ``/usr/bin/mysqladmin -u root  version``
     if the return code is zero, go to step 3 ; otherwise, goto step 2
(2) prompt the user that the root password has been set before and ask user for root password and verify the root password user provided, if failed, prompt ``Wrong MySQL root password`` and exit; otherwise, goto step 4
(3) prompt the user that the root password has not been setup, ask user to specify a root password and set it with ``/usr/bin/mysqladmin -u root  password``
(4) setup xcatadmin id and other stuff
....

what do you think @whowutwut @cxhong ?

**Comment by immarvin** [comment]
hi @cxhong , since you have worked on mysqlsetup before, can you work on this issue to refine the mysqlsetup -i process?

**Comment by cxhong** [comment]
the command ```/usr/bin/mysqladmin -u root version ``` to check the root password will cause more misleading error message from output:
````
Command failed: mysqladmin -u root version 2>&1. Error message: mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!.
`````
Can we reset the password (whether it was set or not) using 
````
mysqld_safe --skip-grant-tables & 
.....
UPDATE mysql.user SET Password=PASSWORD('NEW-PASSWORD') WHERE User='root';
......
`````
Running MySQL with the —skip-grant-tables option enabled is insecure, and should only be done for a brief period while we reset the password.

**Comment by daniceexi** [comment]
@cxhong In the first code section **Command failed ...** of your last comment, looks like the mysql service did not start.

**Comment by cxhong** [comment]
oh, I copied/pasted one error message without mysql was running. 
anyway  it will produce same error message as this issue:
````
Command failed: mysqladmin -u root version 2>&1. Error message: mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'.
`````

**Comment by cxhong** [comment]
another thought, we don't have to fix this issue, if we failed to set password because root password is already set, it doesn't matter in this case.   we will verify the password anyway, it will exit the code if verification failed.  the current flow of setupmysql command:
1) ask user input root password
2) setupmysqlroot :   call ```/usr/bin/mysqladmin -u root password $::rootpassword```
           ----command success:  root password is set
           ---- command failed:   will still take this password  as root password and output the warning message : 
        ````
         "Warning, mysqladmin -u root password command failed, trying to set root password in MySQL. If root id has been defined in MySQL, and has a password then this message can be ignored."
          ````
        
3) verifymysqlroot
   ---if verification failed, it will exit the command with error message "Wrong MySQL root password"

**Comment by junxiawang** [comment]
discussed will not support ubuntu hierarchical so closes the issue
