### ISSUE TITLE
[DEV]zypper install is locked by the y2base on sles12.1 during the provisioning. 

### ISSUE THREAD

**Issue by cxhong** [xcat2/xcat-core#929]
working on sles12.1 hierarchy support for issue  #898,  during the server node provisioning, it hit following error message while it was trying to install otherpkgs.

````
pkgsarray: -perl-doc xcat/xcat-core/xCATsn xcat/xcat-dep/sles12/ppc64le/conserver-xcat, 3
yum: 0, apt: 0, zypper: 1
System management is locked by the application with pid 2729 (y2base).
Close this application before trying again.
System management is locked by the application with pid 2729 (y2base).
Close this application before trying again.
System management is locked by the application with pid 2729 (y2base).
Close this application before trying again.
System management is locked by the application with pid 2729 (y2base).
Close this application before trying again.

`````
after server node provisioned, ran updatenode command and it worked fine

`````
# updatenode fs1vm301 -P otherpkgs
fs1vm301: vpdupdate is not supported on the pSeries KVM Guest
fs1vm301: xcatdsklspost: updating VPD database
fs1vm301: xcatdsklspost: downloaded postscripts successfully
fs1vm301: Fri Nov 27 08:20:11 EST 2015 Running postscript: otherpkgs
fs1vm301: pkgsarray: -perl-doc xcat/xcat-core/xCATsn xcat/xcat-dep/sles12/ppc64le/conserver-xcat, 3
fs1vm301: yum: 0, apt: 0, zypper: 1
fs1vm301: Postscript: otherpkgs exited with code 0
fs1vm301: Running of postscripts has completed.

`````

Yong Song opened a bugzilla issue
https://bugzilla.linux.ibm.com/show_bug.cgi?id=140313

**Comment by immarvin** [comment]
LTC ticket :https://bugzilla.linux.ibm.com/show_bug.cgi?id=140313

**Comment by daniceexi** [comment]
@cxhong Looks like the Yast was trying to install xCATsn or something when the issue happened. Generally, the xCATsn is installed in otherpkgslist. But you were trying to install it in pkglist (Yast phase), right?

**Comment by immarvin** [comment]
hi @daniceexi , for sles, the yast will be run on the 1st reboot after installation, the PBS otherpkgs is called by ``service xcatpostinit1 start``

**Comment by cxhong** [comment]
the bugzilla bug still open.  

workaround:  after service node is up, run:
````
updatenode nodename -P otherpkgs
````

**Comment by daniceexi** [comment]
@cxhong @immarvin But xcatsn packages are installed through otherpkgs which is run in the postbootscript, it will be triggered after the OS reboot, right?

**Comment by cxhong** [comment]
that's the step I saw from xcat.log
1) Running AutoYast Pre-Installation script
2) Running AutoYaST Chroot-Installation script...
3) Running AutoYaST Post-Installation script...
 ---download the postscripts
 --- found zypper
then, as soon as we run zypper command, it hit the issue:
````
++ zypper --non-interactive refresh
+ result='System management is locked by the application with pid 2686 (y2base).
Close this application before trying again.'
````
I added debug code to otherpkgs postscript and this is output 
````
++ grep -v grep
++ grep y2base
++ ps -ef
+ str_out='root      2686  2196 10 18:20 hvc0     00:00:14 y2base installation ("continue") ncurses'
+ '[' 0 -eq 0 ']'
++ awk '{print $2}'
++ echo root 2686 2196 10 18:20 hvc0 00:00:14 y2base installation '("continue")' ncurses
``````

So while y2base process is running, we can't run any zypper command,  why y2base process still running after OS installed and node reboot?  it's safe can we kill y2base process in this stage?

**Comment by immarvin** [comment]
hi @cxhong ,

please try to add 2 options in the template file, 
````
...
 <mode>
...
    <final_reboot config:type="boolean">true</final_reboot>
    <final_restart_services  config:type="boolean">false</second_stage>
...
  </mode>
...
````
to introduce another reboot after installation and configuration, so that the "xcatpostinit1" which calls otherpkgs will be run after the final reboot. 

The explanation of the 2 options:
````
 final_reboot:
If you set this to true, the machine will reboot at the very end of the installation (when everything is installed and configured at the end of the second stage).
<final_reboot config:type="boolean">true</final_reboot>
Optional. The default is false. It makes no sense to set this and final_halt to true.

 final_restart_services
If you set this entry to false, all services will not be restarted at the very end of the installation (when everything is installed and configured at the end of the second stage).
<final_restart_services config:type="boolean">false</final_restart_services>
Optional. The default is true.  
````

The full autoyast documentation is:
https://www.suse.com/documentation/sles-12/book_autoyast/data/createprofile_general.html

**Comment by daniceexi** [comment]
@cxhong One question is the otherpkgs for sles12 does not work because of this issue, right?

**Comment by cxhong** [comment]
@daniceexi , yes, once hit the issue,  xCAT will not create otherpkgs repo and xCATsn package will not able to install on the service node.

**Comment by cxhong** [comment]
tried with @immarvin 's suggestion and changed template file.  after provisioning the node, it had same error messages.

**Comment by cxhong** [comment]
check this : https://sourceforge.net/p/xcat/bugs/3272/

**Comment by cxhong** [comment]
@immarvin 
Good news:   stop network in the end of xcat.post did help.  the otherpkgs can able to install now.  I will to do few more test, then check in the code.

**Comment by immarvin** [comment]
Looked into this issue with @cxhong , we found that "service network restart" in the post-install script caused the conflict between the start of service "xcatpostinit1" and "YaST2-Second-Stage". The fix is to stop network service at the end of post-install script.

we found that "zypper refresh" in the otherpkgs is blocked by ``y2base``
````
 "System management is locked by the application with pid 2729 (y2base).
Close this application before trying again."
````

``y2base`` is started by ``YaST2-Second-Stage.service``, which is the second-stage of suse installation performing system configuration on the 1st boot after installation.  It is a system service managed by systemd, just llke network.service, xcatpostinit1 ,etc.   

````
++ systemctl status YaST2-Second-Stage.service
+ result='YaST2-Second-Stage.service - YaST2 Second Stage
   Loaded: loaded (/usr/lib/systemd/system/YaST2-Second-Stage.service; enabled)
   Active: activating (start) since Tue 2016-05-10 08:38:59 EDT; 3min 9s ago
 Main PID: 717 (YaST2.Second-St)
   CGroup: /system.slice/YaST2-Second-Stage.service
           ├─ 717 /bin/sh /usr/lib/YaST2/startup/YaST2.Second-Stage
           ├─1622 bash
           ├─2169 /bin/sh /usr/lib/YaST2/startup/YaST2.call installation continue
           └─2657 y2base installation ("continue") ncurses
````

From Sles12, systemd is introduced  as a replacement of sysvinit to manage system services.  systemd supports that services can be started in parallel or in the specified order, it also provides compatibility for the existing sysvinit serivces.

the PBS "otherpkgs" is called in "xcatpostinstall"  , which is called by "service xcatpostinoit1 start" on the 1st reboot after installation. The "xcatpostini1" is specified to be started  after the "network" and "syslog" services are started.
````
cat /etc/init.d/xcatpostinit1 
#!/bin/sh
# IBM(c) 2007 EPL license http://www.eclipse.org/legal/epl-v10.html
# chkconfig: 345 84 59
# description: service node postboot script hack
# processname: xcatpostinit

### BEGIN INIT INFO
# Provides: xcatpostinit
# Default-Start: 3 4 5
# Default-stop: 0 1 2 6
# Required-Start: $network $syslog
# Should-Start: cron
# Required-Stop:
# Short-Description: xCATpost
# Description: xCAT post boot script
### END INIT INFO
...
````
 
 "YaST2-Second-Stage" is a "Type=oneshot" service and "RemainAfterExit=yes", which means that it's status will be "active" only after the execution of its "ExecStart" has been exited successfully.  The unit file of "YaST2-Second-Stage" specifies that "network.service"  should be activated after  "YaST2-Second-Stage".
````
fs2vm101:~ # cat /usr/lib/systemd/system/YaST2-Second-Stage.service 
[Unit]
Description=YaST2 Second Stage
After=apparmor.service local-fs.target plymouth-start.service
Before=getty@tty1.service display-manager.service network.service NetworkManager.service SuSEfirewall2_init.service SuSEfirewall2.service
ConditionPathExists=/var/lib/YaST2/runme_at_boot


[Service]
Type=oneshot
...
RemainAfterExit=yes
...
````

If all things is right, the "xcatpostinit1" service should be started after "YaST2-Second-Stage" has been "active". However, the network service is started in the post-installation script, i.e, "service network restart" in post.sles.common, which runs (during the first boot of the installed system, no services running) and breaks the specified service dependency and cause the conflict between "xcatpostini1" and "YaST2-Second-Stage".

**Comment by immarvin** [comment]
hi @cxhong , I verified the fix today, it works well.  Since this is a critical bug for 2.12, I committed a PR https://github.com/xcat2/xcat-core/pull/1087 today so that it can be reviewed and verified by FVT ASAP. Please review the PR here: https://github.com/xcat2/xcat-core/pull/1087
